using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.CampaignBehaviors
{
	// Token: 0x0200037D RID: 893
	public class CampaignBehaviorManager : ICampaignBehaviorManager
	{
		// Token: 0x06003421 RID: 13345 RVA: 0x000DA3F6 File Offset: 0x000D85F6
		public CampaignBehaviorManager(IEnumerable<CampaignBehaviorBase> inputComponents)
		{
			this.SetBehaviors(inputComponents);
			this._campaignBehaviorDataStore = new CampaignBehaviorDataStore();
			CampaignEvents.OnBeforeSaveEvent.AddNonSerializedListener(this, new Action(this.OnBeforeSave));
		}

		// Token: 0x06003422 RID: 13346 RVA: 0x000DA427 File Offset: 0x000D8627
		public void InitializeCampaignBehaviors(IEnumerable<CampaignBehaviorBase> inputComponents)
		{
			this.SetBehaviors(inputComponents);
			CampaignEvents.OnBeforeSaveEvent.AddNonSerializedListener(this, new Action(this.OnBeforeSave));
		}

		// Token: 0x06003423 RID: 13347 RVA: 0x000DA447 File Offset: 0x000D8647
		private void SetBehaviors(IEnumerable<CampaignBehaviorBase> inputComponents)
		{
			this._campaignBehaviors = inputComponents.ToList<CampaignBehaviorBase>();
		}

		// Token: 0x06003424 RID: 13348 RVA: 0x000DA458 File Offset: 0x000D8658
		public void RegisterEvents()
		{
			foreach (CampaignBehaviorBase campaignBehaviorBase in this._campaignBehaviors)
			{
				campaignBehaviorBase.RegisterEvents();
			}
		}

		// Token: 0x06003425 RID: 13349 RVA: 0x000DA4A8 File Offset: 0x000D86A8
		private void OnBeforeSave()
		{
			this._campaignBehaviorDataStore.ClearBehaviorData();
			foreach (CampaignBehaviorBase campaignBehaviorBase in this._campaignBehaviors)
			{
				this._campaignBehaviorDataStore.SaveBehaviorData(campaignBehaviorBase);
			}
		}

		// Token: 0x06003426 RID: 13350 RVA: 0x000DA50C File Offset: 0x000D870C
		public void LoadBehaviorData()
		{
			foreach (CampaignBehaviorBase campaignBehaviorBase in this._campaignBehaviors)
			{
				this._campaignBehaviorDataStore.LoadBehaviorData(campaignBehaviorBase);
			}
			this._campaignBehaviorDataStore.ClearBehaviorData();
		}

		// Token: 0x06003427 RID: 13351 RVA: 0x000DA570 File Offset: 0x000D8770
		public T GetBehavior<T>()
		{
			return this._campaignBehaviors.OfType<T>().FirstOrDefault<T>();
		}

		// Token: 0x06003428 RID: 13352 RVA: 0x000DA582 File Offset: 0x000D8782
		public IEnumerable<T> GetBehaviors<T>()
		{
			return this._campaignBehaviors.OfType<T>();
		}

		// Token: 0x06003429 RID: 13353 RVA: 0x000DA58F File Offset: 0x000D878F
		public void AddBehavior(CampaignBehaviorBase campaignBehavior)
		{
			this._campaignBehaviors.Add(campaignBehavior);
			campaignBehavior.RegisterEvents();
		}

		// Token: 0x0600342A RID: 13354 RVA: 0x000DA5A4 File Offset: 0x000D87A4
		public void RemoveBehavior<T>() where T : CampaignBehaviorBase
		{
			for (int i = this._campaignBehaviors.Count - 1; i >= 0; i--)
			{
				T t;
				if ((t = this._campaignBehaviors[i] as T) != null)
				{
					this._campaignBehaviors.Remove(t);
					CampaignEventDispatcher.Instance.RemoveListeners(t);
					return;
				}
			}
		}

		// Token: 0x0600342B RID: 13355 RVA: 0x000DA60B File Offset: 0x000D880B
		public void ClearBehaviors()
		{
			this._campaignBehaviors.Clear();
		}

		// Token: 0x0600342C RID: 13356 RVA: 0x000DA618 File Offset: 0x000D8818
		internal static void AutoGeneratedStaticCollectObjectsCampaignBehaviorManager(object o, List<object> collectedObjects)
		{
			((CampaignBehaviorManager)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600342D RID: 13357 RVA: 0x000DA626 File Offset: 0x000D8826
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._campaignBehaviorDataStore);
		}

		// Token: 0x0600342E RID: 13358 RVA: 0x000DA634 File Offset: 0x000D8834
		internal static object AutoGeneratedGetMemberValue_campaignBehaviorDataStore(object o)
		{
			return ((CampaignBehaviorManager)o)._campaignBehaviorDataStore;
		}

		// Token: 0x04001104 RID: 4356
		private List<CampaignBehaviorBase> _campaignBehaviors;

		// Token: 0x04001105 RID: 4357
		[SaveableField(1)]
		private readonly CampaignBehaviorDataStore _campaignBehaviorDataStore;
	}
}
