using System;
using System.Collections.Generic;
using TaleWorlds.Core;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.CampaignBehaviors
{
	// Token: 0x020003B2 RID: 946
	public class OrderOfBattleCampaignBehavior : CampaignBehaviorBase
	{
		// Token: 0x0600387F RID: 14463 RVA: 0x00101250 File Offset: 0x000FF450
		public OrderOfBattleCampaignBehavior()
		{
			this._siegeFormationInfos = new List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>();
			this._fieldBattleFormationInfos = new List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>();
		}

		// Token: 0x06003880 RID: 14464 RVA: 0x0010126E File Offset: 0x000FF46E
		public override void RegisterEvents()
		{
		}

		// Token: 0x06003881 RID: 14465 RVA: 0x00101270 File Offset: 0x000FF470
		public override void SyncData(IDataStore dataStore)
		{
			if (dataStore.SyncData<List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>>("_siegeFormationInfos", ref this._siegeFormationInfos) && this._siegeFormationInfos == null)
			{
				this._siegeFormationInfos = new List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>();
			}
			if (dataStore.SyncData<List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>>("_formationInfos", ref this._fieldBattleFormationInfos) && this._fieldBattleFormationInfos == null)
			{
				this._fieldBattleFormationInfos = new List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>();
			}
		}

		// Token: 0x06003882 RID: 14466 RVA: 0x001012C9 File Offset: 0x000FF4C9
		public OrderOfBattleCampaignBehavior.OrderOfBattleFormationData GetFormationDataAtIndex(int formationIndex, bool isSiegeBattle)
		{
			if (isSiegeBattle)
			{
				if (this._siegeFormationInfos.Count > formationIndex)
				{
					return this._siegeFormationInfos[formationIndex];
				}
				return null;
			}
			else
			{
				if (this._fieldBattleFormationInfos.Count > formationIndex)
				{
					return this._fieldBattleFormationInfos[formationIndex];
				}
				return null;
			}
		}

		// Token: 0x06003883 RID: 14467 RVA: 0x00101307 File Offset: 0x000FF507
		public void SetFormationInfos(List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData> formationInfos, bool isSiegeBattle)
		{
			if (isSiegeBattle)
			{
				this._siegeFormationInfos = new List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>(formationInfos);
				return;
			}
			this._fieldBattleFormationInfos = new List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData>(formationInfos);
		}

		// Token: 0x040011AE RID: 4526
		private List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData> _siegeFormationInfos;

		// Token: 0x040011AF RID: 4527
		private List<OrderOfBattleCampaignBehavior.OrderOfBattleFormationData> _fieldBattleFormationInfos;

		// Token: 0x02000708 RID: 1800
		public class OrderOfBattleFormationData
		{
			// Token: 0x06005572 RID: 21874 RVA: 0x0016D2E0 File Offset: 0x0016B4E0
			public OrderOfBattleFormationData(Hero commander, List<Hero> heroTroops, DeploymentFormationClass formationClass, int primaryWeight, int secondaryWeight, Dictionary<FormationFilterType, bool> filters)
			{
				this.Commander = commander;
				this.HeroTroops = heroTroops.ToArray();
				this.FormationClass = formationClass;
				this.PrimaryClassWeight = primaryWeight;
				this.SecondaryClassWeight = secondaryWeight;
				this.Filters = new Dictionary<FormationFilterType, bool>();
				foreach (FormationFilterType formationFilterType in filters.Keys)
				{
					this.Filters.Add(formationFilterType, filters[formationFilterType]);
				}
			}

			// Token: 0x06005573 RID: 21875 RVA: 0x0016D37C File Offset: 0x0016B57C
			internal static void AutoGeneratedStaticCollectObjectsOrderOfBattleFormationData(object o, List<object> collectedObjects)
			{
				((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06005574 RID: 21876 RVA: 0x0016D38A File Offset: 0x0016B58A
			protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				collectedObjects.Add(this.Commander);
				collectedObjects.Add(this.Filters);
				collectedObjects.Add(this.HeroTroops);
			}

			// Token: 0x06005575 RID: 21877 RVA: 0x0016D3B0 File Offset: 0x0016B5B0
			internal static object AutoGeneratedGetMemberValueCommander(object o)
			{
				return ((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).Commander;
			}

			// Token: 0x06005576 RID: 21878 RVA: 0x0016D3BD File Offset: 0x0016B5BD
			internal static object AutoGeneratedGetMemberValueFormationClass(object o)
			{
				return ((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).FormationClass;
			}

			// Token: 0x06005577 RID: 21879 RVA: 0x0016D3CF File Offset: 0x0016B5CF
			internal static object AutoGeneratedGetMemberValuePrimaryClassWeight(object o)
			{
				return ((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).PrimaryClassWeight;
			}

			// Token: 0x06005578 RID: 21880 RVA: 0x0016D3E1 File Offset: 0x0016B5E1
			internal static object AutoGeneratedGetMemberValueSecondaryClassWeight(object o)
			{
				return ((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).SecondaryClassWeight;
			}

			// Token: 0x06005579 RID: 21881 RVA: 0x0016D3F3 File Offset: 0x0016B5F3
			internal static object AutoGeneratedGetMemberValueFilters(object o)
			{
				return ((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).Filters;
			}

			// Token: 0x0600557A RID: 21882 RVA: 0x0016D400 File Offset: 0x0016B600
			internal static object AutoGeneratedGetMemberValueHeroTroops(object o)
			{
				return ((OrderOfBattleCampaignBehavior.OrderOfBattleFormationData)o).HeroTroops;
			}

			// Token: 0x04001CE2 RID: 7394
			[SaveableField(1)]
			public readonly Hero Commander;

			// Token: 0x04001CE3 RID: 7395
			[SaveableField(2)]
			public readonly DeploymentFormationClass FormationClass;

			// Token: 0x04001CE4 RID: 7396
			[SaveableField(3)]
			public readonly int PrimaryClassWeight;

			// Token: 0x04001CE5 RID: 7397
			[SaveableField(4)]
			public readonly int SecondaryClassWeight;

			// Token: 0x04001CE6 RID: 7398
			[SaveableField(5)]
			public readonly Dictionary<FormationFilterType, bool> Filters;

			// Token: 0x04001CE7 RID: 7399
			[SaveableField(6)]
			public readonly Hero[] HeroTroops;
		}
	}
}
