using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	public class ClanChangeKingdomLogEntry : LogEntry, IChatNotification, IWarLog
	{
		internal static void AutoGeneratedStaticCollectObjectsClanChangeKingdomLogEntry(object o, List<object> collectedObjects)
		{
			((ClanChangeKingdomLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.Clan);
			collectedObjects.Add(this.OldKingdom);
			collectedObjects.Add(this.NewKingdom);
		}

		internal static object AutoGeneratedGetMemberValueClan(object o)
		{
			return ((ClanChangeKingdomLogEntry)o).Clan;
		}

		internal static object AutoGeneratedGetMemberValueOldKingdom(object o)
		{
			return ((ClanChangeKingdomLogEntry)o).OldKingdom;
		}

		internal static object AutoGeneratedGetMemberValueNewKingdom(object o)
		{
			return ((ClanChangeKingdomLogEntry)o).NewKingdom;
		}

		internal static object AutoGeneratedGetMemberValue_byRebellion(object o)
		{
			return ((ClanChangeKingdomLogEntry)o)._byRebellion;
		}

		public bool IsVisibleNotification
		{
			get
			{
				return true;
			}
		}

		public override ChatNotificationType NotificationType
		{
			get
			{
				return base.MilitaryNotification(this.NewKingdom, this.OldKingdom);
			}
		}

		public ClanChangeKingdomLogEntry(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, bool byRebellion)
		{
			this.Clan = clan;
			this.OldKingdom = oldKingdom;
			this.NewKingdom = newKingdom;
			this._byRebellion = byRebellion;
		}

		public bool IsRelatedToWar(StanceLink stance, out IFaction effector, out IFaction effected)
		{
			IFaction faction = stance.Faction1;
			IFaction faction2 = stance.Faction2;
			Kingdom newKingdom = this.NewKingdom;
			effector = ((newKingdom != null) ? newKingdom.MapFaction : null);
			Kingdom oldKingdom = this.OldKingdom;
			effected = ((oldKingdom != null) ? oldKingdom.MapFaction : null);
			return (this.OldKingdom == faction && this.NewKingdom == faction2) || (this.OldKingdom == faction2 && this.NewKingdom == faction);
		}

		public TextObject GetNotificationText()
		{
			if (this.NewKingdom != null)
			{
				TextObject textObject = GameTexts.FindText("str_notification_change_faction", null);
				textObject.SetTextVariable("FACTION", this.NewKingdom.InformalName);
				textObject.SetTextVariable("CLAN_NAME", this.Clan.Name);
				return textObject;
			}
			return TextObject.Empty;
		}

		public override ImportanceEnum GetImportanceForClan(Clan clan)
		{
			if (clan == this.Clan)
			{
				return ImportanceEnum.ReasonablyImportant;
			}
			if (clan.Kingdom != null && (clan.Kingdom == this.OldKingdom || clan.Kingdom == this.NewKingdom))
			{
				return ImportanceEnum.SomewhatImportant;
			}
			return ImportanceEnum.Zero;
		}

		public override void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
		{
			score = ImportanceEnum.Zero;
			comment = "";
			if (this.Clan == Clan.PlayerClan && talkTroop.IsLord)
			{
				StringHelpers.SetCharacterProperties("TT_LIEGE", talkTroop.MapFaction.Leader.CharacterObject, null, false);
				if (talkTroop.MapFaction == this.NewKingdom && Hero.MainHero.MapFaction == talkTroop.MapFaction && Hero.MainHero != this.NewKingdom.Leader && talkTroop != this.NewKingdom.Leader)
				{
					score = ImportanceEnum.ReasonablyImportant;
					if (findString)
					{
						if (Hero.MainHero.Clan.IsUnderMercenaryService)
						{
							comment = "str_comment_changeherofaction_you_joined_us_as_mercenary";
							return;
						}
						this.NewKingdom.Leader.SetTextVariables();
						comment = "str_comment_changeherofaction_you_joined_us";
						return;
					}
				}
				else if (talkTroop.MapFaction == this.OldKingdom && Hero.MainHero.MapFaction != talkTroop.MapFaction && this._byRebellion)
				{
					score = ImportanceEnum.QuiteImportant;
					if (findString)
					{
						this.OldKingdom.Leader.SetTextVariables();
						if (this.OldKingdom.Leader == talkTroop)
						{
							comment = "str_comment_changeherofaction_you_rebelled_against_me";
							return;
						}
						comment = "str_comment_changeherofaction_you_rebelled_against_us";
						score = ImportanceEnum.VeryImportant;
						return;
					}
				}
				else if (talkTroop.MapFaction == this.OldKingdom && Hero.MainHero.MapFaction != talkTroop.MapFaction && talkTroop != this.OldKingdom.Leader)
				{
					score = ImportanceEnum.ReasonablyImportant;
					if (findString)
					{
						comment = "str_comment_changeherofaction_you_renounced_your_allegiance";
					}
				}
			}
		}

		public override string ToString()
		{
			return this.GetNotificationText().ToString();
		}

		[SaveableField(150)]
		public readonly Clan Clan;

		[SaveableField(151)]
		public readonly Kingdom OldKingdom;

		[SaveableField(152)]
		public readonly Kingdom NewKingdom;

		[SaveableField(153)]
		private readonly bool _byRebellion;
	}
}
