using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x020002F4 RID: 756
	public class SiegeAftermathLogEntry : LogEntry
	{
		// Token: 0x06002B85 RID: 11141 RVA: 0x000B71B7 File Offset: 0x000B53B7
		internal static void AutoGeneratedStaticCollectObjectsSiegeAftermathLogEntry(object o, List<object> collectedObjects)
		{
			((SiegeAftermathLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002B86 RID: 11142 RVA: 0x000B71C5 File Offset: 0x000B53C5
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._capturedSettlement);
			collectedObjects.Add(this._decisionMaker);
		}

		// Token: 0x06002B87 RID: 11143 RVA: 0x000B71E6 File Offset: 0x000B53E6
		internal static object AutoGeneratedGetMemberValue_siegeAftermath(object o)
		{
			return ((SiegeAftermathLogEntry)o)._siegeAftermath;
		}

		// Token: 0x06002B88 RID: 11144 RVA: 0x000B71F8 File Offset: 0x000B53F8
		internal static object AutoGeneratedGetMemberValue_capturedSettlement(object o)
		{
			return ((SiegeAftermathLogEntry)o)._capturedSettlement;
		}

		// Token: 0x06002B89 RID: 11145 RVA: 0x000B7205 File Offset: 0x000B5405
		internal static object AutoGeneratedGetMemberValue_decisionMaker(object o)
		{
			return ((SiegeAftermathLogEntry)o)._decisionMaker;
		}

		// Token: 0x06002B8A RID: 11146 RVA: 0x000B7212 File Offset: 0x000B5412
		internal static object AutoGeneratedGetMemberValue_playerWasInvolved(object o)
		{
			return ((SiegeAftermathLogEntry)o)._playerWasInvolved;
		}

		// Token: 0x06002B8B RID: 11147 RVA: 0x000B7224 File Offset: 0x000B5424
		public SiegeAftermathLogEntry(MobileParty leaderParty, IEnumerable<MobileParty> attackers, Settlement settlement, SiegeAftermathAction.SiegeAftermath siegeAftermath)
		{
			this._siegeAftermath = siegeAftermath;
			this._decisionMaker = leaderParty.LeaderHero;
			this._capturedSettlement = settlement;
			this._playerWasInvolved = false;
			using (IEnumerator<MobileParty> enumerator = attackers.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					if (enumerator.Current == MobileParty.MainParty)
					{
						this._playerWasInvolved = true;
						break;
					}
				}
			}
		}

		// Token: 0x06002B8C RID: 11148 RVA: 0x000B729C File Offset: 0x000B549C
		public override ImportanceEnum GetImportanceForClan(Clan clan)
		{
			return ImportanceEnum.Zero;
		}

		// Token: 0x06002B8D RID: 11149 RVA: 0x000B72A0 File Offset: 0x000B54A0
		public override void GetConversationScoreAndComment(Hero talkTroop, bool findString, out string comment, out ImportanceEnum score)
		{
			score = ImportanceEnum.Zero;
			comment = "";
			if (this._playerWasInvolved && Hero.MainHero.CurrentSettlement == this._capturedSettlement && Hero.OneToOneConversationHero.IsNotable)
			{
				score = ImportanceEnum.VeryImportant;
				if (this._siegeAftermath == SiegeAftermathAction.SiegeAftermath.ShowMercy)
				{
					comment = "str_comment_endplayerbattle_you_stormed_this_city_showed_mercy";
				}
				if (this._siegeAftermath == SiegeAftermathAction.SiegeAftermath.Devastate)
				{
					comment = "str_comment_endplayerbattle_you_stormed_this_city_devastated";
				}
				if (this._siegeAftermath == SiegeAftermathAction.SiegeAftermath.Pillage)
				{
					comment = "str_comment_endplayerbattle_you_stormed_this_city";
				}
			}
		}

		// Token: 0x06002B8E RID: 11150 RVA: 0x000B7311 File Offset: 0x000B5511
		public override string ToString()
		{
			return this.GetNotificationText().ToString();
		}

		// Token: 0x06002B8F RID: 11151 RVA: 0x000B7320 File Offset: 0x000B5520
		public TextObject GetNotificationText()
		{
			TextObject textObject = null;
			if (this._siegeAftermath == SiegeAftermathAction.SiegeAftermath.ShowMercy)
			{
				textObject = new TextObject("{=wTh00qoj}{HERO.NAME} has showed mercy to {SETTLEMENT}.", null);
			}
			if (this._siegeAftermath == SiegeAftermathAction.SiegeAftermath.Devastate)
			{
				textObject = new TextObject("{=NeTp63aU}{HERO.NAME} has devastated {SETTLEMENT}.", null);
			}
			if (this._siegeAftermath == SiegeAftermathAction.SiegeAftermath.Pillage)
			{
				textObject = new TextObject("{=VzAqZucZ}{HERO.NAME} has pillaged {SETTLEMENT}.", null);
			}
			if (this._decisionMaker != null)
			{
				textObject.SetCharacterProperties("HERO", this._decisionMaker.CharacterObject, false);
			}
			textObject.SetTextVariable("SETTLEMENT", this._capturedSettlement.Name);
			return textObject;
		}

		// Token: 0x04000D21 RID: 3361
		[SaveableField(10)]
		private readonly SiegeAftermathAction.SiegeAftermath _siegeAftermath;

		// Token: 0x04000D22 RID: 3362
		[SaveableField(20)]
		private readonly Settlement _capturedSettlement;

		// Token: 0x04000D23 RID: 3363
		[SaveableField(30)]
		private readonly Hero _decisionMaker;

		// Token: 0x04000D24 RID: 3364
		[SaveableField(40)]
		private readonly bool _playerWasInvolved;
	}
}
