using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.LogEntries
{
	// Token: 0x020002E8 RID: 744
	public class TakePrisonerLogEntry : LogEntry, IEncyclopediaLog, IChatNotification, IWarLog
	{
		// Token: 0x06002B01 RID: 11009 RVA: 0x000B5D68 File Offset: 0x000B3F68
		internal static void AutoGeneratedStaticCollectObjectsTakePrisonerLogEntry(object o, List<object> collectedObjects)
		{
			((TakePrisonerLogEntry)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002B02 RID: 11010 RVA: 0x000B5D78 File Offset: 0x000B3F78
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.CapturerPartyMapFaction);
			collectedObjects.Add(this.Prisoner);
			collectedObjects.Add(this.CapturerSettlement);
			collectedObjects.Add(this.CapturerMobilePartyLeader);
			collectedObjects.Add(this.CapturerHero);
		}

		// Token: 0x06002B03 RID: 11011 RVA: 0x000B5DC8 File Offset: 0x000B3FC8
		internal static object AutoGeneratedGetMemberValueCapturerPartyMapFaction(object o)
		{
			return ((TakePrisonerLogEntry)o).CapturerPartyMapFaction;
		}

		// Token: 0x06002B04 RID: 11012 RVA: 0x000B5DD5 File Offset: 0x000B3FD5
		internal static object AutoGeneratedGetMemberValuePrisoner(object o)
		{
			return ((TakePrisonerLogEntry)o).Prisoner;
		}

		// Token: 0x06002B05 RID: 11013 RVA: 0x000B5DE2 File Offset: 0x000B3FE2
		internal static object AutoGeneratedGetMemberValueCapturerSettlement(object o)
		{
			return ((TakePrisonerLogEntry)o).CapturerSettlement;
		}

		// Token: 0x06002B06 RID: 11014 RVA: 0x000B5DEF File Offset: 0x000B3FEF
		internal static object AutoGeneratedGetMemberValueCapturerMobilePartyLeader(object o)
		{
			return ((TakePrisonerLogEntry)o).CapturerMobilePartyLeader;
		}

		// Token: 0x06002B07 RID: 11015 RVA: 0x000B5DFC File Offset: 0x000B3FFC
		internal static object AutoGeneratedGetMemberValueCapturerHero(object o)
		{
			return ((TakePrisonerLogEntry)o).CapturerHero;
		}

		// Token: 0x17000A7B RID: 2683
		// (get) Token: 0x06002B08 RID: 11016 RVA: 0x000B5E09 File Offset: 0x000B4009
		public override CampaignTime KeepInHistoryTime
		{
			get
			{
				return CampaignTime.Weeks(24f);
			}
		}

		// Token: 0x17000A7C RID: 2684
		// (get) Token: 0x06002B09 RID: 11017 RVA: 0x000B5E15 File Offset: 0x000B4015
		public bool IsVisibleNotification
		{
			get
			{
				return true;
			}
		}

		// Token: 0x17000A7D RID: 2685
		// (get) Token: 0x06002B0A RID: 11018 RVA: 0x000B5E18 File Offset: 0x000B4018
		public override ChatNotificationType NotificationType
		{
			get
			{
				Hero capturerHero = this.CapturerHero;
				IFaction faction = ((capturerHero != null) ? capturerHero.Clan : null);
				return base.MilitaryNotification(faction ?? this.CapturerPartyMapFaction, this.Prisoner.Clan);
			}
		}

		// Token: 0x06002B0B RID: 11019 RVA: 0x000B5E54 File Offset: 0x000B4054
		public TakePrisonerLogEntry(PartyBase capturerParty, Hero prisoner)
		{
			this.CapturerPartyMapFaction = capturerParty.MapFaction;
			this.CapturerHero = capturerParty.LeaderHero;
			MobileParty mobileParty = capturerParty.MobileParty;
			this.CapturerMobilePartyLeader = ((mobileParty != null) ? mobileParty.LeaderHero : null);
			this.CapturerSettlement = capturerParty.Settlement;
			this.Prisoner = prisoner;
		}

		// Token: 0x06002B0C RID: 11020 RVA: 0x000B5EAC File Offset: 0x000B40AC
		public bool IsRelatedToWar(StanceLink stance, out IFaction effector, out IFaction effected)
		{
			IFaction faction = stance.Faction1;
			IFaction faction2 = stance.Faction2;
			effector = this.CapturerPartyMapFaction.MapFaction;
			effected = this.Prisoner.MapFaction;
			return (this.CapturerPartyMapFaction == faction && this.Prisoner.MapFaction == faction2) || (this.CapturerPartyMapFaction == faction2 && this.Prisoner.MapFaction == faction);
		}

		// Token: 0x06002B0D RID: 11021 RVA: 0x000B5F13 File Offset: 0x000B4113
		public override string ToString()
		{
			return this.GetNotificationText().ToString();
		}

		// Token: 0x06002B0E RID: 11022 RVA: 0x000B5F20 File Offset: 0x000B4120
		public TextObject GetNotificationText()
		{
			TextObject textObject = new TextObject("{=QRJQ9Wgv}{PRISONER_LORD.LINK}{?PRISONER_LORD_HAS_FACTION_LINK} of the {PRISONER_LORD_FACTION_LINK}{?}{\\?} has been taken prisoner by the {CAPTOR_FACTION}.", null);
			if (this.CapturerHero != null)
			{
				textObject = new TextObject("{=Ebb7aH3T}{PRISONER_LORD.LINK}{?PRISONER_LORD_HAS_FACTION_LINK} of the {PRISONER_LORD_FACTION_LINK}{?}{\\?} has been taken prisoner by {CAPTURER_LORD.LINK}{?CAPTURER_LORD_HAS_FACTION_LINK} of the {CAPTURER_LORD_FACTION_LINK}{?}{\\?}.", null);
				StringHelpers.SetCharacterProperties("CAPTURER_LORD", this.CapturerHero.CharacterObject, textObject, false);
				Clan clan = this.CapturerHero.Clan;
				if (clan != null && !clan.IsMinorFaction && this.CapturerHero.MapFaction != CampaignData.NeutralFaction)
				{
					textObject.SetTextVariable("CAPTURER_LORD_FACTION_LINK", this.CapturerHero.MapFaction.EncyclopediaLinkWithName);
					textObject.SetTextVariable("CAPTURER_LORD_HAS_FACTION_LINK", 1);
				}
			}
			textObject.SetTextVariable("CAPTOR_FACTION", this.CapturerPartyMapFaction.InformalName);
			StringHelpers.SetCharacterProperties("PRISONER_LORD", this.Prisoner.CharacterObject, textObject, false);
			Clan clan2 = this.Prisoner.Clan;
			if (clan2 != null && !clan2.IsMinorFaction && this.Prisoner.MapFaction != CampaignData.NeutralFaction)
			{
				textObject.SetTextVariable("PRISONER_LORD_FACTION_LINK", this.Prisoner.MapFaction.EncyclopediaLinkWithName);
				textObject.SetTextVariable("PRISONER_LORD_HAS_FACTION_LINK", 1);
			}
			return textObject;
		}

		// Token: 0x06002B0F RID: 11023 RVA: 0x000B6043 File Offset: 0x000B4243
		public bool IsVisibleInEncyclopediaPageOf<T>(T obj) where T : MBObjectBase
		{
			return obj == this.Prisoner || (this.CapturerSettlement != null && obj == this.CapturerSettlement) || (this.CapturerMobilePartyLeader != null && obj == this.CapturerMobilePartyLeader);
		}

		// Token: 0x06002B10 RID: 11024 RVA: 0x000B6083 File Offset: 0x000B4283
		public TextObject GetEncyclopediaText()
		{
			return this.GetNotificationText();
		}

		// Token: 0x04000CFA RID: 3322
		[SaveableField(330)]
		public readonly IFaction CapturerPartyMapFaction;

		// Token: 0x04000CFB RID: 3323
		[SaveableField(331)]
		public readonly Hero Prisoner;

		// Token: 0x04000CFC RID: 3324
		[SaveableField(332)]
		public readonly Settlement CapturerSettlement;

		// Token: 0x04000CFD RID: 3325
		[SaveableField(333)]
		public readonly Hero CapturerMobilePartyLeader;

		// Token: 0x04000CFE RID: 3326
		[SaveableField(334)]
		public readonly Hero CapturerHero;
	}
}
