using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x0200002D RID: 45
	internal class CampaignBehaviorDataStore
	{
		// Token: 0x060002C9 RID: 713 RVA: 0x00012221 File Offset: 0x00010421
		internal CampaignBehaviorDataStore()
		{
			this._behaviorDict = new Dictionary<string, CampaignBehaviorDataStore.BehaviorSaveData>();
		}

		// Token: 0x060002CA RID: 714 RVA: 0x00012234 File Offset: 0x00010434
		internal void SaveBehaviorData(CampaignBehaviorBase campaignBehavior)
		{
			string stringId = campaignBehavior.StringId;
			CampaignBehaviorDataStore.BehaviorSaveData behaviorSaveData = new CampaignBehaviorDataStore.BehaviorSaveData(true);
			campaignBehavior.SyncData(behaviorSaveData);
			if (this._behaviorDict.ContainsKey(stringId))
			{
				Debug.FailedAssert("trying to save multiple behaviors with the same stringid: " + stringId, "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\CampaignBehaviorDataStore.cs", "SaveBehaviorData", 75);
				this._behaviorDict[stringId] = behaviorSaveData;
				return;
			}
			this._behaviorDict.Add(stringId, behaviorSaveData);
		}

		// Token: 0x060002CB RID: 715 RVA: 0x0001229B File Offset: 0x0001049B
		internal void ClearBehaviorData()
		{
			this._behaviorDict.Clear();
		}

		// Token: 0x060002CC RID: 716 RVA: 0x000122A8 File Offset: 0x000104A8
		internal void LoadBehaviorData(CampaignBehaviorBase campaignBehavior)
		{
			string stringId = campaignBehavior.StringId;
			CampaignBehaviorDataStore.BehaviorSaveData behaviorSaveData;
			if (this._behaviorDict.TryGetValue(stringId, out behaviorSaveData))
			{
				campaignBehavior.SyncData(behaviorSaveData);
				return;
			}
			List<KeyValuePair<string, CampaignBehaviorDataStore.BehaviorSaveData>> list = this._behaviorDict.ToList<KeyValuePair<string, CampaignBehaviorDataStore.BehaviorSaveData>>();
			string name = campaignBehavior.GetType().Name;
			foreach (KeyValuePair<string, CampaignBehaviorDataStore.BehaviorSaveData> keyValuePair in list)
			{
				if (keyValuePair.Key.Contains(name))
				{
					this._behaviorDict.Remove(keyValuePair.Key);
					this._behaviorDict.Add(stringId, keyValuePair.Value);
					campaignBehavior.SyncData(keyValuePair.Value);
					break;
				}
			}
		}

		// Token: 0x060002CD RID: 717 RVA: 0x0001236C File Offset: 0x0001056C
		internal static void AutoGeneratedStaticCollectObjectsCampaignBehaviorDataStore(object o, List<object> collectedObjects)
		{
			((CampaignBehaviorDataStore)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060002CE RID: 718 RVA: 0x0001237A File Offset: 0x0001057A
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._behaviorDict);
		}

		// Token: 0x060002CF RID: 719 RVA: 0x00012388 File Offset: 0x00010588
		internal static object AutoGeneratedGetMemberValue_behaviorDict(object o)
		{
			return ((CampaignBehaviorDataStore)o)._behaviorDict;
		}

		// Token: 0x040000E0 RID: 224
		[SaveableField(1)]
		private readonly Dictionary<string, CampaignBehaviorDataStore.BehaviorSaveData> _behaviorDict;

		// Token: 0x0200047F RID: 1151
		internal class BehaviorSaveData : IDataStore
		{
			// Token: 0x06003FE2 RID: 16354 RVA: 0x00130B70 File Offset: 0x0012ED70
			public BehaviorSaveData(bool isSaving)
			{
				this._isSaving = isSaving;
			}

			// Token: 0x06003FE3 RID: 16355 RVA: 0x00130B8C File Offset: 0x0012ED8C
			public bool SyncData<T>(string key, ref T data)
			{
				if (this.IsSaving)
				{
					this._records.Add(key, data);
					return true;
				}
				object obj;
				if (this._records.TryGetValue(key, out obj))
				{
					data = (T)((object)obj);
					return true;
				}
				return false;
			}

			// Token: 0x17000D53 RID: 3411
			// (get) Token: 0x06003FE4 RID: 16356 RVA: 0x00130BD9 File Offset: 0x0012EDD9
			public bool IsSaving
			{
				get
				{
					return this._isSaving;
				}
			}

			// Token: 0x17000D54 RID: 3412
			// (get) Token: 0x06003FE5 RID: 16357 RVA: 0x00130BE1 File Offset: 0x0012EDE1
			public bool IsLoading
			{
				get
				{
					return !this._isSaving;
				}
			}

			// Token: 0x06003FE6 RID: 16358 RVA: 0x00130BEC File Offset: 0x0012EDEC
			internal static void AutoGeneratedStaticCollectObjectsBehaviorSaveData(object o, List<object> collectedObjects)
			{
				((CampaignBehaviorDataStore.BehaviorSaveData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06003FE7 RID: 16359 RVA: 0x00130BFA File Offset: 0x0012EDFA
			protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				collectedObjects.Add(this._records);
			}

			// Token: 0x06003FE8 RID: 16360 RVA: 0x00130C08 File Offset: 0x0012EE08
			internal static object AutoGeneratedGetMemberValue_records(object o)
			{
				return ((CampaignBehaviorDataStore.BehaviorSaveData)o)._records;
			}

			// Token: 0x0400138C RID: 5004
			[SaveableField(0)]
			private Dictionary<string, object> _records = new Dictionary<string, object>();

			// Token: 0x0400138D RID: 5005
			private readonly bool _isSaving;
		}
	}
}
