using System;
using System.Collections;
using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem.Definition;

namespace TaleWorlds.Core
{
	// Token: 0x02000024 RID: 36
	internal class AutoGeneratedSaveManager : IAutoGeneratedSaveManager
	{
		// Token: 0x060001B8 RID: 440 RVA: 0x0000758C File Offset: 0x0000578C
		public void Initialize(DefinitionContext definitionContext)
		{
			TypeDefinition typeDefinition = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10002));
			CollectObjectsDelegate collectObjectsDelegate = new CollectObjectsDelegate(ArmorComponent.AutoGeneratedStaticCollectObjectsArmorComponent);
			typeDefinition.InitializeForAutoGeneration(collectObjectsDelegate);
			TypeDefinition typeDefinition2 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10003));
			CollectObjectsDelegate collectObjectsDelegate2 = new CollectObjectsDelegate(Banner.AutoGeneratedStaticCollectObjectsBanner);
			typeDefinition2.InitializeForAutoGeneration(collectObjectsDelegate2);
			typeDefinition2.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(new GetFieldValueDelegate(Banner.AutoGeneratedGetMemberValue_bannerDataList));
			TypeDefinition typeDefinition3 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10004));
			CollectObjectsDelegate collectObjectsDelegate3 = new CollectObjectsDelegate(BannerData.AutoGeneratedStaticCollectObjectsBannerData);
			typeDefinition3.InitializeForAutoGeneration(collectObjectsDelegate3);
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 3)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_colorId2));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 4)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_size));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 5)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_position));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 6)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_drawStroke));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 7)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_mirror));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 8)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_rotationValue));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_meshId));
			typeDefinition3.GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(new GetFieldValueDelegate(BannerData.AutoGeneratedGetMemberValue_colorId));
			TypeDefinition typeDefinition4 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10005));
			CollectObjectsDelegate collectObjectsDelegate4 = new CollectObjectsDelegate(BasicCharacterObject.AutoGeneratedStaticCollectObjectsBasicCharacterObject);
			typeDefinition4.InitializeForAutoGeneration(collectObjectsDelegate4);
			TypeDefinition typeDefinition5 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10006));
			CollectObjectsDelegate collectObjectsDelegate5 = new CollectObjectsDelegate(CharacterAttribute.AutoGeneratedStaticCollectObjectsCharacterAttribute);
			typeDefinition5.InitializeForAutoGeneration(collectObjectsDelegate5);
			TypeDefinition typeDefinition6 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10008));
			CollectObjectsDelegate collectObjectsDelegate6 = new CollectObjectsDelegate(CharacterSkills.AutoGeneratedStaticCollectObjectsCharacterSkills);
			typeDefinition6.InitializeForAutoGeneration(collectObjectsDelegate6);
			TypeDefinition typeDefinition7 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10009));
			CollectObjectsDelegate collectObjectsDelegate7 = new CollectObjectsDelegate(WeaponDesign.AutoGeneratedStaticCollectObjectsWeaponDesign);
			typeDefinition7.InitializeForAutoGeneration(collectObjectsDelegate7);
			typeDefinition7.GetPropertyDefinitionWithId(new MemberTypeId(2, 21)).InitializeForAutoGeneration(new GetPropertyValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueWeaponName));
			typeDefinition7.GetPropertyDefinitionWithId(new MemberTypeId(2, 50)).InitializeForAutoGeneration(new GetPropertyValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueHandToBottomLength));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 10)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueWeaponFlags));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 60)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueCraftedWeaponLength));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 70)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueTemplate));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 80)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueTopPivotOffsets));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 90)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueBottomPivotOffsets));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 100)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValueHolsterShiftAmount));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 30)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValue_usedPieces));
			typeDefinition7.GetFieldDefinitionWithId(new MemberTypeId(2, 40)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesign.AutoGeneratedGetMemberValue_piecePivotDistances));
			TypeDefinition typeDefinition8 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10010));
			CollectObjectsDelegate collectObjectsDelegate8 = new CollectObjectsDelegate(CraftingPiece.AutoGeneratedStaticCollectObjectsCraftingPiece);
			typeDefinition8.InitializeForAutoGeneration(collectObjectsDelegate8);
			TypeDefinition typeDefinition9 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10011));
			CollectObjectsDelegate collectObjectsDelegate9 = new CollectObjectsDelegate(CraftingTemplate.AutoGeneratedStaticCollectObjectsCraftingTemplate);
			typeDefinition9.InitializeForAutoGeneration(collectObjectsDelegate9);
			TypeDefinition typeDefinition10 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10015));
			TypeDefinition typeDefinition11 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10016));
			CollectObjectsDelegate collectObjectsDelegate10 = new CollectObjectsDelegate(Equipment.AutoGeneratedStaticCollectObjectsEquipment);
			typeDefinition11.InitializeForAutoGeneration(collectObjectsDelegate10);
			typeDefinition11.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(new GetFieldValueDelegate(Equipment.AutoGeneratedGetMemberValue_equipmentType));
			typeDefinition11.GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(new GetFieldValueDelegate(Equipment.AutoGeneratedGetMemberValue_itemSlots));
			TypeDefinition typeDefinition12 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10018));
			CollectObjectsDelegate collectObjectsDelegate11 = new CollectObjectsDelegate(TradeItemComponent.AutoGeneratedStaticCollectObjectsTradeItemComponent);
			typeDefinition12.InitializeForAutoGeneration(collectObjectsDelegate11);
			TypeDefinition typeDefinition13 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10026));
			TypeDefinition typeDefinition14 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10027));
			CollectObjectsDelegate collectObjectsDelegate12 = new CollectObjectsDelegate(HorseComponent.AutoGeneratedStaticCollectObjectsHorseComponent);
			typeDefinition14.InitializeForAutoGeneration(collectObjectsDelegate12);
			TypeDefinition typeDefinition15 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10028));
			CollectObjectsDelegate collectObjectsDelegate13 = new CollectObjectsDelegate(ItemCategory.AutoGeneratedStaticCollectObjectsItemCategory);
			typeDefinition15.InitializeForAutoGeneration(collectObjectsDelegate13);
			TypeDefinition typeDefinition16 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10029));
			TypeDefinition typeDefinition17 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10030));
			CollectObjectsDelegate collectObjectsDelegate14 = new CollectObjectsDelegate(ItemModifier.AutoGeneratedStaticCollectObjectsItemModifier);
			typeDefinition17.InitializeForAutoGeneration(collectObjectsDelegate14);
			TypeDefinition typeDefinition18 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10031));
			CollectObjectsDelegate collectObjectsDelegate15 = new CollectObjectsDelegate(ItemModifierGroup.AutoGeneratedStaticCollectObjectsItemModifierGroup);
			typeDefinition18.InitializeForAutoGeneration(collectObjectsDelegate15);
			TypeDefinition typeDefinition19 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10032));
			CollectObjectsDelegate collectObjectsDelegate16 = new CollectObjectsDelegate(ItemObject.AutoGeneratedStaticCollectObjectsItemObject);
			typeDefinition19.InitializeForAutoGeneration(collectObjectsDelegate16);
			TypeDefinition typeDefinition20 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10036));
			CollectObjectsDelegate collectObjectsDelegate17 = new CollectObjectsDelegate(MissionResult.AutoGeneratedStaticCollectObjectsMissionResult);
			typeDefinition20.InitializeForAutoGeneration(collectObjectsDelegate17);
			TypeDefinition typeDefinition21 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10038));
			CollectObjectsDelegate collectObjectsDelegate18 = new CollectObjectsDelegate(PropertyObject.AutoGeneratedStaticCollectObjectsPropertyObject);
			typeDefinition21.InitializeForAutoGeneration(collectObjectsDelegate18);
			TypeDefinition typeDefinition22 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10039));
			CollectObjectsDelegate collectObjectsDelegate19 = new CollectObjectsDelegate(SkillObject.AutoGeneratedStaticCollectObjectsSkillObject);
			typeDefinition22.InitializeForAutoGeneration(collectObjectsDelegate19);
			TypeDefinition typeDefinition23 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10040));
			TypeDefinition typeDefinition24 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10041));
			TypeDefinition typeDefinition25 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10042));
			CollectObjectsDelegate collectObjectsDelegate20 = new CollectObjectsDelegate(SiegeEngineType.AutoGeneratedStaticCollectObjectsSiegeEngineType);
			typeDefinition25.InitializeForAutoGeneration(collectObjectsDelegate20);
			TypeDefinition typeDefinition26 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10044));
			CollectObjectsDelegate collectObjectsDelegate21 = new CollectObjectsDelegate(WeaponDesignElement.AutoGeneratedStaticCollectObjectsWeaponDesignElement);
			typeDefinition26.InitializeForAutoGeneration(collectObjectsDelegate21);
			typeDefinition26.GetFieldDefinitionWithId(new MemberTypeId(2, 20)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesignElement.AutoGeneratedGetMemberValueScalePercentage));
			typeDefinition26.GetFieldDefinitionWithId(new MemberTypeId(2, 10)).InitializeForAutoGeneration(new GetFieldValueDelegate(WeaponDesignElement.AutoGeneratedGetMemberValue_craftingPiece));
			TypeDefinition typeDefinition27 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10045));
			CollectObjectsDelegate collectObjectsDelegate22 = new CollectObjectsDelegate(WeaponComponent.AutoGeneratedStaticCollectObjectsWeaponComponent);
			typeDefinition27.InitializeForAutoGeneration(collectObjectsDelegate22);
			TypeDefinition typeDefinition28 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10046));
			CollectObjectsDelegate collectObjectsDelegate23 = new CollectObjectsDelegate(WeaponComponentData.AutoGeneratedStaticCollectObjectsWeaponComponentData);
			typeDefinition28.InitializeForAutoGeneration(collectObjectsDelegate23);
			((TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10050))).GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(new GetFieldValueDelegate(InformationData.AutoGeneratedGetMemberValueDescriptionText));
			TypeDefinition typeDefinition29 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10051));
			CollectObjectsDelegate collectObjectsDelegate24 = new CollectObjectsDelegate(Crafting.OverrideData.AutoGeneratedStaticCollectObjectsOverrideData);
			typeDefinition29.InitializeForAutoGeneration(collectObjectsDelegate24);
			typeDefinition29.GetFieldDefinitionWithId(new MemberTypeId(2, 10)).InitializeForAutoGeneration(new GetFieldValueDelegate(Crafting.OverrideData.AutoGeneratedGetMemberValueWeightOverriden));
			typeDefinition29.GetFieldDefinitionWithId(new MemberTypeId(2, 20)).InitializeForAutoGeneration(new GetFieldValueDelegate(Crafting.OverrideData.AutoGeneratedGetMemberValueSwingSpeedOverriden));
			typeDefinition29.GetFieldDefinitionWithId(new MemberTypeId(2, 30)).InitializeForAutoGeneration(new GetFieldValueDelegate(Crafting.OverrideData.AutoGeneratedGetMemberValueThrustSpeedOverriden));
			typeDefinition29.GetFieldDefinitionWithId(new MemberTypeId(2, 40)).InitializeForAutoGeneration(new GetFieldValueDelegate(Crafting.OverrideData.AutoGeneratedGetMemberValueSwingDamageOverriden));
			typeDefinition29.GetFieldDefinitionWithId(new MemberTypeId(2, 50)).InitializeForAutoGeneration(new GetFieldValueDelegate(Crafting.OverrideData.AutoGeneratedGetMemberValueThrustDamageOverriden));
			typeDefinition29.GetFieldDefinitionWithId(new MemberTypeId(2, 60)).InitializeForAutoGeneration(new GetFieldValueDelegate(Crafting.OverrideData.AutoGeneratedGetMemberValueHandling));
			TypeDefinition typeDefinition30 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10052));
			CollectObjectsDelegate collectObjectsDelegate25 = new CollectObjectsDelegate(MBFastRandom.AutoGeneratedStaticCollectObjectsMBFastRandom);
			typeDefinition30.InitializeForAutoGeneration(collectObjectsDelegate25);
			typeDefinition30.GetFieldDefinitionWithId(new MemberTypeId(2, 1)).InitializeForAutoGeneration(new GetFieldValueDelegate(MBFastRandom.AutoGeneratedGetMemberValue_x));
			typeDefinition30.GetFieldDefinitionWithId(new MemberTypeId(2, 2)).InitializeForAutoGeneration(new GetFieldValueDelegate(MBFastRandom.AutoGeneratedGetMemberValue_y));
			typeDefinition30.GetFieldDefinitionWithId(new MemberTypeId(2, 3)).InitializeForAutoGeneration(new GetFieldValueDelegate(MBFastRandom.AutoGeneratedGetMemberValue_z));
			typeDefinition30.GetFieldDefinitionWithId(new MemberTypeId(2, 4)).InitializeForAutoGeneration(new GetFieldValueDelegate(MBFastRandom.AutoGeneratedGetMemberValue_w));
			TypeDefinition typeDefinition31 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(10053));
			CollectObjectsDelegate collectObjectsDelegate26 = new CollectObjectsDelegate(BannerComponent.AutoGeneratedStaticCollectObjectsBannerComponent);
			typeDefinition31.InitializeForAutoGeneration(collectObjectsDelegate26);
			TypeDefinition typeDefinition32 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11004));
			CollectObjectsDelegate collectObjectsDelegate27 = new CollectObjectsDelegate(ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement);
			typeDefinition32.InitializeForAutoGeneration(collectObjectsDelegate27);
			typeDefinition32.GetPropertyDefinitionWithId(new MemberTypeId(1, 21)).InitializeForAutoGeneration(new GetPropertyValueDelegate(ItemRosterElement.AutoGeneratedGetMemberValueEquipmentElement));
			typeDefinition32.GetFieldDefinitionWithId(new MemberTypeId(1, 11)).InitializeForAutoGeneration(new GetFieldValueDelegate(ItemRosterElement.AutoGeneratedGetMemberValue_amount));
			TypeDefinition typeDefinition33 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11006));
			CollectObjectsDelegate collectObjectsDelegate28 = new CollectObjectsDelegate(UniqueTroopDescriptor.AutoGeneratedStaticCollectObjectsUniqueTroopDescriptor);
			typeDefinition33.InitializeForAutoGeneration(collectObjectsDelegate28);
			typeDefinition33.GetPropertyDefinitionWithId(new MemberTypeId(1, 1)).InitializeForAutoGeneration(new GetPropertyValueDelegate(UniqueTroopDescriptor.AutoGeneratedGetMemberValueUniqueSeed));
			TypeDefinition typeDefinition34 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11009));
			CollectObjectsDelegate collectObjectsDelegate29 = new CollectObjectsDelegate(StaticBodyProperties.AutoGeneratedStaticCollectObjectsStaticBodyProperties);
			typeDefinition34.InitializeForAutoGeneration(collectObjectsDelegate29);
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 1)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart1));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 2)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart2));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 3)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart3));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 4)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart4));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 5)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart5));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 6)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart6));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 7)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart7));
			typeDefinition34.GetPropertyDefinitionWithId(new MemberTypeId(1, 8)).InitializeForAutoGeneration(new GetPropertyValueDelegate(StaticBodyProperties.AutoGeneratedGetMemberValueKeyPart8));
			TypeDefinition typeDefinition35 = (TypeDefinition)definitionContext.TryGetTypeDefinition(new TypeSaveId(11011));
			CollectObjectsDelegate collectObjectsDelegate30 = new CollectObjectsDelegate(EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement);
			typeDefinition35.InitializeForAutoGeneration(collectObjectsDelegate30);
			typeDefinition35.GetPropertyDefinitionWithId(new MemberTypeId(1, 1)).InitializeForAutoGeneration(new GetPropertyValueDelegate(EquipmentElement.AutoGeneratedGetMemberValueItem));
			typeDefinition35.GetPropertyDefinitionWithId(new MemberTypeId(1, 2)).InitializeForAutoGeneration(new GetPropertyValueDelegate(EquipmentElement.AutoGeneratedGetMemberValueItemModifier));
			typeDefinition35.GetPropertyDefinitionWithId(new MemberTypeId(1, 3)).InitializeForAutoGeneration(new GetPropertyValueDelegate(EquipmentElement.AutoGeneratedGetMemberValueIsQuestItem));
			SaveId saveId = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 11004 "));
			ContainerDefinition containerDefinition = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId);
			CollectObjectsDelegate collectObjectsDelegate31 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForArray0);
			containerDefinition.InitializeForAutoGeneration(collectObjectsDelegate31, false);
			SaveId saveId2 = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 11011 "));
			ContainerDefinition containerDefinition2 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId2);
			CollectObjectsDelegate collectObjectsDelegate32 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForArray1);
			containerDefinition2.InitializeForAutoGeneration(collectObjectsDelegate32, false);
			SaveId saveId3 = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 10016 "));
			ContainerDefinition containerDefinition3 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId3);
			CollectObjectsDelegate collectObjectsDelegate33 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForArray2);
			containerDefinition3.InitializeForAutoGeneration(collectObjectsDelegate33, false);
			SaveId saveId4 = SaveId.ReadSaveIdFrom(new StringReader("2 3 0 10044 "));
			ContainerDefinition containerDefinition4 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId4);
			CollectObjectsDelegate collectObjectsDelegate34 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForArray3);
			containerDefinition4.InitializeForAutoGeneration(collectObjectsDelegate34, false);
			SaveId saveId5 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10032 "));
			ContainerDefinition containerDefinition5 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId5);
			CollectObjectsDelegate collectObjectsDelegate35 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList4);
			containerDefinition5.InitializeForAutoGeneration(collectObjectsDelegate35, false);
			SaveId saveId6 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10032 "));
			ContainerDefinition containerDefinition6 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId6);
			CollectObjectsDelegate collectObjectsDelegate36 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList5);
			containerDefinition6.InitializeForAutoGeneration(collectObjectsDelegate36, false);
			SaveId saveId7 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10032 "));
			ContainerDefinition containerDefinition7 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId7);
			CollectObjectsDelegate collectObjectsDelegate37 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList6);
			containerDefinition7.InitializeForAutoGeneration(collectObjectsDelegate37, false);
			SaveId saveId8 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10029 "));
			ContainerDefinition containerDefinition8 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId8);
			CollectObjectsDelegate collectObjectsDelegate38 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList7);
			containerDefinition8.InitializeForAutoGeneration(collectObjectsDelegate38, false);
			SaveId saveId9 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10029 "));
			ContainerDefinition containerDefinition9 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId9);
			CollectObjectsDelegate collectObjectsDelegate39 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList8);
			containerDefinition9.InitializeForAutoGeneration(collectObjectsDelegate39, false);
			SaveId saveId10 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10029 "));
			ContainerDefinition containerDefinition10 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId10);
			CollectObjectsDelegate collectObjectsDelegate40 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList9);
			containerDefinition10.InitializeForAutoGeneration(collectObjectsDelegate40, false);
			SaveId saveId11 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10030 "));
			ContainerDefinition containerDefinition11 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId11);
			CollectObjectsDelegate collectObjectsDelegate41 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList10);
			containerDefinition11.InitializeForAutoGeneration(collectObjectsDelegate41, false);
			SaveId saveId12 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10030 "));
			ContainerDefinition containerDefinition12 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId12);
			CollectObjectsDelegate collectObjectsDelegate42 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList11);
			containerDefinition12.InitializeForAutoGeneration(collectObjectsDelegate42, false);
			SaveId saveId13 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10030 "));
			ContainerDefinition containerDefinition13 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId13);
			CollectObjectsDelegate collectObjectsDelegate43 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList12);
			containerDefinition13.InitializeForAutoGeneration(collectObjectsDelegate43, false);
			SaveId saveId14 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10031 "));
			ContainerDefinition containerDefinition14 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId14);
			CollectObjectsDelegate collectObjectsDelegate44 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList13);
			containerDefinition14.InitializeForAutoGeneration(collectObjectsDelegate44, false);
			SaveId saveId15 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10031 "));
			ContainerDefinition containerDefinition15 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId15);
			CollectObjectsDelegate collectObjectsDelegate45 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList14);
			containerDefinition15.InitializeForAutoGeneration(collectObjectsDelegate45, false);
			SaveId saveId16 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10031 "));
			ContainerDefinition containerDefinition16 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId16);
			CollectObjectsDelegate collectObjectsDelegate46 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList15);
			containerDefinition16.InitializeForAutoGeneration(collectObjectsDelegate46, false);
			SaveId saveId17 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10006 "));
			ContainerDefinition containerDefinition17 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId17);
			CollectObjectsDelegate collectObjectsDelegate47 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList16);
			containerDefinition17.InitializeForAutoGeneration(collectObjectsDelegate47, false);
			SaveId saveId18 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10006 "));
			ContainerDefinition containerDefinition18 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId18);
			CollectObjectsDelegate collectObjectsDelegate48 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList17);
			containerDefinition18.InitializeForAutoGeneration(collectObjectsDelegate48, false);
			SaveId saveId19 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10006 "));
			ContainerDefinition containerDefinition19 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId19);
			CollectObjectsDelegate collectObjectsDelegate49 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList18);
			containerDefinition19.InitializeForAutoGeneration(collectObjectsDelegate49, false);
			SaveId saveId20 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10039 "));
			ContainerDefinition containerDefinition20 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId20);
			CollectObjectsDelegate collectObjectsDelegate50 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList19);
			containerDefinition20.InitializeForAutoGeneration(collectObjectsDelegate50, false);
			SaveId saveId21 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10039 "));
			ContainerDefinition containerDefinition21 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId21);
			CollectObjectsDelegate collectObjectsDelegate51 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList20);
			containerDefinition21.InitializeForAutoGeneration(collectObjectsDelegate51, false);
			SaveId saveId22 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10039 "));
			ContainerDefinition containerDefinition22 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId22);
			CollectObjectsDelegate collectObjectsDelegate52 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList21);
			containerDefinition22.InitializeForAutoGeneration(collectObjectsDelegate52, false);
			SaveId saveId23 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10028 "));
			ContainerDefinition containerDefinition23 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId23);
			CollectObjectsDelegate collectObjectsDelegate53 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList22);
			containerDefinition23.InitializeForAutoGeneration(collectObjectsDelegate53, false);
			SaveId saveId24 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10028 "));
			ContainerDefinition containerDefinition24 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId24);
			CollectObjectsDelegate collectObjectsDelegate54 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList23);
			containerDefinition24.InitializeForAutoGeneration(collectObjectsDelegate54, false);
			SaveId saveId25 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10028 "));
			ContainerDefinition containerDefinition25 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId25);
			CollectObjectsDelegate collectObjectsDelegate55 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList24);
			containerDefinition25.InitializeForAutoGeneration(collectObjectsDelegate55, false);
			SaveId saveId26 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10010 "));
			ContainerDefinition containerDefinition26 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId26);
			CollectObjectsDelegate collectObjectsDelegate56 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList25);
			containerDefinition26.InitializeForAutoGeneration(collectObjectsDelegate56, false);
			SaveId saveId27 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10010 "));
			ContainerDefinition containerDefinition27 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId27);
			CollectObjectsDelegate collectObjectsDelegate57 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList26);
			containerDefinition27.InitializeForAutoGeneration(collectObjectsDelegate57, false);
			SaveId saveId28 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10010 "));
			ContainerDefinition containerDefinition28 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId28);
			CollectObjectsDelegate collectObjectsDelegate58 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList27);
			containerDefinition28.InitializeForAutoGeneration(collectObjectsDelegate58, false);
			SaveId saveId29 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10011 "));
			ContainerDefinition containerDefinition29 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId29);
			CollectObjectsDelegate collectObjectsDelegate59 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList28);
			containerDefinition29.InitializeForAutoGeneration(collectObjectsDelegate59, false);
			SaveId saveId30 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10011 "));
			ContainerDefinition containerDefinition30 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId30);
			CollectObjectsDelegate collectObjectsDelegate60 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList29);
			containerDefinition30.InitializeForAutoGeneration(collectObjectsDelegate60, false);
			SaveId saveId31 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10011 "));
			ContainerDefinition containerDefinition31 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId31);
			CollectObjectsDelegate collectObjectsDelegate61 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList30);
			containerDefinition31.InitializeForAutoGeneration(collectObjectsDelegate61, false);
			SaveId saveId32 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10042 "));
			ContainerDefinition containerDefinition32 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId32);
			CollectObjectsDelegate collectObjectsDelegate62 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList31);
			containerDefinition32.InitializeForAutoGeneration(collectObjectsDelegate62, false);
			SaveId saveId33 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10042 "));
			ContainerDefinition containerDefinition33 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId33);
			CollectObjectsDelegate collectObjectsDelegate63 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList32);
			containerDefinition33.InitializeForAutoGeneration(collectObjectsDelegate63, false);
			SaveId saveId34 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10042 "));
			ContainerDefinition containerDefinition34 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId34);
			CollectObjectsDelegate collectObjectsDelegate64 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList33);
			containerDefinition34.InitializeForAutoGeneration(collectObjectsDelegate64, false);
			SaveId saveId35 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10038 "));
			ContainerDefinition containerDefinition35 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId35);
			CollectObjectsDelegate collectObjectsDelegate65 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList34);
			containerDefinition35.InitializeForAutoGeneration(collectObjectsDelegate65, false);
			SaveId saveId36 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10038 "));
			ContainerDefinition containerDefinition36 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId36);
			CollectObjectsDelegate collectObjectsDelegate66 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList35);
			containerDefinition36.InitializeForAutoGeneration(collectObjectsDelegate66, false);
			SaveId saveId37 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10038 "));
			ContainerDefinition containerDefinition37 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId37);
			CollectObjectsDelegate collectObjectsDelegate67 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList36);
			containerDefinition37.InitializeForAutoGeneration(collectObjectsDelegate67, false);
			SaveId saveId38 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 11006 "));
			ContainerDefinition containerDefinition38 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId38);
			CollectObjectsDelegate collectObjectsDelegate68 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList37);
			containerDefinition38.InitializeForAutoGeneration(collectObjectsDelegate68, true);
			SaveId saveId39 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 11006 "));
			ContainerDefinition containerDefinition39 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId39);
			CollectObjectsDelegate collectObjectsDelegate69 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList38);
			containerDefinition39.InitializeForAutoGeneration(collectObjectsDelegate69, true);
			SaveId saveId40 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 11006 "));
			ContainerDefinition containerDefinition40 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId40);
			CollectObjectsDelegate collectObjectsDelegate70 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList39);
			containerDefinition40.InitializeForAutoGeneration(collectObjectsDelegate70, true);
			SaveId saveId41 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10016 "));
			ContainerDefinition containerDefinition41 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId41);
			CollectObjectsDelegate collectObjectsDelegate71 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList40);
			containerDefinition41.InitializeForAutoGeneration(collectObjectsDelegate71, false);
			SaveId saveId42 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10016 "));
			ContainerDefinition containerDefinition42 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId42);
			CollectObjectsDelegate collectObjectsDelegate72 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList41);
			containerDefinition42.InitializeForAutoGeneration(collectObjectsDelegate72, false);
			SaveId saveId43 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10016 "));
			ContainerDefinition containerDefinition43 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId43);
			CollectObjectsDelegate collectObjectsDelegate73 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList42);
			containerDefinition43.InitializeForAutoGeneration(collectObjectsDelegate73, false);
			SaveId saveId44 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10004 "));
			ContainerDefinition containerDefinition44 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId44);
			CollectObjectsDelegate collectObjectsDelegate74 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList43);
			containerDefinition44.InitializeForAutoGeneration(collectObjectsDelegate74, false);
			SaveId saveId45 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10004 "));
			ContainerDefinition containerDefinition45 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId45);
			CollectObjectsDelegate collectObjectsDelegate75 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList44);
			containerDefinition45.InitializeForAutoGeneration(collectObjectsDelegate75, false);
			SaveId saveId46 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10004 "));
			ContainerDefinition containerDefinition46 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId46);
			CollectObjectsDelegate collectObjectsDelegate76 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList45);
			containerDefinition46.InitializeForAutoGeneration(collectObjectsDelegate76, false);
			SaveId saveId47 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 11011 "));
			ContainerDefinition containerDefinition47 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId47);
			CollectObjectsDelegate collectObjectsDelegate77 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList46);
			containerDefinition47.InitializeForAutoGeneration(collectObjectsDelegate77, false);
			SaveId saveId48 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 11011 "));
			ContainerDefinition containerDefinition48 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId48);
			CollectObjectsDelegate collectObjectsDelegate78 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList47);
			containerDefinition48.InitializeForAutoGeneration(collectObjectsDelegate78, false);
			SaveId saveId49 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 11011 "));
			ContainerDefinition containerDefinition49 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId49);
			CollectObjectsDelegate collectObjectsDelegate79 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList48);
			containerDefinition49.InitializeForAutoGeneration(collectObjectsDelegate79, false);
			SaveId saveId50 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10009 "));
			ContainerDefinition containerDefinition50 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId50);
			CollectObjectsDelegate collectObjectsDelegate80 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList49);
			containerDefinition50.InitializeForAutoGeneration(collectObjectsDelegate80, false);
			SaveId saveId51 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10009 "));
			ContainerDefinition containerDefinition51 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId51);
			CollectObjectsDelegate collectObjectsDelegate81 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList50);
			containerDefinition51.InitializeForAutoGeneration(collectObjectsDelegate81, false);
			SaveId saveId52 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10009 "));
			ContainerDefinition containerDefinition52 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId52);
			CollectObjectsDelegate collectObjectsDelegate82 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList51);
			containerDefinition52.InitializeForAutoGeneration(collectObjectsDelegate82, false);
			SaveId saveId53 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 11004 "));
			ContainerDefinition containerDefinition53 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId53);
			CollectObjectsDelegate collectObjectsDelegate83 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList52);
			containerDefinition53.InitializeForAutoGeneration(collectObjectsDelegate83, false);
			SaveId saveId54 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 11004 "));
			ContainerDefinition containerDefinition54 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId54);
			CollectObjectsDelegate collectObjectsDelegate84 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList53);
			containerDefinition54.InitializeForAutoGeneration(collectObjectsDelegate84, false);
			SaveId saveId55 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 11004 "));
			ContainerDefinition containerDefinition55 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId55);
			CollectObjectsDelegate collectObjectsDelegate85 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList54);
			containerDefinition55.InitializeForAutoGeneration(collectObjectsDelegate85, false);
			SaveId saveId56 = SaveId.ReadSaveIdFrom(new StringReader("2 1 0 10050 "));
			ContainerDefinition containerDefinition56 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId56);
			CollectObjectsDelegate collectObjectsDelegate86 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList55);
			containerDefinition56.InitializeForAutoGeneration(collectObjectsDelegate86, false);
			SaveId saveId57 = SaveId.ReadSaveIdFrom(new StringReader("2 5 0 10050 "));
			ContainerDefinition containerDefinition57 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId57);
			CollectObjectsDelegate collectObjectsDelegate87 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList56);
			containerDefinition57.InitializeForAutoGeneration(collectObjectsDelegate87, false);
			SaveId saveId58 = SaveId.ReadSaveIdFrom(new StringReader("2 6 0 10050 "));
			ContainerDefinition containerDefinition58 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId58);
			CollectObjectsDelegate collectObjectsDelegate88 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForList57);
			containerDefinition58.InitializeForAutoGeneration(collectObjectsDelegate88, false);
			SaveId saveId59 = SaveId.ReadSaveIdFrom(new StringReader("2 2 0 11011 0 30001 "));
			ContainerDefinition containerDefinition59 = (ContainerDefinition)definitionContext.TryGetTypeDefinition(saveId59);
			CollectObjectsDelegate collectObjectsDelegate89 = new CollectObjectsDelegate(AutoGeneratedSaveManager.AutoGeneratedStaticCollectObjectsForDictionary58);
			containerDefinition59.InitializeForAutoGeneration(collectObjectsDelegate89, false);
		}

		// Token: 0x060001B9 RID: 441 RVA: 0x00008CB0 File Offset: 0x00006EB0
		private static void AutoGeneratedStaticCollectObjectsForArray0(object o, List<object> collectedObjects)
		{
			ItemRosterElement[] array = (ItemRosterElement[])o;
			for (int i = 0; i < array.Length; i++)
			{
				ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement(array[i], collectedObjects);
			}
		}

		// Token: 0x060001BA RID: 442 RVA: 0x00008CE4 File Offset: 0x00006EE4
		private static void AutoGeneratedStaticCollectObjectsForArray1(object o, List<object> collectedObjects)
		{
			EquipmentElement[] array = (EquipmentElement[])o;
			for (int i = 0; i < array.Length; i++)
			{
				EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement(array[i], collectedObjects);
			}
		}

		// Token: 0x060001BB RID: 443 RVA: 0x00008D18 File Offset: 0x00006F18
		private static void AutoGeneratedStaticCollectObjectsForArray2(object o, List<object> collectedObjects)
		{
			foreach (Equipment equipment in (Equipment[])o)
			{
				collectedObjects.Add(equipment);
			}
		}

		// Token: 0x060001BC RID: 444 RVA: 0x00008D48 File Offset: 0x00006F48
		private static void AutoGeneratedStaticCollectObjectsForArray3(object o, List<object> collectedObjects)
		{
			foreach (WeaponDesignElement weaponDesignElement in (WeaponDesignElement[])o)
			{
				collectedObjects.Add(weaponDesignElement);
			}
		}

		// Token: 0x060001BD RID: 445 RVA: 0x00008D78 File Offset: 0x00006F78
		private static void AutoGeneratedStaticCollectObjectsForList4(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemObject itemObject = (ItemObject)list[i];
				collectedObjects.Add(itemObject);
			}
		}

		// Token: 0x060001BE RID: 446 RVA: 0x00008DB4 File Offset: 0x00006FB4
		private static void AutoGeneratedStaticCollectObjectsForList5(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemObject itemObject = (ItemObject)list[i];
				collectedObjects.Add(itemObject);
			}
		}

		// Token: 0x060001BF RID: 447 RVA: 0x00008DF0 File Offset: 0x00006FF0
		private static void AutoGeneratedStaticCollectObjectsForList6(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemObject itemObject = (ItemObject)list[i];
				collectedObjects.Add(itemObject);
			}
		}

		// Token: 0x060001C0 RID: 448 RVA: 0x00008E2C File Offset: 0x0000702C
		private static void AutoGeneratedStaticCollectObjectsForList7(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemComponent itemComponent = (ItemComponent)list[i];
				collectedObjects.Add(itemComponent);
			}
		}

		// Token: 0x060001C1 RID: 449 RVA: 0x00008E68 File Offset: 0x00007068
		private static void AutoGeneratedStaticCollectObjectsForList8(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemComponent itemComponent = (ItemComponent)list[i];
				collectedObjects.Add(itemComponent);
			}
		}

		// Token: 0x060001C2 RID: 450 RVA: 0x00008EA4 File Offset: 0x000070A4
		private static void AutoGeneratedStaticCollectObjectsForList9(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemComponent itemComponent = (ItemComponent)list[i];
				collectedObjects.Add(itemComponent);
			}
		}

		// Token: 0x060001C3 RID: 451 RVA: 0x00008EE0 File Offset: 0x000070E0
		private static void AutoGeneratedStaticCollectObjectsForList10(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemModifier itemModifier = (ItemModifier)list[i];
				collectedObjects.Add(itemModifier);
			}
		}

		// Token: 0x060001C4 RID: 452 RVA: 0x00008F1C File Offset: 0x0000711C
		private static void AutoGeneratedStaticCollectObjectsForList11(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemModifier itemModifier = (ItemModifier)list[i];
				collectedObjects.Add(itemModifier);
			}
		}

		// Token: 0x060001C5 RID: 453 RVA: 0x00008F58 File Offset: 0x00007158
		private static void AutoGeneratedStaticCollectObjectsForList12(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemModifier itemModifier = (ItemModifier)list[i];
				collectedObjects.Add(itemModifier);
			}
		}

		// Token: 0x060001C6 RID: 454 RVA: 0x00008F94 File Offset: 0x00007194
		private static void AutoGeneratedStaticCollectObjectsForList13(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemModifierGroup itemModifierGroup = (ItemModifierGroup)list[i];
				collectedObjects.Add(itemModifierGroup);
			}
		}

		// Token: 0x060001C7 RID: 455 RVA: 0x00008FD0 File Offset: 0x000071D0
		private static void AutoGeneratedStaticCollectObjectsForList14(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemModifierGroup itemModifierGroup = (ItemModifierGroup)list[i];
				collectedObjects.Add(itemModifierGroup);
			}
		}

		// Token: 0x060001C8 RID: 456 RVA: 0x0000900C File Offset: 0x0000720C
		private static void AutoGeneratedStaticCollectObjectsForList15(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemModifierGroup itemModifierGroup = (ItemModifierGroup)list[i];
				collectedObjects.Add(itemModifierGroup);
			}
		}

		// Token: 0x060001C9 RID: 457 RVA: 0x00009048 File Offset: 0x00007248
		private static void AutoGeneratedStaticCollectObjectsForList16(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CharacterAttribute characterAttribute = (CharacterAttribute)list[i];
				collectedObjects.Add(characterAttribute);
			}
		}

		// Token: 0x060001CA RID: 458 RVA: 0x00009084 File Offset: 0x00007284
		private static void AutoGeneratedStaticCollectObjectsForList17(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CharacterAttribute characterAttribute = (CharacterAttribute)list[i];
				collectedObjects.Add(characterAttribute);
			}
		}

		// Token: 0x060001CB RID: 459 RVA: 0x000090C0 File Offset: 0x000072C0
		private static void AutoGeneratedStaticCollectObjectsForList18(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CharacterAttribute characterAttribute = (CharacterAttribute)list[i];
				collectedObjects.Add(characterAttribute);
			}
		}

		// Token: 0x060001CC RID: 460 RVA: 0x000090FC File Offset: 0x000072FC
		private static void AutoGeneratedStaticCollectObjectsForList19(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				SkillObject skillObject = (SkillObject)list[i];
				collectedObjects.Add(skillObject);
			}
		}

		// Token: 0x060001CD RID: 461 RVA: 0x00009138 File Offset: 0x00007338
		private static void AutoGeneratedStaticCollectObjectsForList20(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				SkillObject skillObject = (SkillObject)list[i];
				collectedObjects.Add(skillObject);
			}
		}

		// Token: 0x060001CE RID: 462 RVA: 0x00009174 File Offset: 0x00007374
		private static void AutoGeneratedStaticCollectObjectsForList21(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				SkillObject skillObject = (SkillObject)list[i];
				collectedObjects.Add(skillObject);
			}
		}

		// Token: 0x060001CF RID: 463 RVA: 0x000091B0 File Offset: 0x000073B0
		private static void AutoGeneratedStaticCollectObjectsForList22(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemCategory itemCategory = (ItemCategory)list[i];
				collectedObjects.Add(itemCategory);
			}
		}

		// Token: 0x060001D0 RID: 464 RVA: 0x000091EC File Offset: 0x000073EC
		private static void AutoGeneratedStaticCollectObjectsForList23(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemCategory itemCategory = (ItemCategory)list[i];
				collectedObjects.Add(itemCategory);
			}
		}

		// Token: 0x060001D1 RID: 465 RVA: 0x00009228 File Offset: 0x00007428
		private static void AutoGeneratedStaticCollectObjectsForList24(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemCategory itemCategory = (ItemCategory)list[i];
				collectedObjects.Add(itemCategory);
			}
		}

		// Token: 0x060001D2 RID: 466 RVA: 0x00009264 File Offset: 0x00007464
		private static void AutoGeneratedStaticCollectObjectsForList25(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CraftingPiece craftingPiece = (CraftingPiece)list[i];
				collectedObjects.Add(craftingPiece);
			}
		}

		// Token: 0x060001D3 RID: 467 RVA: 0x000092A0 File Offset: 0x000074A0
		private static void AutoGeneratedStaticCollectObjectsForList26(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CraftingPiece craftingPiece = (CraftingPiece)list[i];
				collectedObjects.Add(craftingPiece);
			}
		}

		// Token: 0x060001D4 RID: 468 RVA: 0x000092DC File Offset: 0x000074DC
		private static void AutoGeneratedStaticCollectObjectsForList27(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CraftingPiece craftingPiece = (CraftingPiece)list[i];
				collectedObjects.Add(craftingPiece);
			}
		}

		// Token: 0x060001D5 RID: 469 RVA: 0x00009318 File Offset: 0x00007518
		private static void AutoGeneratedStaticCollectObjectsForList28(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CraftingTemplate craftingTemplate = (CraftingTemplate)list[i];
				collectedObjects.Add(craftingTemplate);
			}
		}

		// Token: 0x060001D6 RID: 470 RVA: 0x00009354 File Offset: 0x00007554
		private static void AutoGeneratedStaticCollectObjectsForList29(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CraftingTemplate craftingTemplate = (CraftingTemplate)list[i];
				collectedObjects.Add(craftingTemplate);
			}
		}

		// Token: 0x060001D7 RID: 471 RVA: 0x00009390 File Offset: 0x00007590
		private static void AutoGeneratedStaticCollectObjectsForList30(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				CraftingTemplate craftingTemplate = (CraftingTemplate)list[i];
				collectedObjects.Add(craftingTemplate);
			}
		}

		// Token: 0x060001D8 RID: 472 RVA: 0x000093CC File Offset: 0x000075CC
		private static void AutoGeneratedStaticCollectObjectsForList31(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				SiegeEngineType siegeEngineType = (SiegeEngineType)list[i];
				collectedObjects.Add(siegeEngineType);
			}
		}

		// Token: 0x060001D9 RID: 473 RVA: 0x00009408 File Offset: 0x00007608
		private static void AutoGeneratedStaticCollectObjectsForList32(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				SiegeEngineType siegeEngineType = (SiegeEngineType)list[i];
				collectedObjects.Add(siegeEngineType);
			}
		}

		// Token: 0x060001DA RID: 474 RVA: 0x00009444 File Offset: 0x00007644
		private static void AutoGeneratedStaticCollectObjectsForList33(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				SiegeEngineType siegeEngineType = (SiegeEngineType)list[i];
				collectedObjects.Add(siegeEngineType);
			}
		}

		// Token: 0x060001DB RID: 475 RVA: 0x00009480 File Offset: 0x00007680
		private static void AutoGeneratedStaticCollectObjectsForList34(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				PropertyObject propertyObject = (PropertyObject)list[i];
				collectedObjects.Add(propertyObject);
			}
		}

		// Token: 0x060001DC RID: 476 RVA: 0x000094BC File Offset: 0x000076BC
		private static void AutoGeneratedStaticCollectObjectsForList35(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				PropertyObject propertyObject = (PropertyObject)list[i];
				collectedObjects.Add(propertyObject);
			}
		}

		// Token: 0x060001DD RID: 477 RVA: 0x000094F8 File Offset: 0x000076F8
		private static void AutoGeneratedStaticCollectObjectsForList36(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				PropertyObject propertyObject = (PropertyObject)list[i];
				collectedObjects.Add(propertyObject);
			}
		}

		// Token: 0x060001DE RID: 478 RVA: 0x00009531 File Offset: 0x00007731
		private static void AutoGeneratedStaticCollectObjectsForList37(object o, List<object> collectedObjects)
		{
		}

		// Token: 0x060001DF RID: 479 RVA: 0x00009533 File Offset: 0x00007733
		private static void AutoGeneratedStaticCollectObjectsForList38(object o, List<object> collectedObjects)
		{
		}

		// Token: 0x060001E0 RID: 480 RVA: 0x00009535 File Offset: 0x00007735
		private static void AutoGeneratedStaticCollectObjectsForList39(object o, List<object> collectedObjects)
		{
		}

		// Token: 0x060001E1 RID: 481 RVA: 0x00009538 File Offset: 0x00007738
		private static void AutoGeneratedStaticCollectObjectsForList40(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				Equipment equipment = (Equipment)list[i];
				collectedObjects.Add(equipment);
			}
		}

		// Token: 0x060001E2 RID: 482 RVA: 0x00009574 File Offset: 0x00007774
		private static void AutoGeneratedStaticCollectObjectsForList41(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				Equipment equipment = (Equipment)list[i];
				collectedObjects.Add(equipment);
			}
		}

		// Token: 0x060001E3 RID: 483 RVA: 0x000095B0 File Offset: 0x000077B0
		private static void AutoGeneratedStaticCollectObjectsForList42(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				Equipment equipment = (Equipment)list[i];
				collectedObjects.Add(equipment);
			}
		}

		// Token: 0x060001E4 RID: 484 RVA: 0x000095EC File Offset: 0x000077EC
		private static void AutoGeneratedStaticCollectObjectsForList43(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				BannerData bannerData = (BannerData)list[i];
				collectedObjects.Add(bannerData);
			}
		}

		// Token: 0x060001E5 RID: 485 RVA: 0x00009628 File Offset: 0x00007828
		private static void AutoGeneratedStaticCollectObjectsForList44(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				BannerData bannerData = (BannerData)list[i];
				collectedObjects.Add(bannerData);
			}
		}

		// Token: 0x060001E6 RID: 486 RVA: 0x00009664 File Offset: 0x00007864
		private static void AutoGeneratedStaticCollectObjectsForList45(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				BannerData bannerData = (BannerData)list[i];
				collectedObjects.Add(bannerData);
			}
		}

		// Token: 0x060001E7 RID: 487 RVA: 0x000096A0 File Offset: 0x000078A0
		private static void AutoGeneratedStaticCollectObjectsForList46(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement((EquipmentElement)list[i], collectedObjects);
			}
		}

		// Token: 0x060001E8 RID: 488 RVA: 0x000096DC File Offset: 0x000078DC
		private static void AutoGeneratedStaticCollectObjectsForList47(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement((EquipmentElement)list[i], collectedObjects);
			}
		}

		// Token: 0x060001E9 RID: 489 RVA: 0x00009718 File Offset: 0x00007918
		private static void AutoGeneratedStaticCollectObjectsForList48(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement((EquipmentElement)list[i], collectedObjects);
			}
		}

		// Token: 0x060001EA RID: 490 RVA: 0x00009754 File Offset: 0x00007954
		private static void AutoGeneratedStaticCollectObjectsForList49(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				WeaponDesign weaponDesign = (WeaponDesign)list[i];
				collectedObjects.Add(weaponDesign);
			}
		}

		// Token: 0x060001EB RID: 491 RVA: 0x00009790 File Offset: 0x00007990
		private static void AutoGeneratedStaticCollectObjectsForList50(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				WeaponDesign weaponDesign = (WeaponDesign)list[i];
				collectedObjects.Add(weaponDesign);
			}
		}

		// Token: 0x060001EC RID: 492 RVA: 0x000097CC File Offset: 0x000079CC
		private static void AutoGeneratedStaticCollectObjectsForList51(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				WeaponDesign weaponDesign = (WeaponDesign)list[i];
				collectedObjects.Add(weaponDesign);
			}
		}

		// Token: 0x060001ED RID: 493 RVA: 0x00009808 File Offset: 0x00007A08
		private static void AutoGeneratedStaticCollectObjectsForList52(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement((ItemRosterElement)list[i], collectedObjects);
			}
		}

		// Token: 0x060001EE RID: 494 RVA: 0x00009844 File Offset: 0x00007A44
		private static void AutoGeneratedStaticCollectObjectsForList53(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement((ItemRosterElement)list[i], collectedObjects);
			}
		}

		// Token: 0x060001EF RID: 495 RVA: 0x00009880 File Offset: 0x00007A80
		private static void AutoGeneratedStaticCollectObjectsForList54(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				ItemRosterElement.AutoGeneratedStaticCollectObjectsItemRosterElement((ItemRosterElement)list[i], collectedObjects);
			}
		}

		// Token: 0x060001F0 RID: 496 RVA: 0x000098BC File Offset: 0x00007ABC
		private static void AutoGeneratedStaticCollectObjectsForList55(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				InformationData informationData = (InformationData)list[i];
				collectedObjects.Add(informationData);
			}
		}

		// Token: 0x060001F1 RID: 497 RVA: 0x000098F8 File Offset: 0x00007AF8
		private static void AutoGeneratedStaticCollectObjectsForList56(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				InformationData informationData = (InformationData)list[i];
				collectedObjects.Add(informationData);
			}
		}

		// Token: 0x060001F2 RID: 498 RVA: 0x00009934 File Offset: 0x00007B34
		private static void AutoGeneratedStaticCollectObjectsForList57(object o, List<object> collectedObjects)
		{
			IList list = (IList)o;
			for (int i = 0; i < list.Count; i++)
			{
				InformationData informationData = (InformationData)list[i];
				collectedObjects.Add(informationData);
			}
		}

		// Token: 0x060001F3 RID: 499 RVA: 0x00009970 File Offset: 0x00007B70
		private static void AutoGeneratedStaticCollectObjectsForDictionary58(object o, List<object> collectedObjects)
		{
			foreach (object obj in ((IDictionary)o).Keys)
			{
				EquipmentElement.AutoGeneratedStaticCollectObjectsEquipmentElement(obj, collectedObjects);
			}
		}
	}
}
