using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
	// Token: 0x0200003D RID: 61
	public class MBFastRandom
	{
		// Token: 0x060004B0 RID: 1200 RVA: 0x00011D79 File Offset: 0x0000FF79
		internal static void AutoGeneratedStaticCollectObjectsMBFastRandom(object o, List<object> collectedObjects)
		{
			((MBFastRandom)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060004B1 RID: 1201 RVA: 0x00011D87 File Offset: 0x0000FF87
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x060004B2 RID: 1202 RVA: 0x00011D89 File Offset: 0x0000FF89
		internal static object AutoGeneratedGetMemberValue_x(object o)
		{
			return ((MBFastRandom)o)._x;
		}

		// Token: 0x060004B3 RID: 1203 RVA: 0x00011D9B File Offset: 0x0000FF9B
		internal static object AutoGeneratedGetMemberValue_y(object o)
		{
			return ((MBFastRandom)o)._y;
		}

		// Token: 0x060004B4 RID: 1204 RVA: 0x00011DAD File Offset: 0x0000FFAD
		internal static object AutoGeneratedGetMemberValue_z(object o)
		{
			return ((MBFastRandom)o)._z;
		}

		// Token: 0x060004B5 RID: 1205 RVA: 0x00011DBF File Offset: 0x0000FFBF
		internal static object AutoGeneratedGetMemberValue_w(object o)
		{
			return ((MBFastRandom)o)._w;
		}

		// Token: 0x060004B6 RID: 1206 RVA: 0x00011DD1 File Offset: 0x0000FFD1
		public MBFastRandom()
			: this((uint)Environment.TickCount)
		{
		}

		// Token: 0x060004B7 RID: 1207 RVA: 0x00011DDE File Offset: 0x0000FFDE
		public MBFastRandom(uint seed)
		{
			MBFastRandom.GenerateState(seed, out this._x, out this._y, out this._z, out this._w);
		}

		// Token: 0x060004B8 RID: 1208 RVA: 0x00011E04 File Offset: 0x00010004
		public void SetSeed(uint seed, uint seed2)
		{
			MBFastRandom.GenerateState(seed, seed2, out this._x, out this._y, out this._z, out this._w);
		}

		// Token: 0x060004B9 RID: 1209 RVA: 0x00011E28 File Offset: 0x00010028
		public int Next()
		{
			uint num;
			do
			{
				num = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
				num &= 2147483647U;
			}
			while (num == 2147483647U);
			return (int)num;
		}

		// Token: 0x060004BA RID: 1210 RVA: 0x00011E64 File Offset: 0x00010064
		public int Next(int maxValue)
		{
			if (maxValue < 0)
			{
				throw new ArgumentOutOfRangeException("maxValue", "Maximum value must be non-negative.");
			}
			uint num = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
			return (int)(4.656612873077393E-10 * (double)(2147483647U & num) * (double)maxValue);
		}

		// Token: 0x060004BB RID: 1211 RVA: 0x00011EBC File Offset: 0x000100BC
		public int Next(int minValue, int maxValue)
		{
			if (minValue > maxValue)
			{
				throw new ArgumentOutOfRangeException("maxValue", maxValue, "Maximum value must be greater than or equal to minimum value");
			}
			uint num = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
			int num2 = maxValue - minValue;
			if (num2 < 0)
			{
				return minValue + (int)(2.3283064365386963E-10 * num * (double)((long)maxValue - (long)minValue));
			}
			return minValue + (int)(4.656612873077393E-10 * (double)(2147483647U & num) * (double)num2);
		}

		// Token: 0x060004BC RID: 1212 RVA: 0x00011F3C File Offset: 0x0001013C
		public double NextDouble()
		{
			uint num = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
			return 4.656612873077393E-10 * (double)(2147483647U & num);
		}

		// Token: 0x060004BD RID: 1213 RVA: 0x00011F7C File Offset: 0x0001017C
		public float NextFloat()
		{
			uint num = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
			return 5.9604645E-08f * (float)(16777215U & num);
		}

		// Token: 0x060004BE RID: 1214 RVA: 0x00011FB8 File Offset: 0x000101B8
		public void NextBytes(byte[] buffer)
		{
			int i = 0;
			int num = buffer.Length - 3;
			while (i < num)
			{
				uint num2 = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
				buffer[i++] = (byte)num2;
				buffer[i++] = (byte)(num2 >> 8);
				buffer[i++] = (byte)(num2 >> 16);
				buffer[i++] = (byte)(num2 >> 24);
			}
			if (i < buffer.Length)
			{
				uint num3 = MBFastRandom.XorShift(ref this._x, ref this._y, ref this._z, ref this._w);
				buffer[i++] = (byte)num3;
				if (i < buffer.Length)
				{
					buffer[i++] = (byte)(num3 >> 8);
					if (i < buffer.Length)
					{
						buffer[i++] = (byte)(num3 >> 16);
						if (i < buffer.Length)
						{
							buffer[i] = (byte)(num3 >> 24);
						}
					}
				}
			}
		}

		// Token: 0x060004BF RID: 1215 RVA: 0x0001207C File Offset: 0x0001027C
		internal static int GetRandomInt(uint seed, uint seed2)
		{
			uint num;
			uint num2;
			uint num3;
			uint num4;
			MBFastRandom.GenerateState(seed, seed2, out num, out num2, out num3, out num4);
			uint num5;
			do
			{
				num5 = MBFastRandom.XorShift(ref num, ref num2, ref num3, ref num4);
				num5 &= 2147483647U;
			}
			while (num5 == 2147483647U);
			return (int)num5;
		}

		// Token: 0x060004C0 RID: 1216 RVA: 0x000120BC File Offset: 0x000102BC
		internal static float GetRandomFloat(uint seed, uint seed2)
		{
			uint num;
			uint num2;
			uint num3;
			uint num4;
			MBFastRandom.GenerateState(seed, seed2, out num, out num2, out num3, out num4);
			uint num5 = MBFastRandom.XorShift(ref num, ref num2, ref num3, ref num4);
			return 5.9604645E-08f * (float)(16777215U & num5);
		}

		// Token: 0x060004C1 RID: 1217 RVA: 0x000120F8 File Offset: 0x000102F8
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static uint XorShift(ref uint x, ref uint y, ref uint z, ref uint w)
		{
			uint num = x ^ (x << 11);
			x = y;
			y = z;
			z = w;
			w = w ^ (w >> 19) ^ (num ^ (num >> 8));
			return w;
		}

		// Token: 0x060004C2 RID: 1218 RVA: 0x0001212C File Offset: 0x0001032C
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void GenerateState(uint seed, out uint x, out uint y, out uint z, out uint w)
		{
			x = MBFastRandom.CalculateHashFromSeed(14695981039346656037UL, seed);
			y = MBFastRandom.CalculateHashFromSeed(14695981039346656037UL, x);
			z = MBFastRandom.CalculateHashFromSeed((ulong)x, y);
			w = MBFastRandom.CalculateHashFromSeed((ulong)y, z);
		}

		// Token: 0x060004C3 RID: 1219 RVA: 0x0001216C File Offset: 0x0001036C
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static void GenerateState(uint seed, uint seed2, out uint x, out uint y, out uint z, out uint w)
		{
			uint num = MBFastRandom.CalculateHashFromSeed((ulong)MBFastRandom.CalculateHashFromSeed(14695981039346656037UL, seed), seed2);
			x = MBFastRandom.CalculateHashFromSeed(14695981039346656037UL, num);
			y = MBFastRandom.CalculateHashFromSeed(14695981039346656037UL, x);
			z = MBFastRandom.CalculateHashFromSeed((ulong)x, y);
			w = MBFastRandom.CalculateHashFromSeed((ulong)y, z);
		}

		// Token: 0x060004C4 RID: 1220 RVA: 0x000121CE File Offset: 0x000103CE
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		private static uint CalculateHashFromSeed(ulong inputHash, uint seed)
		{
			return (uint)((inputHash ^ (ulong)seed) * 1099511628211UL >> 17);
		}

		// Token: 0x0400024E RID: 590
		private const ulong InitialHash = 14695981039346656037UL;

		// Token: 0x0400024F RID: 591
		private const ulong Prime = 1099511628211UL;

		// Token: 0x04000250 RID: 592
		private const double RealUnitInt = 4.656612873077393E-10;

		// Token: 0x04000251 RID: 593
		private const double RealUnitUint = 2.3283064365386963E-10;

		// Token: 0x04000252 RID: 594
		private const int FloatUnitRangeMax = 16777215;

		// Token: 0x04000253 RID: 595
		private const float FloatUnitInt = 5.9604645E-08f;

		// Token: 0x04000254 RID: 596
		[SaveableField(1)]
		private uint _x;

		// Token: 0x04000255 RID: 597
		[SaveableField(2)]
		private uint _y;

		// Token: 0x04000256 RID: 598
		[SaveableField(3)]
		private uint _z;

		// Token: 0x04000257 RID: 599
		[SaveableField(4)]
		private uint _w;
	}
}
