using System;
using System.Collections.Generic;

namespace TaleWorlds.Core
{
	// Token: 0x02000032 RID: 50
	public class MissionResult
	{
		// Token: 0x060003B9 RID: 953 RVA: 0x0000EFFA File Offset: 0x0000D1FA
		internal static void AutoGeneratedStaticCollectObjectsMissionResult(object o, List<object> collectedObjects)
		{
			((MissionResult)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060003BA RID: 954 RVA: 0x0000F008 File Offset: 0x0000D208
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x1700013D RID: 317
		// (get) Token: 0x060003BB RID: 955 RVA: 0x0000F00A File Offset: 0x0000D20A
		// (set) Token: 0x060003BC RID: 956 RVA: 0x0000F012 File Offset: 0x0000D212
		public BattleState BattleState { get; private set; }

		// Token: 0x1700013E RID: 318
		// (get) Token: 0x060003BD RID: 957 RVA: 0x0000F01B File Offset: 0x0000D21B
		public bool BattleResolved
		{
			get
			{
				return this.PlayerVictory || this.PlayerDefeated;
			}
		}

		// Token: 0x1700013F RID: 319
		// (get) Token: 0x060003BE RID: 958 RVA: 0x0000F02D File Offset: 0x0000D22D
		// (set) Token: 0x060003BF RID: 959 RVA: 0x0000F035 File Offset: 0x0000D235
		public bool PlayerVictory { get; private set; }

		// Token: 0x17000140 RID: 320
		// (get) Token: 0x060003C0 RID: 960 RVA: 0x0000F03E File Offset: 0x0000D23E
		// (set) Token: 0x060003C1 RID: 961 RVA: 0x0000F046 File Offset: 0x0000D246
		public bool PlayerDefeated { get; private set; }

		// Token: 0x17000141 RID: 321
		// (get) Token: 0x060003C2 RID: 962 RVA: 0x0000F04F File Offset: 0x0000D24F
		// (set) Token: 0x060003C3 RID: 963 RVA: 0x0000F057 File Offset: 0x0000D257
		public bool EnemyRetreated { get; private set; }

		// Token: 0x060003C4 RID: 964 RVA: 0x0000F060 File Offset: 0x0000D260
		public MissionResult(BattleState battleState, bool playerVictory, bool playerDefeated, bool enemyRetreated)
		{
			this.BattleState = battleState;
			this.PlayerVictory = playerVictory;
			this.PlayerDefeated = playerDefeated;
			this.EnemyRetreated = enemyRetreated;
		}

		// Token: 0x060003C5 RID: 965 RVA: 0x0000F085 File Offset: 0x0000D285
		public MissionResult()
		{
			this.PlayerVictory = false;
			this.PlayerDefeated = false;
			this.EnemyRetreated = false;
		}

		// Token: 0x060003C6 RID: 966 RVA: 0x0000F0A2 File Offset: 0x0000D2A2
		public static MissionResult CreateSuccessful(IMission mission, bool enemyRetreated = false)
		{
			return new MissionResult((mission.PlayerTeam.Side == BattleSideEnum.Attacker) ? BattleState.AttackerVictory : BattleState.DefenderVictory, true, false, enemyRetreated);
		}

		// Token: 0x060003C7 RID: 967 RVA: 0x0000F0BE File Offset: 0x0000D2BE
		public static MissionResult CreateDefeated(IMission mission)
		{
			return new MissionResult((mission.PlayerTeam.Side == BattleSideEnum.Attacker) ? BattleState.DefenderVictory : BattleState.AttackerVictory, false, true, false);
		}

		// Token: 0x060003C8 RID: 968 RVA: 0x0000F0DA File Offset: 0x0000D2DA
		public static MissionResult CreateDefenderPushedBack()
		{
			return new MissionResult(BattleState.DefenderPullBack, false, false, false);
		}
	}
}
