using System;
using System.Collections.Generic;
using System.Xml;
using TaleWorlds.Library;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.Core
{
	// Token: 0x02000035 RID: 53
	public class PropertyOwner<T> : MBObjectBase where T : MBObjectBase
	{
		// Token: 0x060003DB RID: 987 RVA: 0x0000F1E7 File Offset: 0x0000D3E7
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._attributes);
		}

		// Token: 0x060003DC RID: 988 RVA: 0x0000F1FC File Offset: 0x0000D3FC
		public PropertyOwner()
		{
			this._attributes = new Dictionary<T, int>();
		}

		// Token: 0x060003DD RID: 989 RVA: 0x0000F20F File Offset: 0x0000D40F
		public PropertyOwner(PropertyOwner<T> propertyOwner)
		{
			this._attributes = new Dictionary<T, int>(propertyOwner._attributes);
		}

		// Token: 0x060003DE RID: 990 RVA: 0x0000F228 File Offset: 0x0000D428
		public void SetPropertyValue(T attribute, int value)
		{
			if (value != 0)
			{
				this._attributes[attribute] = value;
				return;
			}
			if (this.HasProperty(attribute))
			{
				this._attributes.Remove(attribute);
			}
		}

		// Token: 0x060003DF RID: 991 RVA: 0x0000F254 File Offset: 0x0000D454
		public int GetPropertyValue(T attribute)
		{
			if (attribute == null)
			{
				Debug.FailedAssert("attribute in GetPropertyValue can not be null!", "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.Core\\PropertyOwner.cs", "GetPropertyValue", 52);
				return 0;
			}
			int num;
			if (!this._attributes.TryGetValue(attribute, out num))
			{
				return 0;
			}
			return num;
		}

		// Token: 0x060003E0 RID: 992 RVA: 0x0000F294 File Offset: 0x0000D494
		public bool HasProperty(T attribute)
		{
			return this._attributes.ContainsKey(attribute);
		}

		// Token: 0x060003E1 RID: 993 RVA: 0x0000F2A2 File Offset: 0x0000D4A2
		public void ClearAllProperty()
		{
			this._attributes.Clear();
		}

		// Token: 0x060003E2 RID: 994 RVA: 0x0000F2B0 File Offset: 0x0000D4B0
		public void Serialize(XmlWriter writer)
		{
			writer.WriteStartElement("attributes");
			foreach (KeyValuePair<T, int> keyValuePair in this._attributes)
			{
				writer.WriteStartElement("attribute");
				writer.WriteAttributeString("id", keyValuePair.Key.StringId);
				writer.WriteAttributeString("value", keyValuePair.Value.ToString());
				writer.WriteEndElement();
			}
			writer.WriteEndElement();
		}

		// Token: 0x060003E3 RID: 995 RVA: 0x0000F354 File Offset: 0x0000D554
		public override void Deserialize(MBObjectManager objectManager, XmlNode node)
		{
			this.Initialize();
			foreach (object obj in node.ChildNodes)
			{
				XmlNode xmlNode = (XmlNode)obj;
				if (xmlNode.Name == "attributes")
				{
					foreach (object obj2 in xmlNode.ChildNodes)
					{
						XmlNode xmlNode2 = (XmlNode)obj2;
						if (xmlNode2.Name == "attribute")
						{
							string innerText = xmlNode2.Attributes["id"].InnerText;
							if (innerText.Substring(0, innerText.IndexOf('.')).Equals("Attrib"))
							{
								T t = objectManager.ReadObjectReferenceFromXml("id", typeof(T), xmlNode2) as T;
								int num = Convert.ToInt32(xmlNode2.Attributes["value"].Value);
								this.SetPropertyValue(t, num);
							}
						}
					}
				}
			}
		}

		// Token: 0x04000208 RID: 520
		[SaveableField(10)]
		protected readonly Dictionary<T, int> _attributes;
	}
}
