using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.LinQuick;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	public class GangLeaderNeedsToOffloadStolenGoodsIssueBehavior : CampaignBehaviorBase
	{
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		public override void SyncData(IDataStore dataStore)
		{
		}

		private bool ConditionsHold(Hero issueGiver, out Settlement selectedHideout)
		{
			selectedHideout = null;
			bool flag = issueGiver.IsGangLeader && issueGiver.CurrentSettlement.Town.Security < 70f && issueGiver.CurrentSettlement.Notables.Any((Hero x) => x.CharacterObject.IsHero && x.CharacterObject.HeroObject != issueGiver && x.CharacterObject.HeroObject.IsMerchant);
			selectedHideout = ((issueGiver.CurrentSettlement != null && issueGiver.CurrentSettlement.IsTown) ? GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.FindSuitableHideout(issueGiver.CurrentSettlement) : null);
			return flag && selectedHideout != null;
		}

		public void OnCheckForIssue(Hero hero)
		{
			Settlement settlement;
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, this.ConditionsHold(hero, out settlement) ? new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue), IssueBase.IssueFrequency.Common, settlement) : new PotentialIssueData(typeof(GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue), IssueBase.IssueFrequency.Common));
		}

		private static Settlement FindSuitableHideout(Settlement settlement)
		{
			Settlement settlement2 = null;
			float num = float.MaxValue;
			foreach (Hideout hideout in Campaign.Current.AllHideouts.Where((Hideout t) => t.IsInfested))
			{
				float num2 = hideout.Settlement.GatePosition.DistanceSquared(settlement.Position2D);
				if (num2 <= 3600f && num2 < num)
				{
					num = num2;
					settlement2 = hideout.Settlement;
				}
			}
			return settlement2;
		}

		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			PotentialIssueData potentialIssueData = pid;
			return new GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue(issueOwner, potentialIssueData.RelatedObject as Settlement);
		}

		private const int IssueDuration = 15;

		private const int MaxHideoutDistance = 60;

		private const IssueBase.IssueFrequency GangLeaderNeedsToOffloadStolenGoodsIssueFrequency = IssueBase.IssueFrequency.Common;

		public class GangLeaderNeedsToOffloadStolenGoodsIssue : IssueBase
		{
			internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsToOffloadStolenGoodsIssue(object o, List<object> collectedObjects)
			{
				((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._issueHideout);
				collectedObjects.Add(this.CounterOfferHero);
			}

			internal static object AutoGeneratedGetMemberValueCounterOfferHero(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue)o).CounterOfferHero;
			}

			internal static object AutoGeneratedGetMemberValue_randomForStolenTradeGood(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue)o)._randomForStolenTradeGood;
			}

			internal static object AutoGeneratedGetMemberValue_issueHideout(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue)o)._issueHideout;
			}

			private ItemObject StolenTradeGood
			{
				get
				{
					return Game.Current.ObjectManager.GetObject<ItemObject>(GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue.PossibleStolenItems[this._randomForStolenTradeGood]);
				}
			}

			private int StolenTradeGoodAmount
			{
				get
				{
					return MathF.Ceiling(10000f / (float)base.IssueOwner.CurrentSettlement.Town.GetItemPrice(this.StolenTradeGood, null, false) * base.IssueDifficultyMultiplier);
				}
			}

			private int StolenTradeGoodPrice
			{
				get
				{
					return MathF.Round((float)base.IssueOwner.CurrentSettlement.Town.GetItemPrice(this.StolenTradeGood, null, false) * 0.5f * (float)this.StolenTradeGoodAmount);
				}
			}

			protected override int RewardGold
			{
				get
				{
					return MathF.Round((float)base.IssueOwner.CurrentSettlement.Town.GetItemPrice(this.StolenTradeGood, null, false) * 0.4f * (float)this.StolenTradeGoodAmount);
				}
			}

			[SaveableProperty(10)]
			public override Hero CounterOfferHero { get; protected set; }

			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			protected override bool IssueQuestCanBeDuplicated
			{
				get
				{
					return false;
				}
			}

			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=cODzH0Ke}Well, if you don't want to go yourself to meet them, I'm sure you can send a trusted aide with 10 or so men to load and guard those {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}. I am sure our people can seal the deal by themselves.", null);
					textObject.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
					textObject.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
					return textObject;
				}
			}

			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=ltiz6e11}Let them know my companion will be meeting them shortly.", null);
				}
			}

			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=qh1Ot0F9}They have {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}. They're asking {REQUESTED_PRICE}{GOLD_ICON}. You know that this is the best price you can find anywhere in this district.", null);
					textObject.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
					textObject.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
					textObject.SetTextVariable("REQUESTED_PRICE", this.StolenTradeGoodPrice);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					return new TextObject("{=babDRxdu}I am trying to help some friends. They want a buyer for some goods, that, well, let's say that my friends might not have paid for these goods. These lads are camped close by, but would prefer not to come into town. You see?[if:convo_mocking_aristocratic][ib:hip]", null);
				}
			}

			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=rMySUGLu}I am interested. What are they selling?", null);
				}
			}

			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=t1tNPPNf}I can go meet them and seal this deal myself.", null);
				}
			}

			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=ov0u6ahh}All right. It was a pleasure doing business with you.", null);
				}
			}

			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=A2JWExWL}I hope our respective friends come to an agreement.", null);
				}
			}

			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=izuhKnXy}Purchase stolen goods from {ISSUE_GIVER.NAME}", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=3WFgPigk}{ISSUE_GIVER.NAME} wants to sell you stolen goods. The price is low because of the added risk.", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=riKyIyaa}{QUEST_GIVER.LINK}, a gang leader from {QUEST_GIVER_SETTLEMENT}, has offered you to sell {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} for half the normal price, because they were stolen... {?QUEST_GIVER.GENDER}She{?}He{\\?} says they are hidden in a remote location. You asked your companion to go buy the goods.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
					textObject.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
					return textObject;
				}
			}

			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=XOB0SMXC}{COMPANION.LINK} has successfully offloaded the stolen goods. {?QUEST_GIVER.GENDER}She{?}He{\\?} returned to the party with {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}.", null);
					textObject.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, false);
					textObject.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, false);
					textObject.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
					textObject.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
					return textObject;
				}
			}

			protected override int CompanionSkillRewardXP
			{
				get
				{
					return 1000 + (int)(1250f * base.IssueDifficultyMultiplier);
				}
			}

			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return (int)(7f + 10f * base.IssueDifficultyMultiplier);
				}
			}

			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 10;
				}
			}

			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				List<SkillObject> alternativeSolutionMeleeSkills = QuestHelper.GetAlternativeSolutionMeleeSkills();
				alternativeSolutionMeleeSkills.Add(DefaultSkills.Roguery);
				alternativeSolutionMeleeSkills.Add(DefaultSkills.Tactics);
				return new ValueTuple<SkillObject, int>(alternativeSolutionMeleeSkills.MaxBy(new Func<SkillObject, int>(hero.GetSkillValue)), 120);
			}

			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				explanation = TextObject.Empty;
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2, false);
			}

			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this.RewardGold, false);
				this.RelationshipChangeWithIssueOwner = 10;
				base.IssueOwner.AddPower(5f);
				this.CounterOfferHero.AddPower(-5f);
				foreach (Hero hero in base.IssueOwner.CurrentSettlement.Notables.WhereQ((Hero notable) => notable.IsMerchant))
				{
					hero.AddPower(-3f);
				}
				MobileParty.MainParty.ItemRoster.AddToCounts(this.StolenTradeGood, this.StolenTradeGoodAmount);
				TraitLevelingHelper.OnIssueSolvedThroughAlternativeSolution(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Calculating, 50)
				});
			}

			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				explanation = TextObject.Empty;
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2, false);
			}

			public GangLeaderNeedsToOffloadStolenGoodsIssue(Hero issueOwner, Settlement hideout)
				: base(issueOwner, CampaignTime.DaysFromNow(15f))
			{
				this._randomForStolenTradeGood = MBRandom.RandomInt(0, GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue.PossibleStolenItems.Length);
				this._issueHideout = hideout;
			}

			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -1f;
				}
				if (issueEffect == DefaultIssueEffects.SettlementSecurity)
				{
					return 1f;
				}
				return 0f;
			}

			public override bool IssueStayAliveConditions()
			{
				return base.IssueOwner.CurrentSettlement.Town.Security < 90f && this.CounterOfferHero.IsActive && this.CounterOfferHero.CurrentSettlement == base.IssueSettlement && this._issueHideout != null && this._issueHideout.Hideout.IsInfested;
			}

			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			protected override void AfterIssueCreation()
			{
				this.CounterOfferHero = base.IssueOwner.CurrentSettlement.Notables.FirstOrDefault((Hero x) => x != base.IssueOwner && x.IsMerchant) ?? base.IssueOwner.CurrentSettlement.Notables.FirstOrDefault<Hero>();
			}

			protected override void OnGameLoad()
			{
				if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.0", 24202))
				{
					Campaign.Current.IssueManager.DeactivateIssue(this);
				}
			}

			protected override void HourlyTick()
			{
			}

			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(20f), this.StolenTradeGood, this._issueHideout, this.StolenTradeGoodPrice, this.RewardGold, this.StolenTradeGoodAmount, this.CounterOfferHero);
			}

			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.Common;
			}

			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill)
			{
				flag = IssueBase.PreconditionFlags.None;
				relationHero = null;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flag |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (issueGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				if (Clan.PlayerClan == issueGiver.CurrentSettlement.OwnerClan)
				{
					flag |= IssueBase.PreconditionFlags.PlayerIsOwnerOfSettlement;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			private const int QuestDurationInDays = 20;

			private static readonly string[] PossibleStolenItems = new string[] { "jewelry", "fur", "silver", "velvet" };

			[SaveableField(20)]
			private readonly int _randomForStolenTradeGood;

			[SaveableField(30)]
			private readonly Settlement _issueHideout;

			private const int AlternativeSolutionMinimumTroopLevel = 2;

			private const int CompanionRequiredSkillLevel = 120;
		}

		public class GangLeaderNeedsToOffloadStolenGoodsIssueQuest : QuestBase
		{
			internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsToOffloadStolenGoodsIssueQuest(object o, List<object> collectedObjects)
			{
				((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._stolenTradeGood);
				collectedObjects.Add(this._playerStartsQuestLog);
				collectedObjects.Add(this._counterOfferHero);
				collectedObjects.Add(this._questHideout);
			}

			internal static object AutoGeneratedGetMemberValue_stolenTradeGood(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._stolenTradeGood;
			}

			internal static object AutoGeneratedGetMemberValue_stolenTradeGoodAmount(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._stolenTradeGoodAmount;
			}

			internal static object AutoGeneratedGetMemberValue_stolenTradeGoodPrice(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._stolenTradeGoodPrice;
			}

			internal static object AutoGeneratedGetMemberValue_counterOfferGiven(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._counterOfferGiven;
			}

			internal static object AutoGeneratedGetMemberValue_counterOfferGold(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._counterOfferGold;
			}

			internal static object AutoGeneratedGetMemberValue_playerStartsQuestLog(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._playerStartsQuestLog;
			}

			internal static object AutoGeneratedGetMemberValue_counterOfferHero(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._counterOfferHero;
			}

			internal static object AutoGeneratedGetMemberValue_talkedWithBanditLeader(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._talkedWithBanditLeader;
			}

			internal static object AutoGeneratedGetMemberValue_isPayingForGoods(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._isPayingForGoods;
			}

			internal static object AutoGeneratedGetMemberValue_isFightingForGoods(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._isFightingForGoods;
			}

			internal static object AutoGeneratedGetMemberValue_questHideout(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._questHideout;
			}

			internal static object AutoGeneratedGetMemberValue_playerHasTheGoods(object o)
			{
				return ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest)o)._playerHasTheGoods;
			}

			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			private CharacterObject BanditLeader
			{
				get
				{
					return this._questHideout.Culture.BanditChief;
				}
			}

			private TextObject PlayerStartsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=uaYGZUDs}{QUEST_GIVER.LINK}, a gang leader from {QUEST_GIVER_SETTLEMENT}, has offered you to sell {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} for half the normal price, because they were stolen.. {?QUEST_GIVER.GENDER}She{?}He{\\?} says they are hidden in a remote location. You agreed to buy the goods.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
					textObject.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
					return textObject;
				}
			}

			private TextObject SuccessQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=mrNdB0Hh}You refused the {MERCHANT.LINK}'s request and kept the goods.", null);
					textObject.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject, false);
					return textObject;
				}
			}

			private TextObject SuccessByGivingBackTheGoodsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=jO9cGnCK}You bought the goods from the bandits and handed over them to the {MERCHANT.LINK}.", null);
					textObject.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject, false);
					return textObject;
				}
			}

			private TextObject FailBetrayQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=v1bkAxmK}You accepted {MERCHANT.LINK}'s request. You've handed over the goods.", null);
					textObject.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject, false);
					return textObject;
				}
			}

			private TextObject FailBetrayTakeGoodsQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=7q0vbVdN}You betrayed the gang leader and refused the {MERCHANT.LINK}'s request. The goods stayed with you.", null);
					textObject.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject, false);
					return textObject;
				}
			}

			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=AtHjW2lY}Purchase stolen goods from {QUEST_GIVER.NAME}", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			private TextObject FailLoseHideoutFightQuestLogText
			{
				get
				{
					return new TextObject("{=g7atkzxO}You failed to clear the hideout.", null);
				}
			}

			private TextObject FailTimeOutQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=JwNTcFLA}You failed to make the deal with {QUEST_GIVER.LINK}'s associates in time.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			public GangLeaderNeedsToOffloadStolenGoodsIssueQuest(string questId, Hero questGiver, CampaignTime duration, ItemObject stolenTradeGood, Settlement questHideout, int stolenTradeGoodPrice, int rewardGold, int stolenGoodAmount, Hero counterOfferHero)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._stolenTradeGood = stolenTradeGood;
				this._stolenTradeGoodPrice = stolenTradeGoodPrice;
				this._stolenTradeGoodAmount = stolenGoodAmount;
				this._counterOfferGold = MathF.Round((float)(questGiver.CurrentSettlement.Town.GetItemPrice(this._stolenTradeGood, null, false) * this._stolenTradeGoodAmount) * 0.4f);
				this._counterOfferHero = counterOfferHero;
				this._questHideout = questHideout;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
				this.AddGameMenuOptions();
			}

			private TextObject CancelSettlementOwnerChangedQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=0YwZsiT4}Your clan is now owner of the town from which the goods were stolen. As the lord of the settlement you cannot get involved in deals of this kind. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=iKYd8PQc}Excellent. I'll have the whereabouts of the goods delivered to you right away...[if:convo_nonchalant][ib:confident]", null), null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(new TextObject("{=RmjvSKVq}My colleagues are waiting for your arrival. They won't be happy waiting too long with so many valuables at hand.", null), null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.BeginPlayerOptions()
					.PlayerOption(new TextObject("{=D4CsJMLE}Don't worry, I'll get there soon enough.", null), null)
					.NpcLine(new TextObject("{=2D4EdZVK}All right, but if this falls through because you took too long, I won't be too happy with that.", null), null, null)
					.PlayerOption(new TextObject("{=ErKDfLWJ}I have more urgent business to handle. I will get there when I can.", null), null)
					.NpcLine(new TextObject("{=qLdchkGU}Yeah... Well, a lot can go wrong if you don't move on these things quickly.", null), null, null)
					.EndPlayerOptions()
					.CloseDialog();
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetCounterOfferDialogFlow(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetHideoutLeaderDialogFlow(), this);
				Campaign.Current.ConversationManager.AddDialogFlow(this.GetAfterHideoutMerchantDialogFlow(), this);
			}

			private TextObject BeforeAttackHideoutQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=sVL8Z0lg}You met {QUEST_GIVER.LINK}'s associates near their hideout and demanded they turn over the goods to you, refusing to pay. They refused, and your only option now is to attack the hideout under cover of darkness and take the goods by force.", null);
					textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
					return textObject;
				}
			}

			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				this._playerStartsQuestLog = base.AddLog(this.PlayerStartsQuestLogText, true);
				this._questHideout.Hideout.IsSpotted = true;
				this._questHideout.IsVisible = true;
				base.AddTrackedObject(this._questHideout);
			}

			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				this.AddGameMenuOptions();
			}

			protected override void HourlyTick()
			{
			}

			private DialogFlow GetCounterOfferDialogFlow()
			{
				TextObject textObject = new TextObject("{=WJPAWHM9}A moment of your time, {?PLAYER.GENDER}ma'am{?}sir{\\?}. I hear you've been talking with a well-known scoundrel named {QUEST_GIVER.LINK}. A while ago, a caravan of mine carrying some {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} was robbed. Now {?QUEST_GIVER.GENDER}she's{?}he's{\\?} going around offering to sell the exact same merchandise. The guards won't go beyond the walls to get it back, but you can. I will reward you, and you'll earn the gratitude of all law-abiding townsfolk.[if:convo_nonchalant][ib:normal2]", null);
				textObject.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, false);
				textObject.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
				textObject.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
				textObject.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null).Condition(() => this._counterOfferHero == Hero.OneToOneConversationHero && !this._talkedWithBanditLeader && !this._playerHasTheGoods)
					.BeginPlayerOptions()
					.PlayerOption(new TextObject("{=Fk9nVX8t}Yes... Well, I will see what I can do.", null), null)
					.NpcLine(new TextObject("{=WotPuijV}That's the right decision. Thank you.[if:convo_calm_friendly][ib:closed]", null), null, null)
					.CloseDialog()
					.PlayerOption(new TextObject("{=1fXYQ7XG}My deals are none of your business, merchant.", null), null)
					.NpcLine(new TextObject("{=u0pofzPq}Please reconsider. Whether you help me or not, I will make sure other merchants will hear of your decision.[if:convo_very_stern][ib:closed2]", null), null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			protected override void OnTimedOut()
			{
				base.AddLog(this.FailTimeOutQuestLogText, false);
			}

			private void AddGameMenuOptions()
			{
				TextObject textObject = new TextObject("{=wbSXI6iq}Approach to the meeting point", null);
				base.AddGameMenuOption("hideout_place", "talk_to_boss", textObject, new GameMenuOption.OnConditionDelegate(this.game_menu_approach_meeting_on_condition), new GameMenuOption.OnConsequenceDelegate(this.game_menu_approach_meeting_on_consequence), false, 2);
			}

			private DialogFlow GetHideoutLeaderDialogFlow()
			{
				TextObject banditBrief = new TextObject("{=!}{BANDIT_BRIEF}", null);
				TextObject banditFirstInteraction = new TextObject("{=2dWvwc0T}You must be the nice {?PLAYER.GENDER}lady{?}lord{\\?} who {QUEST_GIVER.NAME} has been telling us about. We have been expecting you. The goods are nearby. I will tell my friends to bring them out as soon as you pay up.", null);
				banditFirstInteraction.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, false);
				banditFirstInteraction.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, false);
				TextObject banditSecondInteraction = new TextObject("{=n17USCaH}Well well... Do you have our money yet?", null);
				TextObject textObject = new TextObject("{=hXmmofDN}Here are the denars. You can tell your friends to bring out the {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}.", null);
				textObject.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
				textObject.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
				TextObject textObject2 = new TextObject("{=Bvb0AmW7}Unfortunately, I do not have enough denars on me.", null);
				TextObject textObject3 = new TextObject("{=7kTipmjp}Then why are you here? We're not the sort who does business on credit. Come back when you have the money.", null);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(banditBrief, null, null).Condition(delegate
				{
					banditBrief.SetTextVariable("BANDIT_BRIEF", (!this._talkedWithBanditLeader) ? banditFirstInteraction : banditSecondInteraction);
					return this.BanditLeader == CharacterObject.OneToOneConversationCharacter && Game.Current.GameStateManager.ActiveState is MapState && Settlement.CurrentSettlement == this._questHideout;
				})
					.Consequence(delegate
					{
						this._talkedWithBanditLeader = true;
					})
					.NpcLine(banditSecondInteraction, null, null)
					.Condition(() => this.BanditLeader == CharacterObject.OneToOneConversationCharacter && this._talkedWithBanditLeader && Game.Current.GameStateManager.ActiveState is MapState)
					.BeginPlayerOptions()
					.PlayerOption(textObject, null)
					.ClickableCondition(delegate(out TextObject explanation)
					{
						bool flag = false;
						if (Hero.MainHero.Gold >= this._stolenTradeGoodPrice)
						{
							explanation = new TextObject("{=!}{GOLD_AMOUNT}{GOLD_ICON}", null);
							explanation.SetTextVariable("GOLD_AMOUNT", this._stolenTradeGoodPrice);
							flag = true;
						}
						else
						{
							explanation = new TextObject("{=YuLLsAUb}You don't have {GOLD_AMOUNT}{GOLD_ICON}.", null);
							explanation.SetTextVariable("GOLD_AMOUNT", this._stolenTradeGoodPrice);
						}
						return flag;
					})
					.NpcLine(new TextObject("{=21Y4tWE9}Good, good. All the best to you, friend.", null), null, null)
					.Consequence(delegate
					{
						GiveGoldAction.ApplyForQuestBetweenCharacters(Hero.MainHero, null, this._stolenTradeGoodPrice, false);
						this._isPayingForGoods = true;
						this._playerHasTheGoods = true;
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=H7FpMR0O}I'm not buying them from you, thief. Bring them out now.", null), null)
					.NpcLine(new TextObject("{=M8j6J8aN}Really? Very well, I'll send word to my lads that you intended to take our loot by force. They'll get things ready for you, have no fear. Just maybe not in the way you're hoping...", null), null, null)
					.Consequence(delegate
					{
						this.AddLog(this.BeforeAttackHideoutQuestLogText, false);
						this._isFightingForGoods = true;
					})
					.CloseDialog()
					.PlayerOption(textObject2, null)
					.Condition(() => Hero.MainHero.Gold < this._stolenTradeGoodPrice)
					.NpcLine(textObject3, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			private DialogFlow GetAfterHideoutMerchantDialogFlow()
			{
				TextObject textObject = new TextObject("{=8nq0TbMZ}{?PLAYER.GENDER}Ma'am{?}Sir{\\?}! I saw your party from a distance. I hope you don't mind me catching up to you. I am glad to see you safe - and, from the looks of it, in possession of some fine new goods. Please tell me, would they be mine?", null);
				textObject.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, false);
				TextObject textObject2 = new TextObject("{=Utq4svjd}Splendid. I will be sure that everyone in {MERCHANT_TOWN} hears of your honesty.", null);
				textObject2.SetTextVariable("MERCHANT_TOWN", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
				TextObject textObject3 = new TextObject("{=dtghhz46}Well... You have swords. You can do what you like. Just don't expect anyone in {MERCHANT_TOWN} to think well of you. Good day, {?PLAYER.GENDER}ma'am{?}sir{\\?}.", null);
				textObject3.SetTextVariable("MERCHANT_TOWN", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null).Condition(() => Settlement.CurrentSettlement == this._questHideout && this._counterOfferHero == Hero.OneToOneConversationHero)
					.BeginPlayerOptions()
					.PlayerOption(new TextObject("{=peUxzLsY}\"Your\" goods? These are my goods now.", null), null)
					.NpcLine(textObject3, null, null)
					.Consequence(delegate
					{
						if (this._isPayingForGoods)
						{
							this.SucceedQuestByPayingAndKeepingTheGoods();
							return;
						}
						this.FailQuestByKeepingTheGoods();
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=1lOSJ29M}Yes, they are here. Tell your men to come pick them up.", null), null)
					.NpcLine(textObject2, null, null)
					.Consequence(delegate
					{
						if (this._isPayingForGoods)
						{
							this.SucceedQuestByPayingAndGivingTheGoodsBack();
							return;
						}
						this.FailQuestByGivingBackTheGoods();
					})
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			private void SucceedQuestByPayingAndKeepingTheGoods()
			{
				base.AddLog(this.SuccessQuestLogText, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Calculating, 100)
				});
				MobileParty.MainParty.ItemRoster.AddToCounts(this._stolenTradeGood, this._stolenTradeGoodAmount);
				base.QuestGiver.AddPower(5f);
				this._counterOfferHero.AddPower(-5f);
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, 10, true, true);
				foreach (Hero hero in base.QuestGiver.CurrentSettlement.Notables.WhereQ((Hero notable) => notable.IsMerchant))
				{
					ChangeRelationAction.ApplyPlayerRelation(hero, -3, true, true);
				}
				base.CompleteQuestWithSuccess();
			}

			private void SucceedQuestByPayingAndGivingTheGoodsBack()
			{
				base.AddLog(this.SuccessByGivingBackTheGoodsQuestLogText, false);
				GiveGoldAction.ApplyForQuestBetweenCharacters(this._counterOfferHero, Hero.MainHero, this._counterOfferGold, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Calculating, 150)
				});
				base.QuestGiver.AddPower(5f);
				this._counterOfferHero.AddPower(5f);
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, 10, true, true);
				foreach (Hero hero in base.QuestGiver.CurrentSettlement.Notables.WhereQ((Hero notable) => notable != base.QuestGiver))
				{
					ChangeRelationAction.ApplyPlayerRelation(hero, 3, true, true);
				}
				base.CompleteQuestWithSuccess();
			}

			private void FailQuestByKeepingTheGoods()
			{
				base.QuestGiver.AddPower(-5f);
				this._counterOfferHero.AddPower(-5f);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Calculating, 100)
				});
				MobileParty.MainParty.ItemRoster.AddToCounts(this._stolenTradeGood, this._stolenTradeGoodAmount);
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, -5, true, true);
				foreach (Hero hero in base.QuestGiver.CurrentSettlement.Notables.WhereQ((Hero notable) => notable.IsMerchant))
				{
					ChangeRelationAction.ApplyPlayerRelation(hero, -3, true, true);
				}
				base.CompleteQuestWithBetrayal(this.FailBetrayTakeGoodsQuestLogText);
			}

			private void FailQuestByGivingBackTheGoods()
			{
				GiveGoldAction.ApplyForQuestBetweenCharacters(this._counterOfferHero, Hero.MainHero, this._counterOfferGold, false);
				base.QuestGiver.AddPower(-5f);
				this._counterOfferHero.AddPower(5f);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 100)
				});
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, -5, true, true);
				foreach (Hero hero in base.QuestGiver.CurrentSettlement.Notables.WhereQ((Hero notable) => notable != base.QuestGiver))
				{
					ChangeRelationAction.ApplyPlayerRelation(hero, 3, true, true);
				}
				base.CompleteQuestWithBetrayal(this.FailBetrayQuestLogText);
			}

			private void FailQuestByLosingHideoutBattle()
			{
				base.QuestGiver.AddPower(-5f);
				this._counterOfferHero.AddPower(-5f);
				ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver, -5, true, true);
				base.CompleteQuestWithFail(this.FailLoseHideoutFightQuestLogText);
			}

			protected override void RegisterEvents()
			{
				CampaignEvents.GameMenuOpened.AddNonSerializedListener(this, new Action<MenuCallbackArgs>(this.GameMenuOpened));
				CampaignEvents.OnSettlementLeftEvent.AddNonSerializedListener(this, new Action<MobileParty, Settlement>(this.OnSettlementLeft));
				CampaignEvents.OnHideoutBattleCompletedEvent.AddNonSerializedListener(this, new Action<BattleSideEnum, HideoutEventComponent>(this.OnHideoutBattleCompleted));
				CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener(this, new Action<Settlement, bool, Hero, Hero, Hero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail>(this.OnSettlementOwnerChanged));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (mapEvent.MapEventSettlement == this._questHideout && attackerParty == PartyBase.MainParty)
				{
					this._isFightingForGoods = true;
				}
			}

			private void OnSettlementOwnerChanged(Settlement settlement, bool openToClaim, Hero newOwner, Hero oldOwner, Hero capturerHero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
			{
				if (settlement == base.QuestGiver.CurrentSettlement && newOwner == Hero.MainHero)
				{
					base.CompleteQuestWithCancel(this.CancelSettlementOwnerChangedQuestLogText);
				}
			}

			private void OnHideoutBattleCompleted(BattleSideEnum winnerSide, HideoutEventComponent hideoutEventComponent)
			{
				if (hideoutEventComponent.MapEvent.PlayerSide != winnerSide)
				{
					this.FailQuestByLosingHideoutBattle();
					return;
				}
				if (hideoutEventComponent.MapEvent.MapEventSettlement == this._questHideout)
				{
					this._playerHasTheGoods = true;
					TextObject textObject = new TextObject("{=9bFAsGmp}You have cleared the hideout. Your men found the {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} stashed nearby.", null);
					textObject.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
					textObject.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
					MBInformationManager.AddQuickInformation(textObject, 0, null, "");
				}
			}

			private void GameMenuOpened(MenuCallbackArgs args)
			{
				if (Settlement.CurrentSettlement == this._questHideout && !this._isFightingForGoods)
				{
					GameTexts.SetVariable("HIDEOUT_DESCRIPTION", "{=b14v853a}As you approach the gang's camp, you can see a single man out in the open waiting for you, pacing and kicking stones around.");
				}
			}

			private void OnSettlementLeft(MobileParty party, Settlement settlement)
			{
				if (party == MobileParty.MainParty)
				{
					if (settlement == this._questHideout)
					{
						if (this._playerHasTheGoods)
						{
							CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, null, false, false, false, false, false, false), new ConversationCharacterData(this._counterOfferHero.CharacterObject, null, false, false, false, false, false, false));
							return;
						}
					}
					else if (settlement == this._counterOfferHero.CurrentSettlement && !this._counterOfferGiven)
					{
						CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, null, false, false, false, false, false, false), new ConversationCharacterData(this._counterOfferHero.CharacterObject, null, false, false, false, false, false, false));
						this._counterOfferGiven = true;
					}
				}
			}

			private void game_menu_approach_meeting_on_consequence(MenuCallbackArgs args)
			{
				CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, null, false, false, false, false, false, false), new ConversationCharacterData(this.BanditLeader, null, false, false, false, false, false, false));
			}

			private bool game_menu_approach_meeting_on_condition(MenuCallbackArgs args)
			{
				args.optionLeaveType = GameMenuOption.LeaveType.Conversation;
				args.OptionQuestData = GameMenuOption.IssueQuestFlags.ActiveIssue;
				return Settlement.CurrentSettlement == this._questHideout && !this._isFightingForGoods && !this._isPayingForGoods;
			}

			public override void OnHeroCanHaveQuestOrIssueInfoIsRequested(Hero hero, ref bool result)
			{
				if (hero == this._counterOfferHero)
				{
					result = false;
				}
			}

			[SaveableField(105)]
			private readonly ItemObject _stolenTradeGood;

			[SaveableField(106)]
			private readonly int _stolenTradeGoodAmount;

			[SaveableField(107)]
			private readonly int _stolenTradeGoodPrice;

			[SaveableField(109)]
			private bool _counterOfferGiven;

			[SaveableField(111)]
			private readonly int _counterOfferGold;

			[SaveableField(112)]
			private JournalLog _playerStartsQuestLog;

			[SaveableField(113)]
			private readonly Hero _counterOfferHero;

			[SaveableField(114)]
			private bool _talkedWithBanditLeader;

			[SaveableField(115)]
			private bool _isPayingForGoods;

			[SaveableField(116)]
			private bool _isFightingForGoods;

			[SaveableField(117)]
			private readonly Settlement _questHideout;

			[SaveableField(118)]
			private bool _playerHasTheGoods;
		}

		public class GangLeaderNeedsToOffloadStolenGoodsIssueTypeDefiner : SaveableTypeDefiner
		{
			public GangLeaderNeedsToOffloadStolenGoodsIssueTypeDefiner()
				: base(460000)
			{
			}

			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue), 1, null);
				base.AddClassDefinition(typeof(GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest), 2, null);
			}
		}
	}
}
