using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x02000311 RID: 785
	public class LandLordNeedsManualLaborersIssueBehavior : CampaignBehaviorBase
	{
		// Token: 0x06002CF6 RID: 11510 RVA: 0x000BBABC File Offset: 0x000B9CBC
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		// Token: 0x06002CF7 RID: 11511 RVA: 0x000BBAD5 File Offset: 0x000B9CD5
		public override void SyncData(IDataStore dataStore)
		{
		}

		// Token: 0x06002CF8 RID: 11512 RVA: 0x000BBAD8 File Offset: 0x000B9CD8
		private bool ConditionsHold(Hero issueGiver)
		{
			if (issueGiver.CurrentSettlement != null && issueGiver.IsRuralNotable && issueGiver.GetTraitLevel(DefaultTraits.Mercy) <= 0)
			{
				Village village = issueGiver.CurrentSettlement.Village;
				return village != null && (village.VillageType == DefaultVillageTypes.IronMine || village.VillageType == DefaultVillageTypes.ClayMine || village.VillageType == DefaultVillageTypes.SaltMine || village.VillageType == DefaultVillageTypes.SilverMine);
			}
			return false;
		}

		// Token: 0x06002CF9 RID: 11513 RVA: 0x000BBB4C File Offset: 0x000B9D4C
		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		// Token: 0x06002CFA RID: 11514 RVA: 0x000BBBB0 File Offset: 0x000B9DB0
		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue(issueOwner);
		}

		// Token: 0x04000D8F RID: 3471
		private const IssueBase.IssueFrequency NeedsLaborersIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		// Token: 0x02000636 RID: 1590
		public class LandLordNeedsManualLaborersIssue : IssueBase
		{
			// Token: 0x06004C3D RID: 19517 RVA: 0x00153444 File Offset: 0x00151644
			internal static void AutoGeneratedStaticCollectObjectsLandLordNeedsManualLaborersIssue(object o, List<object> collectedObjects)
			{
				((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06004C3E RID: 19518 RVA: 0x00153452 File Offset: 0x00151652
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x17000FF2 RID: 4082
			// (get) Token: 0x06004C3F RID: 19519 RVA: 0x0015345B File Offset: 0x0015165B
			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.RequiredTroops;
				}
			}

			// Token: 0x17000FF3 RID: 4083
			// (get) Token: 0x06004C40 RID: 19520 RVA: 0x0015345E File Offset: 0x0015165E
			private int RequestedPrisonerCount
			{
				get
				{
					return 6 + MathF.Ceiling(30f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000FF4 RID: 4084
			// (get) Token: 0x06004C41 RID: 19521 RVA: 0x00153473 File Offset: 0x00151673
			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 8 + MathF.Ceiling(12f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000FF5 RID: 4085
			// (get) Token: 0x06004C42 RID: 19522 RVA: 0x00153488 File Offset: 0x00151688
			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 5 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x17000FF6 RID: 4086
			// (get) Token: 0x06004C43 RID: 19523 RVA: 0x0015349D File Offset: 0x0015169D
			protected override int RewardGold
			{
				get
				{
					return this.RequestedPrisonerCount * 50;
				}
			}

			// Token: 0x17000FF7 RID: 4087
			// (get) Token: 0x06004C44 RID: 19524 RVA: 0x001534A8 File Offset: 0x001516A8
			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject;
					if (base.IssueOwner.CharacterObject.GetTraitLevel(DefaultTraits.Mercy) < 0)
					{
						textObject = new TextObject("{=QEhapwtN}I own a mine near here. Normally I can find willing villagers to work it, but these days they've been demanding higher and higher wages. Fine. They're out of a job, but I still need to work the mine. If you could perhaps find me some prisoners...", null);
					}
					else
					{
						textObject = new TextObject("{=1LFcSRPw}I have a mine near here. We had an unfortunate accident a week back. Two workers were crushed to death. It's a great shame... but work must go on. Trouble is, no one wants to come back. If perhaps you could find me some prisoners...", null);
					}
					return textObject;
				}
			}

			// Token: 0x17000FF8 RID: 4088
			// (get) Token: 0x06004C45 RID: 19525 RVA: 0x001534E8 File Offset: 0x001516E8
			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=DSMMIrz9}Prisoners... You want criminals or war captives?", null);
				}
			}

			// Token: 0x17000FF9 RID: 4089
			// (get) Token: 0x06004C46 RID: 19526 RVA: 0x001534F5 File Offset: 0x001516F5
			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=ji5kkqXy}They need to be criminals, bandits, for me to do this legally. I need at least {WANTED_PRISONER_AMOUNT} of them. But if you can bring more I will gladly accept. I'm willing to pay ten times more than their market price for each. What do you say?", null);
					textObject.SetTextVariable("WANTED_PRISONER_AMOUNT", this.RequestedPrisonerCount);
					return textObject;
				}
			}

			// Token: 0x17000FFA RID: 4090
			// (get) Token: 0x06004C47 RID: 19527 RVA: 0x00153514 File Offset: 0x00151714
			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=WpidwcAV}If you have a companion who understands this type of work and {ALTERNATIVE_TROOP_AMOUNT} men, I can tell them where to go to get their hands on some prisoners.", null);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					return textObject;
				}
			}

			// Token: 0x17000FFB RID: 4091
			// (get) Token: 0x06004C48 RID: 19528 RVA: 0x00153533 File Offset: 0x00151733
			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=C06TxxnM}I'll bring you at least {WANTED_PRISONER_AMOUNT} prisoners as soon as possible.", null);
					textObject.SetTextVariable("WANTED_PRISONER_AMOUNT", this.RequestedPrisonerCount);
					return textObject;
				}
			}

			// Token: 0x17000FFC RID: 4092
			// (get) Token: 0x06004C49 RID: 19529 RVA: 0x00153552 File Offset: 0x00151752
			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					return new TextObject("{=QH3shVzb}My people can bring you your laborers.", null);
				}
			}

			// Token: 0x17000FFD RID: 4093
			// (get) Token: 0x06004C4A RID: 19530 RVA: 0x0015355F File Offset: 0x0015175F
			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=XXOlu6z0}Thank you for sparing some of your men to save my business. I am looking forward to resuming work.", null);
				}
			}

			// Token: 0x17000FFE RID: 4094
			// (get) Token: 0x06004C4B RID: 19531 RVA: 0x0015356C File Offset: 0x0015176C
			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=PrzguaEq}Thank you. I appreciate your people's help.", null);
				}
			}

			// Token: 0x17000FFF RID: 4095
			// (get) Token: 0x06004C4C RID: 19532 RVA: 0x00153579 File Offset: 0x00151779
			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			// Token: 0x17001000 RID: 4096
			// (get) Token: 0x06004C4D RID: 19533 RVA: 0x0015357C File Offset: 0x0015177C
			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001001 RID: 4097
			// (get) Token: 0x06004C4E RID: 19534 RVA: 0x00153580 File Offset: 0x00151780
			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=MYeCnHTb}You asked {COMPANION.LINK} to deliver at least {WANTED_PRISONER_AMOUNT} prisoners to {ISSUE_GIVER.LINK} in {SETTLEMENT}. They should rejoin your party in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("WANTED_PRISONER_AMOUNT", this.RequestedPrisonerCount);
					textObject.SetTextVariable("SETTLEMENT", base.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			// Token: 0x17001002 RID: 4098
			// (get) Token: 0x06004C4F RID: 19535 RVA: 0x0015360A File Offset: 0x0015180A
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=hVIsGd2y}Landowner Needs Manual Laborers", null);
				}
			}

			// Token: 0x17001003 RID: 4099
			// (get) Token: 0x06004C50 RID: 19536 RVA: 0x00153617 File Offset: 0x00151817
			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=5of4a1kg}A landowner needs your help to find prisoners to use in {?ISSUE_GIVER.GENDER}her{?}his{\\?} mines as manual laborers.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, null, false);
					return textObject;
				}
			}

			// Token: 0x06004C51 RID: 19537 RVA: 0x0015363C File Offset: 0x0015183C
			public LandLordNeedsManualLaborersIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
			}

			// Token: 0x06004C52 RID: 19538 RVA: 0x0015364F File Offset: 0x0015184F
			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.3f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			// Token: 0x06004C53 RID: 19539 RVA: 0x00153672 File Offset: 0x00151872
			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Athletics) >= hero.GetSkillValue(DefaultSkills.Leadership)) ? DefaultSkills.Athletics : DefaultSkills.Leadership, 120);
			}

			// Token: 0x06004C54 RID: 19540 RVA: 0x0015369F File Offset: 0x0015189F
			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				explanation = TextObject.Empty;
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2, false);
			}

			// Token: 0x06004C55 RID: 19541 RVA: 0x001536B7 File Offset: 0x001518B7
			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				explanation = TextObject.Empty;
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2, false);
			}

			// Token: 0x06004C56 RID: 19542 RVA: 0x001536D8 File Offset: 0x001518D8
			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2;
			}

			// Token: 0x06004C57 RID: 19543 RVA: 0x001536E6 File Offset: 0x001518E6
			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			// Token: 0x06004C58 RID: 19544 RVA: 0x001536E9 File Offset: 0x001518E9
			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid;
			}

			// Token: 0x06004C59 RID: 19545 RVA: 0x00153714 File Offset: 0x00151914
			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			// Token: 0x06004C5A RID: 19546 RVA: 0x00153764 File Offset: 0x00151964
			protected override void OnGameLoad()
			{
			}

			// Token: 0x06004C5B RID: 19547 RVA: 0x00153766 File Offset: 0x00151966
			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(20f), this.RequestedPrisonerCount);
			}

			// Token: 0x06004C5C RID: 19548 RVA: 0x00153784 File Offset: 0x00151984
			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			// Token: 0x17001004 RID: 4100
			// (get) Token: 0x06004C5D RID: 19549 RVA: 0x00153786 File Offset: 0x00151986
			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			// Token: 0x06004C5E RID: 19550 RVA: 0x0015379B File Offset: 0x0015199B
			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.IssueOwner, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
				});
				base.IssueOwner.AddPower(10f);
				this.RelationshipChangeWithIssueOwner = 5;
			}

			// Token: 0x040019FA RID: 6650
			private const int IssueDuration = 30;

			// Token: 0x040019FB RID: 6651
			private const int QuestDuration = 20;

			// Token: 0x040019FC RID: 6652
			private const int AlternativeSolutionTroopTierRequirement = 2;

			// Token: 0x040019FD RID: 6653
			private const int CompanionRequiredSkillLevel = 120;
		}

		// Token: 0x02000637 RID: 1591
		public class LandLordNeedsManualLaborersIssueQuest : QuestBase
		{
			// Token: 0x06004C5F RID: 19551 RVA: 0x001537D4 File Offset: 0x001519D4
			internal static void AutoGeneratedStaticCollectObjectsLandLordNeedsManualLaborersIssueQuest(object o, List<object> collectedObjects)
			{
				((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			// Token: 0x06004C60 RID: 19552 RVA: 0x001537E2 File Offset: 0x001519E2
			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._questProgressLogTest);
			}

			// Token: 0x06004C61 RID: 19553 RVA: 0x001537F7 File Offset: 0x001519F7
			internal static object AutoGeneratedGetMemberValue_requestedPrisonerCount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._requestedPrisonerCount;
			}

			// Token: 0x06004C62 RID: 19554 RVA: 0x00153809 File Offset: 0x00151A09
			internal static object AutoGeneratedGetMemberValue_shareProfit(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._shareProfit;
			}

			// Token: 0x06004C63 RID: 19555 RVA: 0x0015381B File Offset: 0x00151A1B
			internal static object AutoGeneratedGetMemberValue_counterOfferGiven(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._counterOfferGiven;
			}

			// Token: 0x06004C64 RID: 19556 RVA: 0x0015382D File Offset: 0x00151A2D
			internal static object AutoGeneratedGetMemberValue_deliveredPrisonerCount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._deliveredPrisonerCount;
			}

			// Token: 0x06004C65 RID: 19557 RVA: 0x0015383F File Offset: 0x00151A3F
			internal static object AutoGeneratedGetMemberValue_rewardGold(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._rewardGold;
			}

			// Token: 0x06004C66 RID: 19558 RVA: 0x00153851 File Offset: 0x00151A51
			internal static object AutoGeneratedGetMemberValue_maximumPrisonerCount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._maximumPrisonerCount;
			}

			// Token: 0x06004C67 RID: 19559 RVA: 0x00153863 File Offset: 0x00151A63
			internal static object AutoGeneratedGetMemberValue_playerReachedMaximumAmount(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._playerReachedMaximumAmount;
			}

			// Token: 0x06004C68 RID: 19560 RVA: 0x00153875 File Offset: 0x00151A75
			internal static object AutoGeneratedGetMemberValue_questProgressLogTest(object o)
			{
				return ((LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest)o)._questProgressLogTest;
			}

			// Token: 0x17001005 RID: 4101
			// (get) Token: 0x06004C69 RID: 19561 RVA: 0x00153882 File Offset: 0x00151A82
			public override TextObject Title
			{
				get
				{
					return new TextObject("{=hVIsGd2y}Landowner Needs Manual Laborers", null);
				}
			}

			// Token: 0x17001006 RID: 4102
			// (get) Token: 0x06004C6A RID: 19562 RVA: 0x0015388F File Offset: 0x00151A8F
			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			// Token: 0x17001007 RID: 4103
			// (get) Token: 0x06004C6B RID: 19563 RVA: 0x00153894 File Offset: 0x00151A94
			private bool IsQuestWithCounterOffer
			{
				get
				{
					if (base.QuestGiver.CharacterObject.GetTraitLevel(DefaultTraits.Mercy) < 0)
					{
						return base.QuestGiver.CurrentSettlement.Notables.FirstOrDefault((Hero x) => x.IsHeadman) != null;
					}
					return false;
				}
			}

			// Token: 0x17001008 RID: 4104
			// (get) Token: 0x06004C6C RID: 19564 RVA: 0x001538F4 File Offset: 0x00151AF4
			private TextObject QuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=7XR4MJci}{QUEST_GIVER.LINK}, a landowner in {SETTLEMENT}, told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs prisoners to use in {?QUEST_GIVER.GENDER}her{?}his{\\?} mines as manual laborers. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring at least {NEEDED_PRISONER_AMOUNT} bandit prisoners, but {?QUEST_GIVER.GENDER}she{?}he{\\?} will pay extra if you bring more. You have agreed to bring {?QUEST_GIVER.GENDER}her{?}him{\\?} at least {NEEDED_PRISONER_AMOUNT} bandit prisoner and you will be paid ten times more than their market price for each prisoner you bring.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("NEEDED_PRISONER_AMOUNT", this._requestedPrisonerCount);
					return textObject;
				}
			}

			// Token: 0x17001009 RID: 4105
			// (get) Token: 0x06004C6D RID: 19565 RVA: 0x00153954 File Offset: 0x00151B54
			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700100A RID: 4106
			// (get) Token: 0x06004C6E RID: 19566 RVA: 0x00153988 File Offset: 0x00151B88
			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700100B RID: 4107
			// (get) Token: 0x06004C6F RID: 19567 RVA: 0x001539BC File Offset: 0x00151BBC
			private TextObject QuestGiverVillageRaided
			{
				get
				{
					TextObject textObject = new TextObject("{=gJG0xmAq}{QUEST_GIVER.LINK}'s village {QUEST_SETTLEMENT} was raided. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			// Token: 0x1700100C RID: 4108
			// (get) Token: 0x06004C70 RID: 19568 RVA: 0x00153A0C File Offset: 0x00151C0C
			private TextObject QuestSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=ucu9u1nS}You delivered the prisoners to {QUEST_GIVER.LINK} as promised.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700100D RID: 4109
			// (get) Token: 0x06004C71 RID: 19569 RVA: 0x00153A3E File Offset: 0x00151C3E
			private TextObject PlayerSharedTheProfitWithHeadManLogText
			{
				get
				{
					return new TextObject("{=ULpP07bg}You promised to share half of the profit with the headman and the villager.", null);
				}
			}

			// Token: 0x1700100E RID: 4110
			// (get) Token: 0x06004C72 RID: 19570 RVA: 0x00153A4C File Offset: 0x00151C4C
			private TextObject QuestSuccessWithProfitShareLog
			{
				get
				{
					TextObject textObject = new TextObject("{=SyuxD1aY}You delivered the prisoners to {QUEST_GIVER.LINK} as promised and you shared half of the profit with the headman and the villagers.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x1700100F RID: 4111
			// (get) Token: 0x06004C73 RID: 19571 RVA: 0x00153A80 File Offset: 0x00151C80
			private TextObject QuestFailPlayerAcceptedCounterOfferLog
			{
				get
				{
					TextObject textObject = new TextObject("{=u8DJ8a2D}You agreed with the headman to break your agreement with {QUEST_GIVER.LINK}. By doing so you protected the villagers' jobs and now they are grateful to you.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x17001010 RID: 4112
			// (get) Token: 0x06004C74 RID: 19572 RVA: 0x00153AB4 File Offset: 0x00151CB4
			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=b1lsZNxE}You failed to deliver enough prisoners in time. {QUEST_GIVER.LINK} must be disappointed.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			// Token: 0x06004C75 RID: 19573 RVA: 0x00153AE8 File Offset: 0x00151CE8
			public LandLordNeedsManualLaborersIssueQuest(string questId, Hero giverHero, CampaignTime duration, int requestedPrisonerCount)
				: base(questId, giverHero, duration, 0)
			{
				this._requestedPrisonerCount = requestedPrisonerCount;
				this._shareProfit = false;
				this._deliveredPrisonerCount = 0;
				this._rewardGold = 0;
				this._counterOfferGiven = false;
				this._maximumPrisonerCount = MBRandom.RandomInt(40, 60);
				this._playerReachedMaximumAmount = false;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			// Token: 0x06004C76 RID: 19574 RVA: 0x00153B48 File Offset: 0x00151D48
			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddTrackedObject(base.QuestGiver.CurrentSettlement);
				TextObject textObject = new TextObject("{=N4eLGduQ}Delivered Prisoners ({TOTAL_REWARD}{GOLD_ICON})", null);
				textObject.SetTextVariable("TOTAL_REWARD", this._rewardGold);
				textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				this._questProgressLogTest = base.AddDiscreteLog(this.QuestStartedLogText, textObject, this._deliveredPrisonerCount, this._requestedPrisonerCount, null, false);
			}

			// Token: 0x06004C77 RID: 19575 RVA: 0x00153BBC File Offset: 0x00151DBC
			private DialogFlow GetCounterOfferDialogFlow()
			{
				TextObject textObject = new TextObject("{=aJHMafam}{?PLAYER.GENDER}Madam{?}Sir{\\?} - a moment of your time! You're on a job for {ISSUE_GIVER.LINK}, am I right? Look - our people are depending on those jobs. {?ISSUE_GIVER.GENDER}She{?}He{\\?} doesn't need to pay us a living wage if {?ISSUE_GIVER.GENDER}she{?}he{\\?} can do the work with prisoners. Please - break your agreement. You don't have to do this.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
				StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.QuestGiver.CharacterObject, textObject, false);
				TextObject textObject2 = new TextObject("{=8BdJ2MZj}I don't want to hurt your people. I'll forget my deal with {ISSUE_GIVER.LINK}.", null);
				StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject, null, null).Condition(delegate
				{
					if (!this._counterOfferGiven && Hero.OneToOneConversationHero != null)
					{
						return Hero.OneToOneConversationHero == base.QuestGiver.CurrentSettlement.Notables.FirstOrDefault((Hero x) => x.IsHeadman);
					}
					return false;
				})
					.Consequence(delegate
					{
						this._counterOfferGiven = true;
					})
					.BeginPlayerOptions()
					.PlayerOption("{=rOWyAHPo}Mind your own business, Headman.", null)
					.NpcLine("{=tLapkQqg}We won't forget this!", null, null)
					.Consequence(delegate
					{
						ChangeRelationAction.ApplyPlayerRelation(Hero.OneToOneConversationHero, -3, true, true);
					})
					.CloseDialog()
					.PlayerOption("{=I3GUAb9a}I understand your concern, Headman, but I made an agreement. How about I share the profit with you and your people?", null)
					.NpcLine("{=MmQt0TD3}This is not we want, but it's more than nothing. ", null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.ShareTheProfit))
					.CloseDialog()
					.PlayerOption(textObject2, null)
					.NpcLine("{=E5yAFR6y}Good to hear that. Thank you.", null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestFailPlayerAcceptedCounterOffer))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
			}

			// Token: 0x06004C78 RID: 19576 RVA: 0x00153CFE File Offset: 0x00151EFE
			private void ShareTheProfit()
			{
				base.AddLog(this.PlayerSharedTheProfitWithHeadManLogText, false);
				ChangeRelationAction.ApplyPlayerRelation(Hero.OneToOneConversationHero, 3, true, true);
				this._shareProfit = true;
			}

			// Token: 0x06004C79 RID: 19577 RVA: 0x00153D24 File Offset: 0x00151F24
			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=l7dL6arZ}Thank you. Remember - they need to be looters or bandits. Anyone else I can't put to work.", null), null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog();
				TextObject npcDiscussLine = new TextObject("{=!}{MANUAL_LABORERS_QUEST_NOTABLE_DISCUSS}", null);
				TextObject npcResponseLine = new TextObject("{=!}{MANUAL_LABORERS_QUEST_NOTABLE_RESPONSE}", null);
				bool changeDialogAfterTransfer = false;
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).BeginNpcOptions().NpcOption(new TextObject("{=VRLbAaYe}Thank you for saving my business {?PLAYER.GENDER}madam{?}sir{\\?}. Here is your payment.", null), () => Hero.OneToOneConversationHero == this.QuestGiver && this._playerReachedMaximumAmount, null, null)
					.Consequence(delegate
					{
						this.ApplyQuestSuccessConsequences();
						this.CompleteQuestWithSuccess();
					})
					.CloseDialog()
					.NpcOption(npcDiscussLine, delegate
					{
						if (Hero.OneToOneConversationHero != this.QuestGiver)
						{
							return false;
						}
						if (!changeDialogAfterTransfer)
						{
							npcDiscussLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_DISCUSS", new TextObject("{=B0YOpGsZ}Any news about my prisoners?", null));
						}
						else
						{
							npcDiscussLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_DISCUSS", new TextObject("{=ds294zxi}Anything else?", null));
							changeDialogAfterTransfer = false;
						}
						return true;
					}, null, null)
					.BeginPlayerOptions()
					.PlayerOption(new TextObject("{=QbaOoilS}Yes, I have brought you a few men.", null), null)
					.Condition(() => this.CheckIfThereIsSuitablePrisonerInPlayer() && !this._playerReachedMaximumAmount)
					.NpcLine(npcResponseLine, null, null)
					.Condition(delegate
					{
						if (this._playerReachedMaximumAmount)
						{
							return false;
						}
						if ((float)this._deliveredPrisonerCount < (float)this._maximumPrisonerCount * 0.75f)
						{
							npcResponseLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_RESPONSE", new TextObject("{=0ewaZnfe}Very good. Keep them coming.", null));
						}
						else
						{
							TextObject textObject = new TextObject("{=CBBPWMZd}Thanks to you, my mines are full {?PLAYER.GENDER}madam{?}sir{\\?}. I will only buy {X} more then we're done.", null);
							textObject.SetTextVariable("X", this._maximumPrisonerCount - this._deliveredPrisonerCount);
							npcResponseLine.SetTextVariable("MANUAL_LABORERS_QUEST_NOTABLE_RESPONSE", textObject);
							changeDialogAfterTransfer = false;
						}
						return true;
					})
					.PlayerLine(new TextObject("{=IULW8h03}Sure.", null), null)
					.Consequence(delegate
					{
						changeDialogAfterTransfer = true;
						this.OpenPrisonerDeliveryScreen();
					})
					.NpcLine(new TextObject("{=!}Party screen goes here.", null), null, null)
					.GotoDialogState("quest_discuss")
					.PlayerOption(new TextObject("{=UOE7ejgq}Here is all I've got. Let's settle up and finish this business.", null), null)
					.Condition(() => !this._playerReachedMaximumAmount && this._deliveredPrisonerCount >= this._requestedPrisonerCount)
					.NpcLine(new TextObject("{=YZ6UmX5o}Certainly. Here is your payment as I promised. Thank you.", null), null, null)
					.Consequence(delegate
					{
						this.ApplyQuestSuccessConsequences();
						this.CompleteQuestWithSuccess();
					})
					.CloseDialog()
					.PlayerOption(new TextObject("{=wErSpkjy}I'm still working on it.", null), null)
					.NpcLine(new TextObject("{=L1JyetPq}I am glad to hear that.", null), null, null)
					.CloseDialog()
					.EndPlayerOptions();
				if (this.IsQuestWithCounterOffer)
				{
					this.QuestCharacterDialogFlow = this.GetCounterOfferDialogFlow();
				}
			}

			// Token: 0x06004C7A RID: 19578 RVA: 0x00153F24 File Offset: 0x00152124
			private void OpenPrisonerDeliveryScreen()
			{
				PartyScreenManager.OpenScreenWithCondition(new IsTroopTransferableDelegate(this.IsTroopTransferable), new PartyPresentationDoneButtonConditionDelegate(this.DoneButtonCondition), new PartyPresentationDoneButtonDelegate(this.OnDoneClicked), new PartyPresentationCancelButtonDelegate(this.OnCancelClicked), PartyScreenLogic.TransferState.NotTransferable, PartyScreenLogic.TransferState.Transferable, base.QuestGiver.Name, 150, false, false, PartyScreenMode.PrisonerManage);
			}

			// Token: 0x06004C7B RID: 19579 RVA: 0x00153F7B File Offset: 0x0015217B
			private void OnCancelClicked()
			{
				Campaign.Current.ConversationManager.ContinueConversation();
			}

			// Token: 0x06004C7C RID: 19580 RVA: 0x00153F8C File Offset: 0x0015218C
			private Tuple<bool, TextObject> DoneButtonCondition(TroopRoster leftMemberRoster, TroopRoster leftPrisonRoster, TroopRoster rightMemberRoster, TroopRoster rightPrisonRoster, int leftLimitNum, int rightLimitNum)
			{
				if (this._maximumPrisonerCount - this._deliveredPrisonerCount < leftPrisonRoster.TotalManCount)
				{
					int num = this._maximumPrisonerCount - this._deliveredPrisonerCount;
					TextObject textObject = new TextObject("{=bgXebaRF}You can only transfer {X} prisoner{?IS_PLURAL}s{?}{\\?}.", null);
					textObject.SetTextVariable("IS_PLURAL", (num > 1) ? 1 : 0);
					textObject.SetTextVariable("X", num);
					return new Tuple<bool, TextObject>(false, textObject);
				}
				return new Tuple<bool, TextObject>(true, null);
			}

			// Token: 0x06004C7D RID: 19581 RVA: 0x00153FF8 File Offset: 0x001521F8
			private bool OnDoneClicked(TroopRoster leftMemberRoster, TroopRoster leftPrisonRoster, TroopRoster rightMemberRoster, TroopRoster rightPrisonRoster, FlattenedTroopRoster takenPrisonerRoster, FlattenedTroopRoster releasedPrisonerRoster, bool isForced, PartyBase leftParty, PartyBase rightParty)
			{
				foreach (TroopRosterElement troopRosterElement in leftPrisonRoster.GetTroopRoster())
				{
					this._rewardGold += Campaign.Current.Models.RansomValueCalculationModel.PrisonerRansomValue(troopRosterElement.Character, Hero.MainHero) * troopRosterElement.Number * 5;
					this._deliveredPrisonerCount += troopRosterElement.Number;
				}
				this._questProgressLogTest.UpdateCurrentProgress(this._deliveredPrisonerCount);
				this._questProgressLogTest.TaskName.SetTextVariable("TOTAL_REWARD", this._rewardGold);
				if (this._deliveredPrisonerCount == this._maximumPrisonerCount)
				{
					this._playerReachedMaximumAmount = true;
				}
				Campaign.Current.ConversationManager.ContinueConversation();
				return true;
			}

			// Token: 0x06004C7E RID: 19582 RVA: 0x001540E0 File Offset: 0x001522E0
			private bool IsTroopTransferable(CharacterObject character, PartyScreenLogic.TroopType type, PartyScreenLogic.PartyRosterSide side, PartyBase leftOwnerParty)
			{
				return side == PartyScreenLogic.PartyRosterSide.Left || (this._maximumPrisonerCount - this._deliveredPrisonerCount >= 0 && MobileParty.MainParty.PrisonRoster.Contains(character) && character.Occupation == Occupation.Bandit);
			}

			// Token: 0x06004C7F RID: 19583 RVA: 0x00154118 File Offset: 0x00152318
			private bool CheckIfThereIsSuitablePrisonerInPlayer()
			{
				bool flag = false;
				using (List<TroopRosterElement>.Enumerator enumerator = MobileParty.MainParty.PrisonRoster.GetTroopRoster().GetEnumerator())
				{
					while (enumerator.MoveNext())
					{
						if (enumerator.Current.Character.Occupation == Occupation.Bandit)
						{
							flag = true;
							break;
						}
					}
				}
				return flag;
			}

			// Token: 0x06004C80 RID: 19584 RVA: 0x00154184 File Offset: 0x00152384
			private void ApplyQuestSuccessConsequences()
			{
				if (this._shareProfit)
				{
					base.AddLog(this.QuestSuccessWithProfitShareLog, false);
					TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
					{
						new Tuple<TraitObject, int>(DefaultTraits.Honor, 30)
					});
					GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold / 2, false);
					if (this.IsQuestWithCounterOffer)
					{
						base.QuestGiver.CurrentSettlement.Notables.First((Hero x) => x.IsHeadman).AddPower(5f);
					}
				}
				else
				{
					base.AddLog(this.QuestSuccessLog, false);
					TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
					{
						new Tuple<TraitObject, int>(DefaultTraits.Honor, 30),
						new Tuple<TraitObject, int>(DefaultTraits.Mercy, -20)
					});
					GiveGoldAction.ApplyBetweenCharacters(null, Hero.MainHero, this._rewardGold, false);
					if (this.IsQuestWithCounterOffer && this._counterOfferGiven)
					{
						ChangeRelationAction.ApplyPlayerRelation(base.QuestGiver.CurrentSettlement.Notables.First((Hero x) => x.IsHeadman), -5, true, true);
						base.QuestGiver.CurrentSettlement.Notables.First((Hero x) => x.IsHeadman).AddPower(-10f);
					}
				}
				base.QuestGiver.AddPower(10f);
				this.RelationshipChangeWithQuestGiver = 5;
			}

			// Token: 0x06004C81 RID: 19585 RVA: 0x00154320 File Offset: 0x00152520
			private void QuestFailPlayerAcceptedCounterOffer()
			{
				base.AddLog(this.QuestFailPlayerAcceptedCounterOfferLog, false);
				TraitLevelingHelper.OnIssueSolvedThroughQuest(base.QuestGiver, new Tuple<TraitObject, int>[]
				{
					new Tuple<TraitObject, int>(DefaultTraits.Mercy, 20),
					new Tuple<TraitObject, int>(DefaultTraits.Generosity, 20),
					new Tuple<TraitObject, int>(DefaultTraits.Honor, -10)
				});
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -3;
				Hero hero = base.QuestGiver.CurrentSettlement.Notables.First((Hero x) => x.IsHeadman);
				hero.AddPower(10f);
				ChangeRelationAction.ApplyPlayerRelation(hero, 5, true, true);
				base.CompleteQuestWithFail(null);
			}

			// Token: 0x06004C82 RID: 19586 RVA: 0x001543DF File Offset: 0x001525DF
			protected override void OnBeforeTimedOut(ref bool completeWithSuccess, ref bool doNotResolveTheQuest)
			{
				if (this._deliveredPrisonerCount >= this._requestedPrisonerCount)
				{
					completeWithSuccess = true;
					this.ApplyQuestSuccessConsequences();
				}
			}

			// Token: 0x06004C83 RID: 19587 RVA: 0x001543F8 File Offset: 0x001525F8
			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				base.QuestGiver.AddPower(-10f);
				this.RelationshipChangeWithQuestGiver = -5;
			}

			// Token: 0x06004C84 RID: 19588 RVA: 0x00154420 File Offset: 0x00152620
			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.ClanChangedKingdom.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.VillageBeingRaided.AddNonSerializedListener(this, new Action<Village>(this.OnVillageRaided));
				CampaignEvents.GameMenuOpened.AddNonSerializedListener(this, new Action<MenuCallbackArgs>(this.OnGameMenuOpened));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			// Token: 0x06004C85 RID: 19589 RVA: 0x001544A0 File Offset: 0x001526A0
			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			// Token: 0x06004C86 RID: 19590 RVA: 0x001544B4 File Offset: 0x001526B4
			private void OnGameMenuOpened(MenuCallbackArgs args)
			{
				if (this.IsQuestWithCounterOffer && !this._counterOfferGiven && args.MenuContext.GameMenu.StringId == "village" && Settlement.CurrentSettlement == base.QuestGiver.CurrentSettlement && Campaign.Current.GameMenuManager.NextLocation == null && GameStateManager.Current.ActiveState is MapState && PlayerEncounter.EncounterSettlement != null && this.CheckIfThereIsSuitablePrisonerInPlayer())
				{
					Hero hero = base.QuestGiver.CurrentSettlement.Notables.First((Hero x) => x.IsHeadman);
					CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter, PartyBase.MainParty, false, false, false, false, false, false), new ConversationCharacterData(hero.CharacterObject, null, false, false, false, false, false, false));
				}
			}

			// Token: 0x06004C87 RID: 19591 RVA: 0x001545A0 File Offset: 0x001527A0
			private void OnVillageRaided(Village village)
			{
				if (village == base.QuestGiver.CurrentSettlement.Village)
				{
					base.AddLog(this.QuestGiverVillageRaided, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			// Token: 0x06004C88 RID: 19592 RVA: 0x001545CA File Offset: 0x001527CA
			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			// Token: 0x06004C89 RID: 19593 RVA: 0x001545F9 File Offset: 0x001527F9
			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog);
			}

			// Token: 0x06004C8A RID: 19594 RVA: 0x00154610 File Offset: 0x00152810
			protected override void OnFinalize()
			{
			}

			// Token: 0x06004C8B RID: 19595 RVA: 0x00154612 File Offset: 0x00152812
			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
			}

			// Token: 0x040019FE RID: 6654
			private const int MaximumPrisonerLimitMinValue = 40;

			// Token: 0x040019FF RID: 6655
			private const int MaximumPrisonerLimitMaxValue = 60;

			// Token: 0x04001A00 RID: 6656
			[SaveableField(1)]
			private int _requestedPrisonerCount;

			// Token: 0x04001A01 RID: 6657
			[SaveableField(2)]
			private bool _shareProfit;

			// Token: 0x04001A02 RID: 6658
			[SaveableField(4)]
			private bool _counterOfferGiven;

			// Token: 0x04001A03 RID: 6659
			[SaveableField(5)]
			private int _deliveredPrisonerCount;

			// Token: 0x04001A04 RID: 6660
			[SaveableField(6)]
			private int _rewardGold;

			// Token: 0x04001A05 RID: 6661
			[SaveableField(8)]
			private int _maximumPrisonerCount;

			// Token: 0x04001A06 RID: 6662
			[SaveableField(9)]
			private bool _playerReachedMaximumAmount;

			// Token: 0x04001A07 RID: 6663
			[SaveableField(7)]
			private JournalLog _questProgressLogTest;
		}

		// Token: 0x02000638 RID: 1592
		public class LandLordNeedsManualLaborersIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			// Token: 0x06004C8E RID: 19598 RVA: 0x0015467E File Offset: 0x0015287E
			public LandLordNeedsManualLaborersIssueBehaviorTypeDefiner()
				: base(810000)
			{
			}

			// Token: 0x06004C8F RID: 19599 RVA: 0x0015468B File Offset: 0x0015288B
			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssue), 1, null);
				base.AddClassDefinition(typeof(LandLordNeedsManualLaborersIssueBehavior.LandLordNeedsManualLaborersIssueQuest), 2, null);
			}
		}
	}
}
