using System;
using System.Collections.Generic;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	public class LandLordTheArtOfTheTradeIssueBehavior : CampaignBehaviorBase
	{
		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		public override void SyncData(IDataStore dataStore)
		{
		}

		private bool ConditionsHold(Hero issueGiver)
		{
			if (issueGiver.IsRuralNotable)
			{
				Settlement currentSettlement = issueGiver.CurrentSettlement;
				Village village = ((currentSettlement != null) ? currentSettlement.Village : null);
				return village != null && village.Bound.Town.GetItemPrice(village.VillageType.PrimaryProduction, null, false) < village.VillageType.PrimaryProduction.Value;
			}
			return false;
		}

		public void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue(issueOwner, issueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction);
		}

		private const IssueBase.IssueFrequency LandLordTheArtOfTheTradeIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		private const float TargetDenarsConstant = 0.55f;

		public class LandLordTheArtOfTheTradeIssue : IssueBase
		{
			internal static void AutoGeneratedStaticCollectObjectsLandLordTheArtOfTheTradeIssue(object o, List<object> collectedObjects)
			{
				((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			private int SelectedItemObjectCount
			{
				get
				{
					return MathF.Max(1, MathF.Round((float)((int)(5000f / (float)this._selectedItemObject.Value)) * base.IssueDifficultyMultiplier));
				}
			}

			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 2 + MathF.Ceiling(4f * base.IssueDifficultyMultiplier);
				}
			}

			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 3 + MathF.Ceiling(5f * base.IssueDifficultyMultiplier);
				}
			}

			protected override int RewardGold
			{
				get
				{
					return (int)((float)(this._selectedItemObject.Value * this.SelectedItemObjectCount) * this.RewardGoldDeterministicRandomContribution);
				}
			}

			private float RewardGoldDeterministicRandomContribution
			{
				get
				{
					return base.IssueOwner.RandomFloatWithSeed((uint)this.IssueCreationTime.ElapsedDaysUntilNow, 0.2f, 0.5f);
				}
			}

			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=AKdDSZoM}Yes. It's a good problem to have, though. As you know, I deal in {.%}{SELECTED_ITEM}{.%}. Production this year has been very good, and we can no longer make a profit on the local market. I cannot however, put together a caravan to sell it elsewhere. So, I propose a very simple deal.[if:convo_innocent_smile][ib:confident]", null);
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject = new TextObject("{=llVFTH6n}Yes. It's a good problem to have, though. As you may know, I deal in {PLURAL(SELECTED_ITEM)}. Our herds have increased this year, and we can no longer make a profit on the local market. I cannot however organize a drive to a new market. So, I propose a very simple deal.[if:convo_innocent_smile][ib:confident]", null);
					}
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					return textObject;
				}
			}

			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					return new TextObject("{=8jyUn6mb}You sell me the goods at a discount?", null);
				}
			}

			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=rWnvnufw}That could work, if you have the money. But if you don't, I'm willing to take a chance on you. I reckon for {SELECTED_ITEM_COUNT} {.%}{?SELECTED_ITEM_COUNT > 1}{PLURAL(SELECTED_ITEM)}{?}{SELECTED_ITEM}{\\?}{.%} you can probably find a market nearby where buyers will pay you a total of {TOTAL_GOLD}{GOLD_ICON}. Here's my offer. I loan you the product. You sell it at whatever price you like, and bring me back {TOTAL_GOLD}{GOLD_ICON} denars. I have little doubt you could find a market where you could get a better price than this, and make a profit.[if:convo_innocent_smile][ib:confident]", null);
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject = new TextObject("{=b19Hlp7h}That could work, if you have the money. But if you don't, I'm willing to take a chance on you. I reckon for {SELECTED_ITEM_COUNT} {?SELECTED_ITEM_COUNT > 1}{PLURAL(SELECTED_ITEM)}{?}{SELECTED_ITEM}{\\?} you can probably find a market nearby where buyers will pay you a total of {TOTAL_GOLD}{GOLD_ICON}. Here's my offer. I loan you the livestock. You sell at whatever price you like, and bring me back {TOTAL_GOLD}{GOLD_ICON} denars. I have little doubt you could find a market where you could get a better price than this, and make a profit.[if:convo_innocent_smile][ib:confident]", null);
					}
					textObject.SetTextVariable("TOTAL_GOLD", (int)((float)(this._selectedItemObject.Value * this.SelectedItemObjectCount) * 0.55f));
					textObject.SetTextVariable("SELECTED_ITEM_COUNT", this.SelectedItemObjectCount);
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			public override TextObject IssuePlayerResponseAfterAlternativeExplanation
			{
				get
				{
					return new TextObject("{=w1rVTUIs}This seems like a simple errand. Would your offer still stand if I get someone else to do it for me?", null);
				}
			}

			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=PE97ZWvX}Not just anybody. If you have a companion that has your complete trust, then I'll agree... Just make sure he is well guarded. Goods attract bandits, as I'm sure you know. I suppose {ALTERNATIVE_TROOP_AMOUNT} well-armed men would be enough.[if:convo_innocent_smile][ib:confident]", null);
					textObject.SetTextVariable("ALTERNATIVE_TROOP_AMOUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					return textObject;
				}
			}

			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=aB0TT6Ur}Fear not. I will find the right market for your {.%}{SELECTED_ITEM}{.%} myself.", null);
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject = new TextObject("{=cBO49V5b}Fear not. I will find the right market for your {PLURAL(SELECTED_ITEM)} myself.", null);
					}
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					return textObject;
				}
			}

			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=IFasMslv}I will assign a companion with {TROOP_COUNT} good men for {RETURN_DAYS} days.", null);
					textObject.SetTextVariable("TROOP_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					return textObject;
				}
			}

			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=dLywF1Uz}I have heard your companion has started to sell the goods. This was a good deal, {?PLAYER.GENDER}ma'am{?}sir{\\?}.[if:convo_relaxed_happy][ib:confident]", null);
				}
			}

			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					return new TextObject("{=aUXAh8cE}Very well, {PLAYER.NAME}. If you're willing to vouch for your companion, I'm sure this will work.[if:convo_innocent_smile][ib:confident]", null);
				}
			}

			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=BK9ww4NU}{QUEST_GIVER.LINK} asked you to sell {?QUEST_GIVER.GENDER}her{?}his{\\?} goods for at least {UNIT_PRICE}{GOLD_ICON} per {UNIT_NAME} and return to {?QUEST_GIVER.GENDER}her{?}him{\\?}. {?QUEST_GIVER.GENDER}She{?}He{\\?} told you that any profit that the deal would make above this price is yours to keep. You asked {COMPANION.LINK} to take {TROOP_COUNT} of your best men to go and take care of it. They should report back to you in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, true);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("UNIT_NAME", "{=g72xNv75}load");
					if (this._selectedItemObject.HasHorseComponent || this._selectedItemObject.IsAnimal)
					{
						textObject.SetTextVariable("UNIT_NAME", "{=T9Tgi9is}animal");
					}
					textObject.SetTextVariable("UNIT_PRICE", this._selectedItemObject.Value);
					textObject.SetTextVariable("RETURN_DAYS", base.GetTotalAlternativeSolutionDurationInDays());
					textObject.SetTextVariable("TROOP_COUNT", base.GetTotalAlternativeSolutionNeededMenCount());
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=BDAmZkJF}You received a message from {ISSUE_GIVER.LINK}. 'It was a pleasure doing business with you and your folks.'", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			public override TextObject Title
			{
				get
				{
					return new TextObject("{=96m29Eb7}The Art of The Trade", null);
				}
			}

			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=BZwKEIm5}{ISSUE_GIVER.LINK} wants you to sell {?ISSUE_GIVER.GENDER}her{?}his{\\?} goods for a price above the global average.", null);
					StringHelpers.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, null, false);
					return textObject;
				}
			}

			public LandLordTheArtOfTheTradeIssue(Hero issueOwner, ItemObject villageProduction)
				: base(issueOwner, CampaignTime.DaysFromNow(30f))
			{
				this._selectedItemObject = villageProduction;
			}

			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.VillageHearth)
				{
					return -0.1f;
				}
				if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
				{
					return -0.1f;
				}
				return 0f;
			}

			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Trade) >= hero.GetSkillValue(DefaultSkills.Riding)) ? DefaultSkills.Trade : DefaultSkills.Riding, 120);
			}

			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				int totalAlternativeSolutionNeededMenCount = base.GetTotalAlternativeSolutionNeededMenCount();
				if (this.GetNumberOfTier2Troops(troopRoster) < totalAlternativeSolutionNeededMenCount)
				{
					explanation = new TextObject("{=rJIY7OiR}You have to send {NEEDED_TROOP_COUNT} troops with at least tier 2 to this quest.", null);
					explanation.SetTextVariable("NEEDED_TROOP_COUNT", totalAlternativeSolutionNeededMenCount);
					return false;
				}
				explanation = TextObject.Empty;
				return true;
			}

			private int GetNumberOfTier2Troops(TroopRoster troopRoster)
			{
				int num = 0;
				foreach (TroopRosterElement troopRosterElement in troopRoster.GetTroopRoster())
				{
					if (troopRosterElement.Character.Tier >= 2)
					{
						num += troopRoster.GetTroopCount(troopRosterElement.Character) - troopRoster.GetElementWoundedNumber(troopRoster.FindIndexOfTroop(troopRosterElement.Character));
					}
				}
				return num;
			}

			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			public override bool IssueStayAliveConditions()
			{
				return !base.IssueOwner.CurrentSettlement.IsRaided && !base.IssueOwner.CurrentSettlement.IsUnderRaid && (float)base.IssueOwner.CurrentSettlement.Village.Bound.Town.GetItemPrice(base.IssueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction, null, false) < (float)base.IssueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction.Value * 1.3f;
			}

			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flags, out Hero relationHero, out SkillObject skill)
			{
				flags = IssueBase.PreconditionFlags.None;
				relationHero = null;
				skill = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					flags |= IssueBase.PreconditionFlags.Relation;
					relationHero = issueGiver;
				}
				if (FactionManager.IsAtWarAgainstFaction(issueGiver.MapFaction, Hero.MainHero.MapFaction))
				{
					flags |= IssueBase.PreconditionFlags.AtWar;
				}
				return flags == IssueBase.PreconditionFlags.None;
			}

			protected override void OnGameLoad()
			{
				this._selectedItemObject = base.IssueOwner.CurrentSettlement.Village.VillageType.PrimaryProduction;
			}

			protected override void HourlyTick()
			{
			}

			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest(questId, base.IssueOwner, CampaignTime.DaysFromNow(30f), this._selectedItemObject, this.SelectedItemObjectCount);
			}

			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(900f + 800f * base.IssueDifficultyMultiplier);
				}
			}

			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				this.RelationshipChangeWithIssueOwner = 10;
			}

			private const int IssueAndQuestDuration = 30;

			private const int CompanionRequiredSkillLevel = 120;

			private ItemObject _selectedItemObject;
		}

		public class LandLordTheArtOfTheTradeIssueQuest : QuestBase
		{
			internal static void AutoGeneratedStaticCollectObjectsLandLordTheArtOfTheTradeIssueQuest(object o, List<object> collectedObjects)
			{
				((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._selectedItemObject);
				collectedObjects.Add(this._soldItemAmountLog);
				collectedObjects.Add(this._gatheredDenarsLog);
			}

			internal static object AutoGeneratedGetMemberValue_selectedItemObject(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._selectedItemObject;
			}

			internal static object AutoGeneratedGetMemberValue_selectedItemObjectCount(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._selectedItemObjectCount;
			}

			internal static object AutoGeneratedGetMemberValue_soldCount(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._soldCount;
			}

			internal static object AutoGeneratedGetMemberValue_gatheredDenars(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._gatheredDenars;
			}

			internal static object AutoGeneratedGetMemberValue_daysPassed(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._daysPassed;
			}

			internal static object AutoGeneratedGetMemberValue_underSoldLogAdded(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._underSoldLogAdded;
			}

			internal static object AutoGeneratedGetMemberValue_soldItemAmountLog(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._soldItemAmountLog;
			}

			internal static object AutoGeneratedGetMemberValue_gatheredDenarsLog(object o)
			{
				return ((LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest)o)._gatheredDenarsLog;
			}

			public override TextObject Title
			{
				get
				{
					return new TextObject("{=96m29Eb7}The Art of The Trade", null);
				}
			}

			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			private bool QuestCanBeFinalized
			{
				get
				{
					return Hero.OneToOneConversationHero != null && Hero.OneToOneConversationHero == base.QuestGiver && (this.ItemCountLeftToSell <= 0 || this._targetDenarsToAchieve <= this._gatheredDenars || (this._daysPassed >= 1 && this.CheckIfPlayerLostItem()));
				}
			}

			private int ItemCountLeftToSell
			{
				get
				{
					return this._selectedItemObjectCount - this._soldCount;
				}
			}

			private int RemainingDenars
			{
				get
				{
					return this._targetDenarsToAchieve - this._gatheredDenars;
				}
			}

			private TextObject QuestStartedLogText1
			{
				get
				{
					TextObject textObject = new TextObject("{=2bcNCnI3}{QUEST_GIVER.LINK} asked you to sell {?QUEST_GIVER.GENDER}her{?}his{\\?} goods for at least {UNIT_PRICE}{GOLD_ICON} per load and return to {?QUEST_GIVER.GENDER}her{?}him{\\?}. {?QUEST_GIVER.GENDER}She{?}He{\\?} told you that any profit would make above this price is yours to keep.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, true);
					textObject.SetTextVariable("UNIT_PRICE", this._targetDenarsToAchieve / this._selectedItemObjectCount);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			private TextObject QuestStartedLogText2
			{
				get
				{
					TextObject textObject = new TextObject("{=jI251oj9}{?QUEST_GIVER.GENDER}She{?}He{\\?} noted that {?QUEST_GIVER.GENDER}she{?}he{\\?} has {SELECTED_ITEM_COUNT} {.%}{?SELECTED_ITEM_COUNT > 1}{PLURAL(SELECTED_ITEM)}{?}{SELECTED_ITEM}{\\?}{.%}. {?QUEST_GIVER.GENDER}She{?}He{\\?} is expecting to earn {TOTAL_GOLD}{GOLD_ICON} denars from that.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("SELECTED_ITEM_COUNT", this._selectedItemObjectCount);
					textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
					textObject.SetTextVariable("TOTAL_GOLD", this._targetDenarsToAchieve);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			private TextObject QuestStartedLogText3
			{
				get
				{
					TextObject textObject = new TextObject("{=tf04Piaj}You told {?QUEST_GIVER.GENDER}her{?}him{\\?} that you will sell the goods personally.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject QuestSuccessLogText
			{
				get
				{
					return new TextObject("{=EsNDadiR}You have completed your end of your bargain and made some denars simply by using your smarts.", null);
				}
			}

			private TextObject QuestReadyToBeFinishedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=2GMOnUIM}{QUEST_GIVER.LINK} expects your return to have {?QUEST_GIVER.GENDER}her{?}his{\\?} share of the deal.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			private TextObject QuestReadyToBeFinishedUnderSoldLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=IfPnl0B6}You have lost some of the wares you were supposed to be selling. You can speak with {QUEST_GIVER.LINK} to pay for a compensation.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject QuestSuccessWithPayingGatheredDenarsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=4bDHBIr1}You have completed your end of the bargain. {QUEST_GIVER.LINK} now considers you as a trustworthy {?PLAYER.GENDER}tradeswoman{?}tradesman{\\?}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject, false);
					return textObject;
				}
			}

			private TextObject QuestSuccessPlayerBoughtItemsLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=rYt43AWk}{QUEST_GIVER.LINK} accepted your offer to buy the products from an average price. You can now sell those for profits without any obligations to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject QuestFailedPlayerBrokeTheAgreementLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=1q2dxlol}You have failed to pay {TOTAL_DENAR}{GOLD_ICON} denars to {QUEST_GIVER.LINK}. {QUEST_GIVER_VILLAGE} and its locals are aware of your misdemeanor.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_VILLAGE", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					textObject.SetTextVariable("TOTAL_DENAR", this._targetDenarsToAchieve);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			private TextObject QuestCanceledWarDeclaredLog
			{
				get
				{
					TextObject textObject = new TextObject("{=vW6kBki9}Your clan is now at war with {QUEST_GIVER.LINK}'s realm. Your agreement with {QUEST_GIVER.LINK} is canceled.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject PlayerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject QuestGiverVillageRaided
			{
				get
				{
					TextObject textObject = new TextObject("{=w0FD9U98}{QUEST_GIVER.LINK}'s village is raided. Your agreement with {?QUEST_GIVER.GENDER}her{?}him{\\?} is moot.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_SETTLEMENT", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			private TextObject QuestFailedWithTimeOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=PQt8lfTX}You have failed to return to the {QUEST_GIVER.LINK} in time. {QUEST_GIVER_VILLAGE} and its locals are aware of your misdemeanor.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("QUEST_GIVER_VILLAGE", base.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
					return textObject;
				}
			}

			public LandLordTheArtOfTheTradeIssueQuest(string questId, Hero giverHero, CampaignTime duration, ItemObject selectedItemObject, int selectedItemObjectCount)
				: base(questId, giverHero, duration, 0)
			{
				this._selectedItemObject = selectedItemObject;
				this._selectedItemObjectCount = selectedItemObjectCount;
				this._targetDenarsToAchieve = (int)((float)(selectedItemObject.Value * selectedItemObjectCount) * 0.55f);
				this._daysPassed = 0;
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			protected override void SetDialogs()
			{
				TextObject textObject = new TextObject("{=3Sk0BQ4n}I will buy the products from you for {TOTAL_GOLD}{GOLD_ICON}. This way we both will get what we desire.", null);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject = new TextObject("{=7nBOWsg2}I will buy the livestock from you for {TOTAL_GOLD}{GOLD_ICON}. This way we both will get what we desire.", null);
				}
				textObject.SetTextVariable("TOTAL_GOLD", this._targetDenarsToAchieve);
				textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				TextObject textObject2 = new TextObject("{=iYtzlRSN}I would rather be your middleman on this matter. I need to keep my money. You can have your men load up the {.%}{SELECTED_ITEM}{.%} already.", null);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject2 = new TextObject("{=exmSGWUb}I would rather be your middleman on this matter. I need to keep my money. You can have your men get the herd ready.", null);
				}
				textObject2.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				TextObject textObject3 = new TextObject("{=9d6WxRrj}Do you want to buy the goods yourself? Or will I retain ownership, and you just keep the extra profits? I am expecting to earn {TOTAL_DENARS}{GOLD_ICON} for {SELECTED_COUNT} loads of produce. If would like to buy it right away you can simply sell it yourself or do whatever you wish with it.", null);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject3 = new TextObject("{=GihVcxIB}Do you want to buy the livestock yourself? Or will I retain ownership, and you just keep the extra profits? I am expecting to earn {TOTAL_DENARS}{GOLD_ICON} in total. If would like to buy the livestock right away you can simply sell it yourself or do whatever you wish with it.", null);
				}
				textObject3.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				textObject3.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				textObject3.SetTextVariable("SELECTED_COUNT", this._selectedItemObjectCount);
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine(new TextObject("{=NaoYCmC6}Good. Needless to say, by not taking any money up front, I am trusting in your honesty in your ability to protect those goods. But I am sure that trust will not be misplaced.[if:convo_innocent_smile][ib:closed]", null), null, null).Condition(() => Hero.OneToOneConversationHero == this.QuestGiver)
					.NpcLine(textObject3, null, null)
					.BeginPlayerOptions()
					.PlayerOption(textObject, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.PlayerBuyClickableOptionCondition))
					.NpcLine(new TextObject("{=LmTii9E2}It was a pleasure doing business with you. If only everyone was as honest as you.[if:convo_happy][ib:confident3]", null), null, null)
					.Consequence(delegate
					{
						this.StartQuest();
						this.QuestFinishedPlayerBoughtTheGoods();
					})
					.CloseDialog()
					.PlayerOption(textObject2, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences))
					.CloseDialog()
					.EndPlayerOptions()
					.CloseDialog();
				TextObject playerMainOptionOneWithGold = new TextObject("{=1zdkXAwL}The market isn't what we expected. I am afraid I only made {GATHERED_DENARS}{GOLD_ICON} of the {TOTAL_DENARS}{GOLD_ICON} that we agreed upon.", null);
				playerMainOptionOneWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
				playerMainOptionOneWithGold.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				playerMainOptionOneWithGold.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				TextObject playerMainOptionOneNoGold = new TextObject("{=52lNazA1}I'm afraid that things came up. I was not able to make the sale.", null);
				TextObject textObject4 = new TextObject("{=!}{PLAYER_OPTION}", null);
				TextObject textObject5 = new TextObject("{=THD3C7xc}I have. Here is the {TOTAL_DENARS}{GOLD_ICON} denars just as we agreed.[ib:hip2]", null);
				textObject5.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				textObject5.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				TextObject textObject6 = new TextObject("{=z47GjqTZ}Yes, of course. This is the {TOTAL_DENARS}{GOLD_ICON} denars that I owe you.[ib:hip2]", null);
				textObject6.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
				textObject6.SetTextVariable("TOTAL_DENARS", this._targetDenarsToAchieve);
				TextObject playerFailOptionWithGold = new TextObject("{=dtzKfkrh}We never agreed on this. I am not paying you any more than {GATHERED_DENARS}{GOLD_ICON}, and you cannot force me.", null);
				playerFailOptionWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
				TextObject playerFailOptionNoGold = new TextObject("{=aFDiKxhr}Our deal involved you getting your cut from the sales I made. No sale means no cut. I'm sure you understand.[ib:warrior2]", null);
				TextObject textObject7 = new TextObject("{=!}{PLAYER_FAIL_OPTION}", null);
				TextObject textObject8 = new TextObject("{=41wb8QaV}I know I can not force you to pay you what you owe me. But I think you will find that a good name is worth more than a few loads of {SELECTED_ITEM}...", null);
				textObject8.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				if (this._selectedItemObject.IsAnimal || this._selectedItemObject.HasHorseComponent)
				{
					textObject8 = new TextObject("{=pcrdOlE8}I know I can not force you to pay you what you owe me. But I think you will find that a good name is worth more than a bit of livestock...", null);
				}
				TextObject textObject9 = new TextObject("{=OIwtLKN3}I am a {?PLAYER.GENDER}woman{?}man{\\?} of my word. I will raise some money to pay you. Wait for my return {QUEST_GIVER.LINK}.", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject9, false);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject9, false);
				TextObject textObject10 = new TextObject("{=bPPXiybO}I just happened to be around. Have no fear {QUEST_GIVER.NAME}, your goods are fine.", null);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject10, false);
				TextObject textObject11 = new TextObject("{=ekSg8okD}I will be better once you return with the denars you owe me {PLAYER.NAME}.[ib:aggressive2]", null);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject10, false);
				TextObject textObject12 = new TextObject("{=bbsN6hOo}Have you already sold that {SELECTED_ITEM}? If so, that seems awfully quick.", null);
				textObject12.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).BeginNpcOptions().NpcOption(textObject12, () => Hero.OneToOneConversationHero != null && Hero.OneToOneConversationHero == this.QuestGiver && !this.QuestCanBeFinalized, null, null)
					.BeginPlayerOptions()
					.PlayerOption(new TextObject("{=gVad94Br}I was just checking in with you.", null), null)
					.Condition(() => !this.QuestCanBeFinalized)
					.NpcLine(textObject11, null, null)
					.CloseDialog()
					.PlayerOption(textObject10, null)
					.Condition(() => !this.QuestCanBeFinalized)
					.NpcLine(textObject11, null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.NpcOption(new TextObject("{=1q3FKY1s}Have you made your trip yet? I presume you were able to make a sale?", null), () => Hero.OneToOneConversationHero != null && Hero.OneToOneConversationHero == this.QuestGiver && this.QuestCanBeFinalized, null, null)
					.BeginPlayerOptions()
					.PlayerOption(textObject4, null)
					.Condition(delegate
					{
						if (this._gatheredDenars > 0)
						{
							playerMainOptionOneWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_OPTION", playerMainOptionOneWithGold);
						}
						else
						{
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_OPTION", playerMainOptionOneNoGold);
						}
						return this.QuestCanBeFinalized && this._productsUndersold;
					})
					.NpcLine(new TextObject("{=QlYUE00L}Well. We did have an agreement. I do expect you to pay the full amount.", null), null, null)
					.BeginPlayerOptions()
					.PlayerOption(textObject6, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.PlayerPayAgreedDenarsClickableCondition))
					.NpcLine(new TextObject("{=gNHh9bvb}I am sorry that you did not manage to make a profit. But you are keeping your end of the bargain, and that is admirable.", null), null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.PlayerPaidAgreedDenarsQuestSuccess;
					})
					.CloseDialog()
					.PlayerOption(textObject7, null)
					.ClickableCondition(new ConversationSentence.OnClickableConditionDelegate(this.PlayerFailWithGoldClickableCondition))
					.Condition(delegate
					{
						if (this._gatheredDenars > 0)
						{
							playerFailOptionWithGold.SetTextVariable("GATHERED_DENARS", this._gatheredDenars);
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_FAIL_OPTION", playerFailOptionWithGold);
						}
						else
						{
							Campaign.Current.ConversationManager.GetCurrentDialogLine().SetTextVariable("PLAYER_FAIL_OPTION", playerFailOptionNoGold);
						}
						return true;
					})
					.NpcLine(textObject8, null, null)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += this.QuestFailedPlayerBrokeTheAgreement;
					})
					.CloseDialog()
					.PlayerOption(textObject9, null)
					.NpcLine(new TextObject("{=RxjuaDum}I am glad of that. Don't make me wait too long. Some men say they will pay a debt, and you never see them again.[if:convo_mocking_teasing][ib:confident2]", null), null, null)
					.CloseDialog()
					.EndPlayerOptions()
					.PlayerOption(textObject5, null)
					.Condition(() => this.QuestCanBeFinalized && !this._productsUndersold)
					.NpcLine(new TextObject("{=9jFqXvHy}Excellent! I knew you were an honest soul. Trust is a fine thing, isn't it? Perhaps we can do more business in the future.[if:convo_innocent_smile][ib:confident]", null), null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestSuccessPlayerSoldTheProducts))
					.CloseDialog()
					.EndPlayerOptions()
					.EndNpcOptions();
			}

			private void QuestSuccessPlayerSoldTheProducts()
			{
				base.AddLog(this.QuestSuccessLogText, false);
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				this.RelationshipChangeWithQuestGiver = 10;
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._targetDenarsToAchieve, false);
				base.CompleteQuestWithSuccess();
			}

			private void QuestFailedPlayerBrokeTheAgreement()
			{
				base.AddLog(this.QuestFailedPlayerBrokeTheAgreementLogText, false);
				ChangeCrimeRatingAction.Apply(base.QuestGiver.MapFaction, 5f, true);
				base.QuestGiver.AddPower(-5f);
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._gatheredDenars, false);
				this.RelationshipChangeWithQuestGiver = -10 - this.RemainingDenars / 10;
				base.CompleteQuestWithFail(null);
			}

			private void PlayerPaidAgreedDenarsQuestSuccess()
			{
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._targetDenarsToAchieve, false);
				this.RelationshipChangeWithQuestGiver = 10;
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				base.AddLog(this.QuestSuccessWithPayingGatheredDenarsLogText, false);
				base.CompleteQuestWithSuccess();
			}

			private bool PlayerPayAgreedDenarsClickableCondition(out TextObject explanation)
			{
				explanation = TextObject.Empty;
				if (Hero.MainHero.Gold < this._targetDenarsToAchieve)
				{
					explanation = new TextObject("{=d0kbtGYn}You don't have enough gold.", null);
					return false;
				}
				MBTextManager.SetTextVariable("REMAINING_DENARS", this.RemainingDenars);
				return true;
			}

			private bool PlayerFailWithGoldClickableCondition(out TextObject explanation)
			{
				explanation = TextObject.Empty;
				if (this._gatheredDenars > 0 && Hero.MainHero.Gold < this._gatheredDenars)
				{
					explanation = new TextObject("{=d0kbtGYn}You don't have enough gold.", null);
					return false;
				}
				return true;
			}

			private void QuestAcceptedConsequences()
			{
				base.StartQuest();
				base.AddTrackedObject(base.QuestGiver.CurrentSettlement);
				MobileParty.MainParty.ItemRoster.AddToCounts(this._selectedItemObject, this._selectedItemObjectCount);
				TextObject textObject = new TextObject("{=jKHkGzUn}As agreed, {SELECTED_ITEM_COUNT} {?IS_PLURAL}{.%}{PLURAL(SELECTED_ITEM)}{.%} have been{?}{.%}{SELECTED_ITEM}{.%} has been{\\?} added to your inventory.", null);
				textObject.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				textObject.SetTextVariable("SELECTED_ITEM_COUNT", this._selectedItemObjectCount);
				textObject.SetTextVariable("IS_PLURAL", (this._selectedItemObjectCount > 1) ? 1 : 0);
				MBInformationManager.AddQuickInformation(textObject, 0, null, "");
				base.AddLog(this.QuestStartedLogText1, false);
				base.AddLog(this.QuestStartedLogText2, false);
				base.AddLog(this.QuestStartedLogText3, false);
				TextObject textObject2 = new TextObject("{=GaXEmoFy}Sold {.%}{SELECTED_ITEM}{.%} amount:", null);
				textObject2.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				TextObject textObject3 = new TextObject("{=pwnqk0Nj}Gathered denars from {.%}{SELECTED_ITEM}{.%}", null);
				textObject3.SetTextVariable("SELECTED_ITEM", this._selectedItemObject.Name);
				this._soldItemAmountLog = base.AddDiscreteLog(TextObject.Empty, textObject2, this._soldCount, this._selectedItemObjectCount, null, false);
				this._gatheredDenarsLog = base.AddDiscreteLog(TextObject.Empty, textObject3, this._gatheredDenars, this._targetDenarsToAchieve, null, false);
			}

			private void QuestFinishedPlayerBoughtTheGoods()
			{
				base.AddLog(this.QuestSuccessPlayerBoughtItemsLogText, false);
				MobileParty.MainParty.ItemRoster.AddToCounts(this._selectedItemObject, this._selectedItemObjectCount);
				GiveGoldAction.ApplyBetweenCharacters(Hero.MainHero, base.QuestGiver, this._targetDenarsToAchieve, false);
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				this.RelationshipChangeWithQuestGiver = 1;
				base.CompleteQuestWithSuccess();
			}

			private bool PlayerBuyClickableOptionCondition(out TextObject explanation)
			{
				explanation = TextObject.Empty;
				if (Hero.MainHero.Gold < this._targetDenarsToAchieve)
				{
					explanation = new TextObject("{=d0kbtGYn}You don't have enough gold.", null);
					return false;
				}
				return true;
			}

			protected override void OnTimedOut()
			{
				base.AddLog(this.QuestFailedWithTimeOutLogText, false);
				this.RelationshipChangeWithQuestGiver = -10;
				ChangeCrimeRatingAction.Apply(base.QuestGiver.MapFaction, 5f, true);
			}

			protected override void RegisterEvents()
			{
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.OnClanChangedKingdomEvent.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.VillageBeingRaided.AddNonSerializedListener(this, new Action<Village>(this.OnVillageRaided));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			protected override void HourlyTick()
			{
				if (base.IsOngoing && !this._underSoldLogAdded && this.CheckIfPlayerLostItem())
				{
					base.AddLog(this.QuestReadyToBeFinishedUnderSoldLogText, false);
					this._daysPassed++;
					this._underSoldLogAdded = true;
				}
			}

			private bool CheckIfPlayerLostItem()
			{
				return this._soldCount + MobileParty.MainParty.ItemRoster.GetItemNumber(this._selectedItemObject) < this._selectedItemObjectCount;
			}

			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				if (isTrading && this.ItemCountLeftToSell > 0)
				{
					foreach (ValueTuple<ItemRosterElement, int> valueTuple in soldItems)
					{
						ItemRosterElement itemRosterElement = valueTuple.Item1;
						if (itemRosterElement.EquipmentElement.Item == this._selectedItemObject)
						{
							int soldCount = this._soldCount;
							itemRosterElement = valueTuple.Item1;
							this._soldCount = soldCount + itemRosterElement.Amount;
							this._gatheredDenars += valueTuple.Item2;
						}
					}
					if (this.ItemCountLeftToSell <= 0)
					{
						base.AddLog(this.QuestReadyToBeFinishedLogText, false);
					}
					this._productsUndersold = this._gatheredDenars < this._targetDenarsToAchieve;
					this._soldItemAmountLog.UpdateCurrentProgress(this._soldCount);
					this._gatheredDenarsLog.UpdateCurrentProgress(this._gatheredDenars);
				}
			}

			private void OnVillageRaided(Village village)
			{
				if (village == base.QuestGiver.CurrentSettlement.Village)
				{
					base.AddLog(this.QuestGiverVillageRaided, false);
					base.CompleteQuestWithCancel(null);
				}
			}

			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this.QuestCanceledWarDeclaredLog);
				}
			}

			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this.PlayerDeclaredWarQuestLogText, this.QuestCanceledWarDeclaredLog, false);
			}

			protected override void OnFinalize()
			{
			}

			protected override void InitializeQuestOnGameLoad()
			{
				this._targetDenarsToAchieve = (int)((float)(this._selectedItemObject.Value * this._selectedItemObjectCount) * 0.55f);
				this._productsUndersold = this._gatheredDenars < this._targetDenarsToAchieve;
				this.SetDialogs();
			}

			[SaveableField(10)]
			private ItemObject _selectedItemObject;

			[SaveableField(20)]
			private int _selectedItemObjectCount;

			[SaveableField(30)]
			private int _soldCount;

			[SaveableField(40)]
			private int _gatheredDenars;

			private bool _productsUndersold = true;

			[SaveableField(60)]
			private int _daysPassed;

			[SaveableField(70)]
			private bool _underSoldLogAdded;

			private int _targetDenarsToAchieve;

			[SaveableField(80)]
			private JournalLog _soldItemAmountLog;

			[SaveableField(90)]
			private JournalLog _gatheredDenarsLog;
		}

		public class LandLordTheArtOfTheTradeIssueBehaviorTypeDefiner : SaveableTypeDefiner
		{
			public LandLordTheArtOfTheTradeIssueBehaviorTypeDefiner()
				: base(249000)
			{
			}

			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssue), 1, null);
				base.AddClassDefinition(typeof(LandLordTheArtOfTheTradeIssueBehavior.LandLordTheArtOfTheTradeIssueQuest), 2, null);
			}
		}
	}
}
