using System;
using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	public class LordNeedsHorsesIssueBehavior : CampaignBehaviorBase
	{
		private void OnCheckForIssue(Hero hero)
		{
			if (this.ConditionsHold(hero))
			{
				Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnIssueSelected), typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue), IssueBase.IssueFrequency.VeryCommon, null));
				return;
			}
			Campaign.Current.IssueManager.AddPotentialIssueData(hero, new PotentialIssueData(typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue), IssueBase.IssueFrequency.VeryCommon));
		}

		private IssueBase OnIssueSelected(in PotentialIssueData pid, Hero issueOwner)
		{
			return new LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue(issueOwner);
		}

		private bool ConditionsHold(Hero issueGiver)
		{
			if (!issueGiver.IsFactionLeader)
			{
				Clan clan = issueGiver.Clan;
				if (((clan != null) ? clan.Leader : null) != issueGiver)
				{
					return false;
				}
			}
			if (!issueGiver.IsMinorFactionHero && issueGiver.Clan != Clan.PlayerClan)
			{
				MobileParty partyBelongedTo = issueGiver.PartyBelongedTo;
				if (partyBelongedTo != null && partyBelongedTo.Party.MemberRoster.TotalManCount > 50)
				{
					int num2;
					float num = LordNeedsHorsesIssueBehavior.ComputeMountsOverInfantryCountRatio(partyBelongedTo, out num2);
					return num2 >= 10 && num < 0.6f;
				}
			}
			return false;
		}

		public static float ComputeMountsOverInfantryCountRatio(MobileParty issueParty, out int numInfantry)
		{
			if (issueParty == null)
			{
				Debug.FailedAssert("Cannot compute mounts over infantry ratio as related party is null", "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Issues\\LordNeedsHorsesIssueBehavior.cs", "ComputeMountsOverInfantryCountRatio", 888);
				numInfantry = 0;
				return float.MaxValue;
			}
			int numberOfMounts = issueParty.ItemRoster.NumberOfMounts;
			numInfantry = 0;
			foreach (TroopRosterElement troopRosterElement in issueParty.Party.MemberRoster.GetTroopRoster())
			{
				if (troopRosterElement.Character.IsInfantry)
				{
					numInfantry += troopRosterElement.Number;
				}
			}
			if (numInfantry != 0)
			{
				return (float)numberOfMounts / (float)numInfantry;
			}
			return float.MaxValue;
		}

		public static bool IsMountCamel(ItemObject mountObject)
		{
			HorseComponent horseComponent;
			return (horseComponent = ((mountObject != null) ? mountObject.ItemComponent : null) as HorseComponent) != null && horseComponent.Monster.MonsterUsage == "camel";
		}

		public override void RegisterEvents()
		{
			CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener(this, new Action<Hero>(this.OnCheckForIssue));
		}

		public override void SyncData(IDataStore dataStore)
		{
		}

		private const IssueBase.IssueFrequency LordNeedsHorsesIssueFrequency = IssueBase.IssueFrequency.VeryCommon;

		public class LordNeedsHorsesIssue : IssueBase
		{
			internal static void AutoGeneratedStaticCollectObjectsLordNeedsHorsesIssue(object o, List<object> collectedObjects)
			{
				((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._mountObjectToBeDelivered);
			}

			internal static object AutoGeneratedGetMemberValue_numMountsToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o)._numMountsToBeDelivered;
			}

			internal static object AutoGeneratedGetMemberValue_mountObjectToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o)._mountObjectToBeDelivered;
			}

			internal static object AutoGeneratedGetMemberValue_mountValuePerUnit(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue)o)._mountValuePerUnit;
			}

			protected override int AlternativeSolutionBaseDurationInDaysInternal
			{
				get
				{
					return 2 + MathF.Ceiling(4f * base.IssueDifficultyMultiplier);
				}
			}

			public override IssueBase.AlternativeSolutionScaleFlag AlternativeSolutionScaleFlags
			{
				get
				{
					return IssueBase.AlternativeSolutionScaleFlag.Duration;
				}
			}

			protected override int RewardGold
			{
				get
				{
					return 500 + MathF.Ceiling(1.5f * (float)this.IssueNumMountsToBeDelivered * (float)this._mountValuePerUnit);
				}
			}

			private int IssueNumMountsToBeDelivered
			{
				get
				{
					if (this._numMountsToBeDelivered == 0)
					{
						this._numMountsToBeDelivered = MathF.Max(1 + MathF.Ceiling(12f * base.IssueDifficultyMultiplier), 2);
					}
					return this._numMountsToBeDelivered;
				}
			}

			public override int AlternativeSolutionBaseNeededMenCount
			{
				get
				{
					return 3 + MathF.Ceiling(6f * base.IssueDifficultyMultiplier);
				}
			}

			private int AlternativeSolutionGoldRequirement
			{
				get
				{
					return this.IssueNumMountsToBeDelivered * this._mountValuePerUnit;
				}
			}

			protected override int CompanionSkillRewardXP
			{
				get
				{
					return (int)(500f + 700f * base.IssueDifficultyMultiplier);
				}
			}

			public override TextObject IssueBriefByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=TBpMffcv}Campaigning this season has taken even a higher toll on {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} than it has on my men. The animals will drop dead of exhaustion while my troops soldier on. Yet if we don't keep our stocks up, the enemy will run rings around us.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			public override TextObject IssueAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=jjNSVzx3}What do you need, my {?ISSUE_GIVER.GENDER}lady{?}lord{\\?}?", null);
					textObject.SetCharacterProperties("ISSUE_GIVER", base.IssueOwner.CharacterObject, false);
					return textObject;
				}
			}

			public override TextObject IssueQuestSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=ugHO6Sa6}I need more {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}, specifically, we need {MOUNT_COUNT} and they need to be {PLURAL(MOUNT_NAME)}, because we know how to use them and how they fit our needs. Bring them to me and a bag of {REWARD}{GOLD_ICON} will be right in your pocket.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("MOUNT_COUNT", this.IssueNumMountsToBeDelivered);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					return textObject;
				}
			}

			public override TextObject IssueQuestSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=0YRl5Yie}I'll bring your {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} by myself.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			public override bool IsThereAlternativeSolution
			{
				get
				{
					return true;
				}
			}

			public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=YHG17dqZ}One of your companions who is good at haggling and riding would be appropriate for this task. {?MOUNT_TYPE_IS_CAMEL}Camels{?}Horses{\\?} should cost no more than {REQUIRED_GOLD_AMOUNT}{GOLD_ICON} denars and this should be covered by yourself. You'll also need some cavalry to bring the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}. A purse of {REWARD_GOLD_AMOUNT}{GOLD_ICON} denars will be waiting for you when you get the job done.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("REQUIRED_GOLD_AMOUNT", this.AlternativeSolutionGoldRequirement);
					textObject.SetTextVariable("REWARD_GOLD_AMOUNT", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			public override TextObject IssueAlternativeSolutionAcceptByPlayer
			{
				get
				{
					TextObject textObject = new TextObject("{=loJja04L}My men will bring your {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} as soon as possible.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			public override TextObject IssueDiscussAlternativeSolution
			{
				get
				{
					return new TextObject("{=6EJbUGpi}You will be rewarded when your companion returns with the animals we discussed.", null);
				}
			}

			public override TextObject IssueAlternativeSolutionResponseByIssueGiver
			{
				get
				{
					TextObject textObject = new TextObject("{=YF6PPWlT}Very good. I'm sure your men will bring my {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} as soon as possible.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			protected override TextObject AlternativeSolutionStartLog
			{
				get
				{
					TextObject textObject = new TextObject("{=PCigQKQ8}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} for {?QUEST_GIVER.GENDER}her{?}his{\\?} party. You asked your companion {COMPANION.LINK} and {TROOP_COUNT} of your horsemen to deliver {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK}. {?QUEST_GIVER.GENDER}She{?}He{\\?} will pay you {REWARD}{GOLD_ICON} denars when the task is done. They will rejoin your party in {RETURN_DAYS} days.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					StringHelpers.SetCharacterProperties("COMPANION", base.AlternativeSolutionHero.CharacterObject, textObject, false);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					textObject.SetTextVariable("TROOP_COUNT", this.AlternativeSolutionSentTroops.TotalManCount - 1);
					textObject.SetTextVariable("MOUNT_COUNT", this.IssueNumMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					textObject.SetTextVariable("RETURN_DAYS", MathF.Ceiling(base.AlternativeSolutionReturnTimeForTroops.RemainingDaysFromNow));
					return textObject;
				}
			}

			public override TextObject IssueAlternativeSolutionSuccessLog
			{
				get
				{
					TextObject textObject = new TextObject("{=tJc5mZua}Your companion has successfully delivered the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} {QUEST_GIVER.LINK} requested. You received {QUEST_REWARD}{GOLD_ICON} gold in return for your service.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("QUEST_REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					return textObject;
				}
			}

			public override bool IsThereLordSolution
			{
				get
				{
					return false;
				}
			}

			public override bool DoTroopsSatisfyAlternativeSolution(TroopRoster troopRoster, out TextObject explanation)
			{
				explanation = TextObject.Empty;
				return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, base.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2, true);
			}

			public override bool IsTroopTypeNeededByAlternativeSolution(CharacterObject character)
			{
				return character.Tier >= 2 && character.IsMounted;
			}

			public override bool AlternativeSolutionCondition(out TextObject explanation)
			{
				explanation = TextObject.Empty;
				return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, base.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2, true) && QuestHelper.CheckGoldForAlternativeSolution(this.AlternativeSolutionGoldRequirement, ref explanation);
			}

			public override void AlternativeSolutionStartConsequence()
			{
				Hero.MainHero.ChangeHeroGold(-this.AlternativeSolutionGoldRequirement);
			}

			protected override void AlternativeSolutionEndWithSuccessConsequence()
			{
				this.RelationshipChangeWithIssueOwner = 2;
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
			}

			protected override void AlternativeSolutionEndWithFailureConsequence()
			{
				this.RelationshipChangeWithIssueOwner = -5;
			}

			protected override void OnGameLoad()
			{
			}

			protected override QuestBase GenerateIssueQuest(string questId)
			{
				return new LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest(questId, base.IssueOwner, this.IssueNumMountsToBeDelivered, this._mountObjectToBeDelivered, this.RewardGold, CampaignTime.DaysFromNow(20f));
			}

			public override IssueBase.IssueFrequency GetFrequency()
			{
				return IssueBase.IssueFrequency.VeryCommon;
			}

			protected override bool CanPlayerTakeQuestConditions(Hero issueGiver, out IssueBase.PreconditionFlags flag, out Hero relationHero, out SkillObject skill)
			{
				flag = IssueBase.PreconditionFlags.None;
				skill = null;
				relationHero = null;
				if (issueGiver.GetRelationWithPlayer() < -10f)
				{
					relationHero = issueGiver;
					flag |= IssueBase.PreconditionFlags.Relation;
				}
				if (Hero.MainHero.MapFaction.IsKingdomFaction && Hero.MainHero.IsFactionLeader)
				{
					flag |= IssueBase.PreconditionFlags.MainHeroIsKingdomLeader;
				}
				if (issueGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					flag |= IssueBase.PreconditionFlags.AtWar;
				}
				return flag == IssueBase.PreconditionFlags.None;
			}

			protected override void CompleteIssueWithTimedOutConsequences()
			{
			}

			public override bool IssueStayAliveConditions()
			{
				int num;
				return !base.IssueOwner.IsDead && base.IssueOwner.PartyBelongedTo != null && base.IssueOwner.Clan != Clan.PlayerClan && (base.IssueOwner.IsFactionLeader || base.IssueOwner.Clan.Leader == base.IssueOwner) && LordNeedsHorsesIssueBehavior.ComputeMountsOverInfantryCountRatio(base.IssueOwner.PartyBelongedTo, out num) < 0.8f;
			}

			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=5zF6vI5s}Lord Needs {?MOUNT_TYPE_IS_CAMEL}Camels{?}Horses{\\?}", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			public override TextObject Description
			{
				get
				{
					TextObject textObject = new TextObject("{=GHbM1i6R}{QUEST_GIVER.LINK} needs {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to speed up {?QUEST_GIVER.GENDER}her{?}his{\\?} party.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.IssueOwner.CharacterObject, textObject, false);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			public LordNeedsHorsesIssue(Hero issueOwner)
				: base(issueOwner, CampaignTime.DaysFromNow(20f))
			{
				MBList<ItemObject> mblist = new MBList<ItemObject>();
				foreach (ItemObject itemObject in Items.All)
				{
					if (itemObject.IsMountable && itemObject.Culture == issueOwner.Culture && !itemObject.NotMerchandise && (itemObject.Tier == ItemObject.ItemTiers.Tier1 || itemObject.Tier == ItemObject.ItemTiers.Tier2))
					{
						mblist.Add(itemObject);
					}
				}
				this._mountObjectToBeDelivered = mblist.GetRandomElement<ItemObject>();
				this._numMountsToBeDelivered = MathF.Max(1 + MathF.Ceiling(12f * base.IssueDifficultyMultiplier), 2);
				if (this._mountObjectToBeDelivered == null)
				{
					this._mountObjectToBeDelivered = MBObjectManager.Instance.GetObject<ItemObject>("sumpter_horse");
				}
				ItemObject mountObjectToBeDelivered = this._mountObjectToBeDelivered;
				this._mountValuePerUnit = ((mountObjectToBeDelivered != null) ? mountObjectToBeDelivered.Value : 0);
			}

			protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
			{
				if (issueEffect == DefaultIssueEffects.ClanInfluence)
				{
					return -0.1f;
				}
				return 0f;
			}

			public override ValueTuple<SkillObject, int> GetAlternativeSolutionSkill(Hero hero)
			{
				return new ValueTuple<SkillObject, int>((hero.GetSkillValue(DefaultSkills.Trade) >= hero.GetSkillValue(DefaultSkills.Riding)) ? DefaultSkills.Trade : DefaultSkills.Riding, 120);
			}

			private const int IssueDueTimeInDays = 20;

			internal const int IssueGiverMinimumPartySize = 50;

			internal const int IssueGiverMinimumInfantryCount = 10;

			internal const float IssuePreConditionMinPlayerRelation = -10f;

			internal const float IssuePreConditionMountsOverInfantryRatioThreshold = 0.6f;

			internal const float IssueStayingAliveMountsOverInfantryRatioThreshold = 0.8f;

			private const int AlternativeSolutionCompanionSkillThreshold = 120;

			private const int AlternativeSolutionRenownRewardOnSuccess = 1;

			private const int AlternativeSolutionRelationRewardOnSuccess = 2;

			private const int AlternativeSolutionRelationPenaltyOnFail = -5;

			private const int AlternativeSolutionTroopTierRequirement = 2;

			[SaveableField(4)]
			private int _numMountsToBeDelivered;

			[SaveableField(2)]
			private readonly ItemObject _mountObjectToBeDelivered;

			[SaveableField(3)]
			private readonly int _mountValuePerUnit;
		}

		public class LordNeedsHorsesIssueQuest : QuestBase
		{
			internal static void AutoGeneratedStaticCollectObjectsLordNeedsHorsesIssueQuest(object o, List<object> collectedObjects)
			{
				((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
			}

			protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
			{
				base.AutoGeneratedInstanceCollectObjects(collectedObjects);
				collectedObjects.Add(this._mountObjectToBeDelivered);
				collectedObjects.Add(this._questJournalEntry);
			}

			internal static object AutoGeneratedGetMemberValue_numMountsToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o)._numMountsToBeDelivered;
			}

			internal static object AutoGeneratedGetMemberValue_mountObjectToBeDelivered(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o)._mountObjectToBeDelivered;
			}

			internal static object AutoGeneratedGetMemberValue_questJournalEntry(object o)
			{
				return ((LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest)o)._questJournalEntry;
			}

			public override TextObject Title
			{
				get
				{
					TextObject textObject = new TextObject("{=5zF6vI5s}Lord Needs {?MOUNT_TYPE_IS_CAMEL}Camels{?}Horses{\\?}", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					return textObject;
				}
			}

			private TextObject _journalTaskName
			{
				get
				{
					TextObject textObject = new TextObject("{=plHZYtxF}{PLURAL(REQUESTED_MOUNT_NAME)} in Inventory: ", null);
					textObject.SetTextVariable("REQUESTED_MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					return textObject;
				}
			}

			private TextObject _onQuestStartedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=GQ96SX4M}{QUEST_GIVER.LINK} told you that {?QUEST_GIVER.GENDER}she{?}he{\\?} needs {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} for {?QUEST_GIVER.GENDER}her{?}his{\\?} party. {?QUEST_GIVER.GENDER}She{?}He{\\?} asked you to bring {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {?QUEST_GIVER.GENDER}her{?}him{\\?}. {?QUEST_GIVER.GENDER}She{?}He{\\?} will pay you {REWARD_GOLD}{GOLD_ICON} denars when the task is done.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					textObject.SetTextVariable("REWARD_GOLD", this.RewardGold);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestSucceededLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=aGvLxsub}You have successfully delivered {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK} as requested. You received {GOLD_REWARD}{GOLD_ICON} denars in return for your service.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					textObject.SetTextVariable("GOLD_REWARD", this.RewardGold);
					textObject.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
					return textObject;
				}
			}

			private TextObject _onQuestFailedLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=yLuzvTtd}You had promised to deliver {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK}. But you've failed to complete this task. {QUEST_GIVER.LINK} was displeased.", null);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestTimedOutLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=BFEYIMdi}You had promised to deliver {MOUNT_COUNT} {PLURAL(MOUNT_NAME)} to {QUEST_GIVER.LINK}. But you've failed to complete this task in time. {QUEST_GIVER.LINK} was displeased.", null);
					textObject.SetTextVariable("MOUNT_COUNT", this._numMountsToBeDelivered);
					textObject.SetTextVariable("MOUNT_NAME", this._mountObjectToBeDelivered.Name);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestCancelled1LogText
			{
				get
				{
					TextObject textObject = new TextObject("{=MKBWG06O}{QUEST_GIVER.LINK} had died and your agreement with {?QUEST_GIVER.GENDER}her{?}him{\\?} was canceled. You can no longer deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestCancelled2LogText
			{
				get
				{
					TextObject textObject = new TextObject("{=pYgl86Cr}Your clan had entered a war with the {QUEST_GIVER.LINK}'s faction. Your agreement was canceled. You can no longer deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _playerDeclaredWarQuestLogText
			{
				get
				{
					TextObject textObject = new TextObject("{=bqeWVVEE}Your actions have started a war with {QUEST_GIVER.LINK}'s faction. {?QUEST_GIVER.GENDER}She{?}He{\\?} cancels your agreement and the quest is a failure.", null);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestCancelled3LogText
			{
				get
				{
					TextObject textObject = new TextObject("{=qEh4gdjU}{QUEST_GIVER.LINK} was imprisoned and your agreement with {?QUEST_GIVER.GENDER}her{?}him{\\?} was canceled. You can no longer deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} to {?QUEST_GIVER.GENDER}her{?}him{\\?}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestMountRequirementSatisfiedQuickText
			{
				get
				{
					TextObject textObject = new TextObject("{=ZCPrYXaO}You have enough {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}. Return back to {QUEST_GIVER.LINK}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			private TextObject _onQuestMountRequirementNotSatisfiedQuickText
			{
				get
				{
					TextObject textObject = new TextObject("{=aFNfxhwz}You no longer have enough {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} for {QUEST_GIVER.LINK}.", null);
					textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
					StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject, false);
					return textObject;
				}
			}

			public override bool IsRemainingTimeHidden
			{
				get
				{
					return false;
				}
			}

			public LordNeedsHorsesIssueQuest(string questId, Hero questGiver, int numMountsToBeDelivered, ItemObject mountObjectToBeDelivered, int rewardGold, CampaignTime duration)
				: base(questId, questGiver, duration, rewardGold)
			{
				this._numMountsToBeDelivered = numMountsToBeDelivered;
				this._mountObjectToBeDelivered = mountObjectToBeDelivered;
				this._playerInventoryVersionNo = MobileParty.MainParty.ItemRoster.VersionNo;
				base.AddTrackedObject(base.QuestGiver);
				this.SetDialogs();
				base.InitializeQuestOnCreation();
			}

			protected override void InitializeQuestOnGameLoad()
			{
				this.SetDialogs();
				this._numMountsInInventory = this.GetNumQuestMountsInInventory();
				this._playerInventoryVersionNo = MobileParty.MainParty.ItemRoster.VersionNo;
				if (this._questJournalEntry == null)
				{
					this._questJournalEntry = base.JournalEntries.FirstOrDefault((JournalLog x) => x.Range == this._numMountsToBeDelivered && x.Type == LogType.Discreate);
					if (this._questJournalEntry == null)
					{
						if (base.JournalEntries.Count > 0)
						{
							for (int i = 0; i < base.JournalEntries.Count; i++)
							{
								if (base.JournalEntries[i].Type == LogType.Discreate)
								{
									base.RemoveLog(base.JournalEntries[i]);
								}
							}
							this._questJournalEntry = base.AddDiscreteLog(this._onQuestStartedLogText, this._journalTaskName, MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered), this._numMountsToBeDelivered, null, false);
						}
						else
						{
							this._questJournalEntry = base.AddDiscreteLog(this._onQuestStartedLogText, this._journalTaskName, MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered), this._numMountsToBeDelivered, null, false);
						}
					}
				}
				this.UpdateQuestJournalEntry();
			}

			protected override void SetDialogs()
			{
				this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start", 100).NpcLine("{=qR3gQrLi}Splendid. We'll need to keep moving around, though, so it might be tricky to find us. My fellow nobles will usually know where to find me though, if you ask them.", null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(this.OnQuestAccepted))
					.CloseDialog();
				new TextObject(LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? "{=nysBXpEO}camels" : "{=6YbGQDme}horses", null);
				TextObject textObject = new TextObject("{=bmW77NvO}What about my {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?}?", null);
				textObject.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				TextObject textObject2 = new TextObject("{=TLcnbALt}Here are your {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}.", null);
				textObject2.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				StringHelpers.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter, textObject2, false);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject2, false);
				TextObject textObject3 = new TextObject("{=6bt9jYai}I am still looking for the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} you have requested.", null);
				textObject3.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				TextObject textObject4 = new TextObject("{=pV7DLTAu}I am sorry, my {?QUEST_GIVER.GENDER}lady{?}lord{\\?}. I cannot deliver the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} you requested.", null);
				textObject4.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				StringHelpers.SetCharacterProperties("QUEST_GIVER", base.QuestGiver.CharacterObject, textObject4, false);
				TextObject textObject5 = new TextObject("{=inkr6Dzy}Too bad. Perhaps someone else will be able to get me the {?MOUNT_TYPE_IS_CAMEL}camels{?}horses{\\?} that I need.", null);
				textObject5.SetTextVariable("MOUNT_TYPE_IS_CAMEL", LordNeedsHorsesIssueBehavior.IsMountCamel(this._mountObjectToBeDelivered) ? 1 : 0);
				this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss", 100).NpcLine(textObject, null, null).Condition(() => Hero.OneToOneConversationHero == base.QuestGiver)
					.Consequence(delegate
					{
						Campaign.Current.ConversationManager.ConversationEndOneShot += MapEventHelper.OnConversationEnd;
					})
					.BeginPlayerOptions()
					.PlayerOption(textObject2, null)
					.Condition(() => this.GetNumQuestMountsInInventory() >= this._numMountsToBeDelivered)
					.NpcLine("{=9HJbLneH}Thank you for your help, {PLAYER.NAME}. Here is the purse I promised you. Farewell.", null, null)
					.Consequence(new ConversationSentence.OnConsequenceDelegate(base.CompleteQuestWithSuccess))
					.CloseDialog()
					.PlayerOption(textObject3, null)
					.NpcLine("{=cH0iAEfq}Please take care of this as quickly as you can. I need those animals.", null, null)
					.CloseDialog()
					.PlayerOption(textObject4, null)
					.NpcLine(textObject5, null, null)
					.Consequence(delegate
					{
						this.OnQuestDeclined();
					})
					.CloseDialog()
					.EndPlayerOptions();
			}

			private void OnQuestAccepted()
			{
				base.StartQuest();
				this._numMountsInInventory = this.GetNumQuestMountsInInventory();
				this._questJournalEntry = base.AddDiscreteLog(this._onQuestStartedLogText, this._journalTaskName, MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered), this._numMountsToBeDelivered, null, false);
			}

			private void OnQuestDeclined()
			{
				base.AddLog(this._onQuestFailedLogText, false);
				base.CompleteQuestWithFail(null);
			}

			protected override void RegisterEvents()
			{
				CampaignEvents.HourlyTickEvent.AddNonSerializedListener(this, new Action(this.OnHourlyTickEvent));
				CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener(this, new Action<List<ValueTuple<ItemRosterElement, int>>, List<ValueTuple<ItemRosterElement, int>>, bool>(this.OnPlayerInventoryExchange));
				CampaignEvents.WarDeclared.AddNonSerializedListener(this, new Action<IFaction, IFaction, DeclareWarAction.DeclareWarDetail>(this.OnWarDeclared));
				CampaignEvents.ClanChangedKingdom.AddNonSerializedListener(this, new Action<Clan, Kingdom, Kingdom, ChangeKingdomAction.ChangeKingdomActionDetail, bool>(this.OnClanChangedKingdom));
				CampaignEvents.HeroKilledEvent.AddNonSerializedListener(this, new Action<Hero, Hero, KillCharacterAction.KillCharacterActionDetail, bool>(this.OnHeroKilled));
				CampaignEvents.HeroPrisonerTaken.AddNonSerializedListener(this, new Action<PartyBase, Hero>(this.OnHeroPrisonerTaken));
				CampaignEvents.MapEventStarted.AddNonSerializedListener(this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
			}

			private void OnMapEventStarted(MapEvent mapEvent, PartyBase attackerParty, PartyBase defenderParty)
			{
				if (QuestHelper.CheckMinorMajorCoercion(this, mapEvent, attackerParty))
				{
					QuestHelper.ApplyGenericMinorMajorCoercionConsequences(this, mapEvent);
				}
			}

			private void UpdateQuestJournalEntry()
			{
				int num = MBMath.ClampInt(this._numMountsInInventory, 0, this._numMountsToBeDelivered);
				if (num != this._questJournalEntry.CurrentProgress)
				{
					base.UpdateQuestTaskStage(this._questJournalEntry, num);
				}
			}

			private void CheckAndHandleQuestSuccessConditions()
			{
				int numQuestMountsInInventory = this.GetNumQuestMountsInInventory();
				if (numQuestMountsInInventory != this._numMountsInInventory)
				{
					if (this._numMountsInInventory < this._numMountsToBeDelivered && numQuestMountsInInventory >= this._numMountsToBeDelivered)
					{
						MBInformationManager.AddQuickInformation(this._onQuestMountRequirementSatisfiedQuickText, 0, null, "");
					}
					else if (this._numMountsInInventory >= this._numMountsToBeDelivered && numQuestMountsInInventory < this._numMountsToBeDelivered)
					{
						MBInformationManager.AddQuickInformation(this._onQuestMountRequirementNotSatisfiedQuickText, 0, null, "");
					}
					this._numMountsInInventory = numQuestMountsInInventory;
					this.UpdateQuestJournalEntry();
				}
			}

			private void OnHourlyTickEvent()
			{
				int versionNo = MobileParty.MainParty.ItemRoster.VersionNo;
				if (this._playerInventoryVersionNo != versionNo)
				{
					this.CheckAndHandleQuestSuccessConditions();
					this._playerInventoryVersionNo = versionNo;
				}
			}

			private void OnPlayerInventoryExchange(List<ValueTuple<ItemRosterElement, int>> purchasedItems, List<ValueTuple<ItemRosterElement, int>> soldItems, bool isTrading)
			{
				bool flag = false;
				foreach (ValueTuple<ItemRosterElement, int> valueTuple in purchasedItems)
				{
					ItemRosterElement itemRosterElement = valueTuple.Item1;
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						flag = true;
						break;
					}
				}
				bool flag2 = false;
				foreach (ValueTuple<ItemRosterElement, int> valueTuple2 in soldItems)
				{
					ItemRosterElement itemRosterElement = valueTuple2.Item1;
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						flag2 = true;
						break;
					}
				}
				if (flag || flag2)
				{
					this.CheckAndHandleQuestSuccessConditions();
				}
				this._playerInventoryVersionNo = MobileParty.MainParty.ItemRoster.VersionNo;
			}

			private void OnHeroKilled(Hero victim, Hero killer, KillCharacterAction.KillCharacterActionDetail detail, bool showNotification)
			{
				if (victim == base.QuestGiver)
				{
					base.CompleteQuestWithCancel(this._onQuestCancelled1LogText);
				}
			}

			private void OnHeroPrisonerTaken(PartyBase capturer, Hero prisoner)
			{
				if (prisoner == base.QuestGiver)
				{
					base.CompleteQuestWithCancel(this._onQuestCancelled3LogText);
				}
			}

			private void OnClanChangedKingdom(Clan clan, Kingdom oldKingdom, Kingdom newKingdom, ChangeKingdomAction.ChangeKingdomActionDetail detail, bool showNotification = true)
			{
				if (base.QuestGiver.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
				{
					base.CompleteQuestWithCancel(this._onQuestCancelled2LogText);
				}
			}

			private void OnWarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
			{
				QuestHelper.CheckWarDeclarationAndFailOrCancelTheQuest(this, faction1, faction2, detail, this._playerDeclaredWarQuestLogText, this._onQuestCancelled2LogText);
			}

			protected override void OnCompleteWithSuccess()
			{
				base.AddLog(this._onQuestSucceededLogText, false);
				int num = this._numMountsToBeDelivered;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						int amount = itemRosterElement.Amount;
						if (amount >= num)
						{
							this.GiveMounts(Hero.MainHero, base.QuestGiver, itemRosterElement, num);
							break;
						}
						num -= amount;
						this.GiveMounts(Hero.MainHero, base.QuestGiver, itemRosterElement, amount);
					}
				}
				GainRenownAction.Apply(Hero.MainHero, 1f, false);
				GiveGoldAction.ApplyForQuestBetweenCharacters(base.QuestGiver, Hero.MainHero, this.RewardGold, false);
				this.RelationshipChangeWithQuestGiver = 2;
			}

			private void GiveMounts(Hero giver, Hero receiver, ItemRosterElement item, int count)
			{
				if (giver.PartyBelongedTo != null)
				{
					giver.PartyBelongedTo.Party.ItemRoster.AddToCounts(item.EquipmentElement, -count);
					if (receiver.PartyBelongedTo != null)
					{
						receiver.PartyBelongedTo.Party.ItemRoster.AddToCounts(item.EquipmentElement, count);
					}
				}
			}

			protected override void OnFinalize()
			{
				base.RemoveTrackedObject(base.QuestGiver);
			}

			public override void OnFailed()
			{
				this.RelationshipChangeWithQuestGiver = -3;
			}

			protected override void OnTimedOut()
			{
				base.AddLog(this._onQuestTimedOutLogText, false);
				this.RelationshipChangeWithQuestGiver = -5;
			}

			private int GetNumQuestMountsInInventory()
			{
				int num = 0;
				foreach (ItemRosterElement itemRosterElement in MobileParty.MainParty.ItemRoster)
				{
					if (itemRosterElement.EquipmentElement.Item == this._mountObjectToBeDelivered)
					{
						num += itemRosterElement.Amount;
					}
				}
				return num;
			}

			private const int RenownChangeOnSuccess = 1;

			private const int RelationChangeOnSuccess = 2;

			private const int RelationChangeOnFailure = -3;

			private const int RelationChangeOnTimeOut = -5;

			[SaveableField(1)]
			private readonly int _numMountsToBeDelivered;

			[SaveableField(2)]
			private readonly ItemObject _mountObjectToBeDelivered;

			[SaveableField(3)]
			private JournalLog _questJournalEntry;

			private int _numMountsInInventory;

			private int _playerInventoryVersionNo;
		}

		public class LordNeedsHorsesIssueBehaviorTypeDefiner : CampaignBehaviorBase.SaveableCampaignBehaviorTypeDefiner
		{
			public LordNeedsHorsesIssueBehaviorTypeDefiner()
				: base(510000)
			{
			}

			protected override void DefineClassTypes()
			{
				base.AddClassDefinition(typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssue), 1, null);
				base.AddClassDefinition(typeof(LordNeedsHorsesIssueBehavior.LordNeedsHorsesIssueQuest), 2, null);
			}

			protected override void DefineEnumTypes()
			{
			}
		}
	}
}
