using System;
using System.Collections.Generic;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	public abstract class WarPartyComponent : PartyComponent
	{
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		public Clan Clan
		{
			get
			{
				return base.Party.MobileParty.ActualClan;
			}
		}

		protected override void OnInitialize()
		{
			this.Clan.OnWarPartyAdded(this);
		}

		protected override void OnFinalize()
		{
			this.Clan.OnWarPartyRemoved(this);
		}

		internal void OnClanChange(Clan oldClan, Clan newClan)
		{
			oldClan.OnWarPartyRemoved(this);
			newClan.OnWarPartyAdded(this);
		}
	}
}
