using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.BarterSystem.Barterables
{
	public class FiefBarterable : Barterable
	{
		public override string StringID
		{
			get
			{
				return "fief_barterable";
			}
		}

		public Settlement TargetSettlement
		{
			get
			{
				return this._settlement;
			}
		}

		public override TextObject Name
		{
			get
			{
				return this._settlement.Name;
			}
		}

		public FiefBarterable(Settlement settlement, Hero owner, Hero heroOfferedTo)
			: base(owner, null)
		{
			this._settlement = settlement;
			this._heroOfferedTo = heroOfferedTo;
		}

		public override int GetUnitValueForFaction(IFaction faction)
		{
			float num = 1f;
			if (faction == this._heroOfferedTo.Clan)
			{
				num = 1f;
			}
			else if (faction == base.OriginalOwner.Clan)
			{
				num = -1f;
			}
			else if (faction.MapFaction == this._heroOfferedTo.MapFaction)
			{
				num = 1f;
			}
			else if (faction.MapFaction == base.OriginalOwner.MapFaction)
			{
				num = -1f;
			}
			float num2 = Campaign.Current.Models.SettlementValueModel.CalculateSettlementValueForFaction(this._settlement, faction);
			return (int)(num * num2);
		}

		public override ImageIdentifier GetVisualIdentifier()
		{
			return null;
		}

		public override string GetEncyclopediaLink()
		{
			return this.TargetSettlement.EncyclopediaLink;
		}

		public override void Apply()
		{
			ChangeOwnerOfSettlementAction.ApplyByBarter(this._heroOfferedTo, this._settlement);
		}

		internal static void AutoGeneratedStaticCollectObjectsFiefBarterable(object o, List<object> collectedObjects)
		{
			((FiefBarterable)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this._settlement);
			collectedObjects.Add(this._heroOfferedTo);
		}

		internal static object AutoGeneratedGetMemberValue_settlement(object o)
		{
			return ((FiefBarterable)o)._settlement;
		}

		internal static object AutoGeneratedGetMemberValue_heroOfferedTo(object o)
		{
			return ((FiefBarterable)o)._heroOfferedTo;
		}

		[SaveableField(100)]
		private readonly Settlement _settlement;

		[SaveableField(101)]
		private readonly Hero _heroOfferedTo;
	}
}
