using System;
using System.Collections.Generic;
using TaleWorlds.Core;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.MapNotificationTypes
{
	public class MercenaryOfferMapNotification : InformationData
	{
		internal static void AutoGeneratedStaticCollectObjectsMercenaryOfferMapNotification(object o, List<object> collectedObjects)
		{
			((MercenaryOfferMapNotification)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.OfferedKingdom);
		}

		internal static object AutoGeneratedGetMemberValueOfferedKingdom(object o)
		{
			return ((MercenaryOfferMapNotification)o).OfferedKingdom;
		}

		public override TextObject TitleText
		{
			get
			{
				return new TextObject("{=z7y35aPE}Mercenary Offer", null);
			}
		}

		public override string SoundEventPath
		{
			get
			{
				return "event:/ui/notification/kingdom_decision";
			}
		}

		[SaveableProperty(1)]
		public Kingdom OfferedKingdom { get; private set; }

		public MercenaryOfferMapNotification(Kingdom offeredKingdom, TextObject descriptionText)
			: base(descriptionText)
		{
			this.OfferedKingdom = offeredKingdom;
		}
	}
}
