using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Siege
{
	public class BesiegerCamp : ISiegeEventSide
	{
		internal static void AutoGeneratedStaticCollectObjectsBesiegerCamp(object o, List<object> collectedObjects)
		{
			((BesiegerCamp)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(this._besiegerParties);
			collectedObjects.Add(this._siegeEngineMissiles);
			collectedObjects.Add(this.SiegeEvent);
			collectedObjects.Add(this.SiegeEngines);
			collectedObjects.Add(this.SiegeStrategy);
		}

		internal static object AutoGeneratedGetMemberValueSiegeEvent(object o)
		{
			return ((BesiegerCamp)o).SiegeEvent;
		}

		internal static object AutoGeneratedGetMemberValueSiegeEngines(object o)
		{
			return ((BesiegerCamp)o).SiegeEngines;
		}

		internal static object AutoGeneratedGetMemberValueSiegeStrategy(object o)
		{
			return ((BesiegerCamp)o).SiegeStrategy;
		}

		internal static object AutoGeneratedGetMemberValueNumberOfTroopsKilledOnSide(object o)
		{
			return ((BesiegerCamp)o).NumberOfTroopsKilledOnSide;
		}

		internal static object AutoGeneratedGetMemberValueIsAttackersVulnerable(object o)
		{
			return ((BesiegerCamp)o).IsAttackersVulnerable;
		}

		internal static object AutoGeneratedGetMemberValue_besiegerParties(object o)
		{
			return ((BesiegerCamp)o)._besiegerParties;
		}

		internal static object AutoGeneratedGetMemberValue_siegeEngineMissiles(object o)
		{
			return ((BesiegerCamp)o)._siegeEngineMissiles;
		}

		internal static object AutoGeneratedGetMemberValue_attackerVulnerableDurationLeft(object o)
		{
			return ((BesiegerCamp)o)._attackerVulnerableDurationLeft;
		}

		internal static object AutoGeneratedGetMemberValue_attackerVulnerableDayCount(object o)
		{
			return ((BesiegerCamp)o)._attackerVulnerableDayCount;
		}

		internal static object AutoGeneratedGetMemberValue_attackerVulnerableDueTime(object o)
		{
			return ((BesiegerCamp)o)._attackerVulnerableDueTime;
		}

		[SaveableProperty(6)]
		public SiegeEvent SiegeEvent { get; private set; }

		[SaveableProperty(7)]
		public SiegeEvent.SiegeEnginesContainer SiegeEngines { get; private set; }

		public MobileParty BesiegerParty
		{
			get
			{
				if (this._besiegerParties.Count <= 0)
				{
					return null;
				}
				return this._besiegerParties[0];
			}
		}

		public IEnumerable<PartyBase> GetInvolvedPartiesForEventType(MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
		{
			foreach (MobileParty mobileParty in this._besiegerParties)
			{
				yield return mobileParty.Party;
			}
			List<MobileParty>.Enumerator enumerator = default(List<MobileParty>.Enumerator);
			yield break;
			yield break;
		}

		public PartyBase GetNextInvolvedPartyForEventType(ref int partyIndex, MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
		{
			partyIndex++;
			if (partyIndex >= this._besiegerParties.Count)
			{
				return null;
			}
			return this._besiegerParties[partyIndex].Party;
		}

		public bool HasInvolvedPartyForEventType(PartyBase party, MapEvent.BattleTypes mapEventType = MapEvent.BattleTypes.Siege)
		{
			using (List<MobileParty>.Enumerator enumerator = this._besiegerParties.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					if (enumerator.Current.Party == party)
					{
						return true;
					}
				}
			}
			return false;
		}

		public BattleSideEnum BattleSide
		{
			get
			{
				return BattleSideEnum.Attacker;
			}
		}

		public MBReadOnlyList<SiegeEvent.SiegeEngineMissile> SiegeEngineMissiles
		{
			get
			{
				return this._siegeEngineMissiles;
			}
		}

		[SaveableProperty(10)]
		public SiegeStrategy SiegeStrategy { get; private set; }

		[SaveableProperty(11)]
		public int NumberOfTroopsKilledOnSide { get; private set; }

		[SaveableProperty(13)]
		public bool IsAttackersVulnerable { get; private set; }

		public BesiegerCamp(SiegeEvent siegeEvent)
		{
			this._besiegerParties = new List<MobileParty>();
			this.SiegeEvent = siegeEvent;
		}

		public bool IsBesiegerSideParty(MobileParty mobileParty)
		{
			Func<MobileParty, bool> <>9__1;
			return this.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege).Any(delegate(PartyBase t)
			{
				if (t != mobileParty.Party)
				{
					IEnumerable<MobileParty> attachedParties = t.MobileParty.AttachedParties;
					Func<MobileParty, bool> func;
					if ((func = <>9__1) == null)
					{
						func = (<>9__1 = (MobileParty k) => k == mobileParty);
					}
					return attachedParties.Any(func);
				}
				return true;
			});
		}

		private float PreparationProgress
		{
			get
			{
				SiegeEvent.SiegeEnginesContainer siegeEngines = this.SiegeEngines;
				float? num;
				if (siegeEngines == null)
				{
					num = null;
				}
				else
				{
					SiegeEvent.SiegeEngineConstructionProgress siegePreparations = siegeEngines.SiegePreparations;
					num = ((siegePreparations != null) ? new float?(siegePreparations.Progress) : null);
				}
				float? num2 = num;
				if (num2 == null)
				{
					return 0f;
				}
				return num2.GetValueOrDefault();
			}
		}

		public bool IsPreparationComplete
		{
			get
			{
				return this.PreparationProgress >= 1f;
			}
		}

		public bool IsReadyToBesiege
		{
			get
			{
				return this.IsPreparationComplete && this.StartingAssaultOnBesiegedSettlementIsLogical();
			}
		}

		public void InitializeSiegeEventSide()
		{
			this.SiegeStrategy = DefaultSiegeStrategies.Custom;
			this.NumberOfTroopsKilledOnSide = 0;
			SiegeEvent.SiegeEngineConstructionProgress siegeEngineConstructionProgress = new SiegeEvent.SiegeEngineConstructionProgress(DefaultSiegeEngineTypes.Preparations, this.PreparationProgress, (float)DefaultSiegeEngineTypes.Preparations.BaseHitPoints);
			siegeEngineConstructionProgress.Activate(true);
			this.SiegeEngines = new SiegeEvent.SiegeEnginesContainer(BattleSideEnum.Attacker, siegeEngineConstructionProgress);
			this._siegeEngineMissiles = new MBList<SiegeEvent.SiegeEngineMissile>();
			this.SetPrebuiltSiegeEngines();
		}

		public void OnTroopsKilledOnSide(int killCount)
		{
			this.NumberOfTroopsKilledOnSide += killCount;
		}

		public void SetSiegeStrategy(SiegeStrategy strategy)
		{
			this.SiegeStrategy = strategy;
		}

		internal void AddSiegePartyInternal(MobileParty mobileParty)
		{
			this._besiegerParties.Add(mobileParty);
			if (this._besiegerParties.Count == 1)
			{
				this.SiegeEvent.BesiegedSettlement.LastAttackerParty = mobileParty;
			}
		}

		internal void RemoveSiegePartyInternal(MobileParty mobileParty)
		{
			this._besiegerParties.Remove(mobileParty);
			if (mobileParty != null)
			{
				this.OnPartyLeftSiege(mobileParty);
			}
			if (this._besiegerParties.Count == 0)
			{
				this.SiegeEvent.FinalizeSiegeEvent();
			}
		}

		public void RemoveAllSiegeParties()
		{
			MapEvent mapEvent = this.SiegeEvent.BesiegedSettlement.Party.MapEvent;
			if (mapEvent != null && mapEvent.IsSiegeAssault && !mapEvent.IsFinished)
			{
				Debug.FailedAssert("RemoveAllParties called before mapEvent is cleared", "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Siege\\BesiegerCamp.cs", "RemoveAllSiegeParties", 162);
			}
			while (this._besiegerParties.Count > 0)
			{
				this._besiegerParties[0].BesiegerCamp = null;
			}
		}

		public void Tick(float dt)
		{
			bool flag = false;
			if (this._attackerVulnerableDurationLeft > 0f)
			{
				this._attackerVulnerableDurationLeft -= dt;
				flag = true;
			}
			else if (this._attackerVulnerableDueTime > 0f)
			{
				this._attackerVulnerableDueTime -= dt;
				if (this._attackerVulnerableDueTime <= 0f)
				{
					this._attackerVulnerableDurationLeft = Campaign.Current.Models.PartyImpairmentModel.GetVulnerabilityStateDuration(this.BesiegerParty.Party);
					flag = true;
				}
			}
			else if (this._attackerVulnerableDayCount < this.SiegeEvent.SiegeStartTime.ElapsedDaysUntilNow)
			{
				this._attackerVulnerableDayCount = this.SiegeEvent.SiegeStartTime.ElapsedDaysUntilNow;
				this._attackerVulnerableDueTime = Campaign.Current.Models.PartyImpairmentModel.GetSiegeExpectedVulnerabilityTime();
			}
			this.IsAttackersVulnerable = flag;
		}

		public void OnPartyLeftSiege(MobileParty mobileParty)
		{
			if (mobileParty == MobileParty.MainParty && PlayerSiege.PlayerSiegeEvent != null)
			{
				PlayerSiege.ClosePlayerSiege();
			}
			if (Campaign.Current.Models.PartyImpairmentModel.CanGetDisorganized(mobileParty.Party))
			{
				mobileParty.SetDisorganized(true);
			}
			if (this._besiegerParties.Contains(MobileParty.MainParty) && (MobileParty.MainParty.MapEvent == null || !MobileParty.MainParty.MapEvent.HasWinner))
			{
				Campaign.Current.TimeControlMode = CampaignTimeControlMode.Stop;
				MenuContext currentMenuContext = Campaign.Current.CurrentMenuContext;
				if (currentMenuContext == null)
				{
					return;
				}
				currentMenuContext.Refresh();
			}
		}

		internal void SetSiegeCampPartyPosition(MobileParty mobileParty)
		{
			ReadOnlyCollection<MatrixFrame> siegeCamp1GlobalFrames = this.SiegeEvent.BesiegedSettlement.Party.Visuals.GetSiegeCamp1GlobalFrames();
			ReadOnlyCollection<MatrixFrame> siegeCamp2GlobalFrames = this.SiegeEvent.BesiegedSettlement.Party.Visuals.GetSiegeCamp2GlobalFrames();
			int num = 0;
			Vec2 vec2;
			bool flag;
			do
			{
				int num2 = MBRandom.RandomInt(siegeCamp1GlobalFrames.Count);
				float randomFloat = MBRandom.RandomFloat;
				float randomFloat2 = MBRandom.RandomFloat;
				MatrixFrame matrixFrame = siegeCamp1GlobalFrames[num2];
				Vec2 asVec = matrixFrame.origin.AsVec2;
				float num3 = randomFloat;
				matrixFrame = siegeCamp1GlobalFrames[num2];
				Vec2 vec = asVec + num3 * matrixFrame.rotation.s.AsVec2;
				float num4 = randomFloat2;
				matrixFrame = siegeCamp1GlobalFrames[num2];
				vec2 = vec + num4 * matrixFrame.rotation.f.AsVec2;
				flag = false;
				foreach (PartyBase partyBase in this.SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege))
				{
					if ((vec2 - partyBase.MobileParty.VisualPosition2DWithoutError).LengthSquared < 0.25f)
					{
						flag = true;
						break;
					}
				}
				num++;
			}
			while (flag && num < 20);
			if (num == 20 && siegeCamp2GlobalFrames != null && siegeCamp2GlobalFrames.Count > 0)
			{
				num = 0;
				do
				{
					int num5 = MBRandom.RandomInt(siegeCamp2GlobalFrames.Count);
					float randomFloat3 = MBRandom.RandomFloat;
					float randomFloat4 = MBRandom.RandomFloat;
					MatrixFrame matrixFrame = siegeCamp2GlobalFrames[num5];
					Vec2 asVec2 = matrixFrame.origin.AsVec2;
					float num6 = randomFloat3;
					matrixFrame = siegeCamp2GlobalFrames[num5];
					Vec2 vec3 = asVec2 + num6 * matrixFrame.rotation.s.AsVec2;
					float num7 = randomFloat4;
					matrixFrame = siegeCamp2GlobalFrames[num5];
					vec2 = vec3 + num7 * matrixFrame.rotation.f.AsVec2;
					flag = false;
					foreach (PartyBase partyBase2 in this.SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege))
					{
						if ((vec2 - partyBase2.MobileParty.VisualPosition2DWithoutError).LengthSquared < 0.25f)
						{
							flag = true;
							break;
						}
					}
					num++;
				}
				while (flag && num < 20);
			}
			mobileParty.Position2D = vec2;
			mobileParty.Party.Visuals.SetMapIconAsDirty();
		}

		public void AddSiegeEngineMissile(SiegeEvent.SiegeEngineMissile missile)
		{
			this._siegeEngineMissiles.Add(missile);
		}

		public void RemoveDeprecatedMissiles()
		{
			this._siegeEngineMissiles.RemoveAll((SiegeEvent.SiegeEngineMissile missile) => missile.CollisionTime.IsPast);
		}

		private bool StartingAssaultOnBesiegedSettlementIsLogical()
		{
			float num = 0f;
			float num2 = ((MobileParty.MainParty.CurrentSettlement == this.SiegeEvent.BesiegedSettlement) ? 0.5f : 1f);
			foreach (PartyBase partyBase in this.SiegeEvent.BesiegedSettlement.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege))
			{
				if (partyBase.IsMobile && partyBase.MobileParty.CurrentSettlement == this.SiegeEvent.BesiegedSettlement && (partyBase.MobileParty.Aggressiveness > 0.01f || partyBase.MobileParty.IsMilitia || partyBase.MobileParty.IsGarrison))
				{
					num += num2 * partyBase.TotalStrength;
				}
			}
			float num3 = 0f;
			LocatableSearchData<MobileParty> locatableSearchData = Campaign.Current.MobilePartyLocator.StartFindingLocatablesAroundPosition(this.SiegeEvent.BesiegedSettlement.Position2D, 10f);
			for (MobileParty mobileParty = Campaign.Current.MobilePartyLocator.FindNextLocatable(ref locatableSearchData); mobileParty != null; mobileParty = Campaign.Current.MobilePartyLocator.FindNextLocatable(ref locatableSearchData))
			{
				if (mobileParty.Aggressiveness > 0f && mobileParty.MapFaction == this.SiegeEvent.BesiegedSettlement.MapFaction && mobileParty.CurrentSettlement == null)
				{
					num3 += mobileParty.Party.TotalStrength;
				}
			}
			float num4 = 0f;
			foreach (PartyBase partyBase2 in this.SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege))
			{
				num4 += partyBase2.TotalStrength;
			}
			float settlementAdvantage = Campaign.Current.Models.CombatSimulationModel.GetSettlementAdvantage(this.SiegeEvent.BesiegedSettlement);
			float maximumSiegeEquipmentProgress = Campaign.Current.Models.CombatSimulationModel.GetMaximumSiegeEquipmentProgress(this.SiegeEvent.BesiegedSettlement);
			float randomFloat = MBRandom.RandomFloat;
			float num5 = num4 / (num * MathF.Pow(settlementAdvantage, 0.67f));
			bool flag = false;
			float num6 = 0.9f;
			if (num5 > num6)
			{
				float num7 = 0f;
				float num8 = 0f;
				foreach (PartyBase partyBase3 in this.SiegeEvent.BesiegerCamp.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege))
				{
					num7 += partyBase3.MobileParty.Food;
					num8 += -partyBase3.MobileParty.FoodChange;
				}
				float num9 = MathF.Max(0f, num7) / num8;
				float num10 = MathF.Min(1f, num3 / num4);
				float num11 = ((num9 < 3f) ? ((1f + (3f - num9) * (3f - num9)) * 0.2f) : 0f);
				float num12 = (MathF.Min(4f, MathF.Max(num5, 1f)) - 1f) * 0.2f;
				float totalStrength = this.SiegeEvent.BesiegerCamp.BesiegerParty.MapFaction.TotalStrength;
				float totalStrength2 = this.SiegeEvent.BesiegedSettlement.MapFaction.TotalStrength;
				float num13 = ((totalStrength < totalStrength2) ? ((1f - (totalStrength + 0.01f) / (totalStrength2 + 0.01f)) * 0.6f) : 0f);
				float num14 = MathF.Max(0.5f, 3f - num12 - num10 - num11 - num13);
				float num15 = MathF.Pow(settlementAdvantage, num14);
				int numberOfEquipmentsBuilt = Campaign.Current.Models.CombatSimulationModel.GetNumberOfEquipmentsBuilt(this.SiegeEvent.BesiegedSettlement);
				float num16 = (MathF.Min(9f, num5) - num6) / num15;
				num16 *= ((float)MathF.Min(2, numberOfEquipmentsBuilt) + 1f) / 3f;
				num16 *= 1f - 0.66f * (maximumSiegeEquipmentProgress * maximumSiegeEquipmentProgress);
				flag = num == 0f || randomFloat < num16;
			}
			return flag;
		}

		private void SetPrebuiltSiegeEngines()
		{
			foreach (SiegeEngineType siegeEngineType in Campaign.Current.Models.SiegeEventModel.GetPrebuiltSiegeEnginesOfSiegeCamp(this))
			{
				float siegeEngineHitPoints = Campaign.Current.Models.SiegeEventModel.GetSiegeEngineHitPoints(this.SiegeEvent, siegeEngineType, BattleSideEnum.Attacker);
				SiegeEvent.SiegeEngineConstructionProgress siegeEngineConstructionProgress = new SiegeEvent.SiegeEngineConstructionProgress(siegeEngineType, 1f, siegeEngineHitPoints);
				this.SiegeEngines.AddPrebuiltEngineToReserve(siegeEngineConstructionProgress);
				this.SiegeEvent.CreateSiegeObject(siegeEngineConstructionProgress, this.SiegeEvent.GetSiegeEventSide(BattleSideEnum.Defender));
			}
		}

		private float GetDistanceBetweenRangedEngineAndWall(int rangedEngine, int wallIndex)
		{
			float num = (float)rangedEngine * 1f;
			float num2 = 0.5f + 2f * (float)wallIndex;
			return MathF.Abs(num - num2) + 2f;
		}

		private float PriorityCalculationForWalls(float distance)
		{
			return 5f - distance;
		}

		private void FindAttackableWallSectionWithHighestPriority(int attackerSlotIndex, SiegeEngineType siegeEngine, out int targetIndex, out float targetPriority)
		{
			targetIndex = -1;
			targetPriority = 0f;
			if (siegeEngine.IsAntiPersonnel)
			{
				return;
			}
			float num = 9999f;
			MBReadOnlyList<float> settlementWallSectionHitPointsRatioList = this.SiegeEvent.BesiegedSettlement.SettlementWallSectionHitPointsRatioList;
			for (int i = 0; i < settlementWallSectionHitPointsRatioList.Count; i++)
			{
				if (settlementWallSectionHitPointsRatioList[i] > 0f)
				{
					float distanceBetweenRangedEngineAndWall = this.GetDistanceBetweenRangedEngineAndWall(attackerSlotIndex, i);
					float num2 = this.PriorityCalculationForWalls(distanceBetweenRangedEngineAndWall);
					if (num2 > targetPriority || (MathF.Abs(num2 - targetPriority) < 0.0001f && num > distanceBetweenRangedEngineAndWall))
					{
						targetIndex = i;
						targetPriority = num2;
						num = distanceBetweenRangedEngineAndWall;
					}
				}
			}
		}

		public void BombardHitWalls(SiegeEngineType attackerEngineType, int wallIndex)
		{
			MBReadOnlyList<float> settlementWallSectionHitPointsRatioList = this.SiegeEvent.BesiegedSettlement.SettlementWallSectionHitPointsRatioList;
			if (settlementWallSectionHitPointsRatioList[wallIndex] > 0f)
			{
				float siegeEngineDamage = Campaign.Current.Models.SiegeEventModel.GetSiegeEngineDamage(this.SiegeEvent, BattleSideEnum.Attacker, attackerEngineType, SiegeBombardTargets.Wall);
				float num = siegeEngineDamage / this.SiegeEvent.BesiegedSettlement.MaxHitPointsOfOneWallSection;
				this.SiegeEvent.BesiegedSettlement.SetWallSectionHitPointsRatioAtIndex(wallIndex, MBMath.ClampFloat(settlementWallSectionHitPointsRatioList[wallIndex] - num, 0f, 1f));
				bool flag = settlementWallSectionHitPointsRatioList[wallIndex] <= 0f;
				if (flag)
				{
					this.SiegeEvent.BesiegedSettlement.Party.Visuals.SetMapIconAsDirty();
				}
				CampaignEventDispatcher.Instance.OnSiegeBombardmentWallHit(this.BesiegerParty, this.SiegeEvent.BesiegedSettlement, BattleSideEnum.Attacker, attackerEngineType, flag);
				Debug.Print(string.Concat(new object[]
				{
					this.SiegeEvent.BesiegedSettlement.Name,
					" - ",
					BattleSideEnum.Attacker.ToString(),
					" ",
					attackerEngineType.Name,
					" hit the walls for ",
					siegeEngineDamage
				}), 0, Debug.DebugColor.Yellow, 137438953472UL);
			}
		}

		public void GetAttackTarget(ISiegeEventSide siegeEventSide, SiegeEngineType siegeEngine, int siegeEngineSlot, out SiegeBombardTargets targetType, out int targetIndex)
		{
			targetType = SiegeBombardTargets.None;
			targetIndex = -1;
			int num;
			float num2;
			siegeEventSide.SiegeEvent.FindAttackableRangedEngineWithHighestPriority(this, siegeEngineSlot, out num, out num2);
			int num3;
			float num4;
			this.FindAttackableWallSectionWithHighestPriority(siegeEngineSlot, siegeEngine, out num3, out num4);
			if (num == -1 && num3 == -1)
			{
				return;
			}
			if (num == -1)
			{
				targetIndex = num3;
				targetType = SiegeBombardTargets.Wall;
				return;
			}
			if (num3 == -1)
			{
				targetIndex = num;
				targetType = SiegeBombardTargets.RangedEngines;
				return;
			}
			float num5 = num2 + num4;
			if (MBRandom.RandomFloat * num5 < num2)
			{
				targetIndex = num;
				targetType = SiegeBombardTargets.RangedEngines;
				return;
			}
			targetIndex = num3;
			targetType = SiegeBombardTargets.Wall;
		}

		public void FinalizeSiegeEvent()
		{
			if (!this.GetInvolvedPartiesForEventType(MapEvent.BattleTypes.Siege).IsEmpty<PartyBase>())
			{
				this.RemoveAllSiegeParties();
			}
		}

		[SaveableField(8)]
		private readonly List<MobileParty> _besiegerParties;

		[SaveableField(1)]
		private MBList<SiegeEvent.SiegeEngineMissile> _siegeEngineMissiles;

		[SaveableField(3)]
		private float _attackerVulnerableDurationLeft;

		[SaveableField(4)]
		private float _attackerVulnerableDayCount;

		[SaveableField(5)]
		private float _attackerVulnerableDueTime;
	}
}
